- appveyor.yml
I have updated the AppVeyor notifications section to include a custom webhook for posting information to the newly created Gitter Chat Room for the choco repository:
https://gitter.im/chocolatey/choco
This will make information about new builds starting/stopping/failing etc, appear in the activity stream, similar to what happens in the ChocolateyGUI chat room:
> (build) Adding Gitter Notification

- src/chocolatey/ObjectExtensions.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/configuration/PackagesConfigFilePackageSetting.cs
- src/chocolatey/infrastructure.app/configuration/PackagesConfigFileSettings.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
If a config file is specified, use that to determine settings for each
package to install. Clone the config and make adjustments based on what
is in the packages.config file for that particular package.
Closes #10
> (GH-10) Packages.config

- src/chocolatey/GetChocolatey.cs
add a RunConsole overload that can parse commandline args with the Console runner.
I'd like to use this with Boxstarter since it simply intercepts user choco calls via unparsed commandline args.
~~Depends on #130.~~
Closes #135
> (GH-135) Adds a Console Runner to GetChocolatey

- .gitignore
- src/chocolatey/infrastructure.app/runners/GenericRunner.cs
The warning happens on API calls when choco.exe is not on the system,
so it should reference the product name "chocolatey" not the app name.
> (maint) Change the "not an official build" warning

- src/chocolatey.tests/infrastructure.app/commands/ChocolateySourceCommandSpecs.cs
- src/chocolatey/GetChocolatey.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateySourceCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateySource.cs
- src/chocolatey/infrastructure.app/runners/GenericRunner.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
- src/chocolatey/infrastructure.app/services/IChocolateyConfigSettingsService.cs
- src/chocolatey/infrastructure/commands/IListCommand.cs
This is mostly so you can review and provide feedback ;-)
> Start exposing lists and package results via the API #132

- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey.resources/helpers/functions/Generate-BinFile.ps1
Previously, Chocolatey had an internal helper function
called Generate-BinFile.  While this was never part of the
public API, many packages take a dependency on it.
Without this change, a number of packages will fail to
install.
Closes #145
> Added Generate-BinFile Helper

- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey.resources/helpers/functions/Remove-BinFile.ps1
Previously, Chocolatey had an internal helper function
called Remove-BinFile.  While this was never part of the
public API, many packages take a dependency on it.
Without this change, a number of packages will fail to
install.
Closes #195
> Added Remove-BinFile Helper

- src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1
- src/chocolatey.resources/helpers/functions/Get-WebFile.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyZipPackage.ps1
Adds the ability for packages that use Get-ChocolateyWebFile.ps1 or
Get-WebFile to specify customer headers during the request. See #332 or
powershell documentation for example usage
> (GH-332) Custom headers support for downloads

- nuget/chocolatey.lib/chocolatey.lib.nuspec
This corrects the version of log4net declared in the chocolatey.lib
nuspec. changing it to 2.0.3 which maps to assembly version 1.2.13.
Closes #390
> (GH-390) Fix log4net dependency version in nuspec

- .build.custom/ilmerge.replace.build
- .build.custom/ilmergeDLL.build
- .build/ilmerge.build
- lib/NuGet-Chocolatey/strongname.cmd
Makes chocolatey builds more portable and allows it to be built on .net
4.5+ machines while maintaining compatibility with .net 4.0 clients.
Closes #392
> (GH-392) pass 4.0 reference assemblies to ilmerge

- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey.resources/helpers/functions/Format-FileSize.ps1
- src/chocolatey.resources/helpers/functions/Get-FtpFile.ps1
- src/chocolatey.resources/helpers/functions/Get-WebFile.ps1
> (GH-363) Show human-readable file sizes when downloading

- Scenarios.md
- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/infrastructure/filesystem/DotNetFileSystemSpecs.cs
- src/chocolatey.tests.integration/infrastructure/filesystem/context/attributes.txt
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/FilesService.cs
- src/chocolatey/infrastructure.app/services/IFilesService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure/filesystem/DotNetFileSystem.cs
- src/chocolatey/infrastructure/filesystem/IFileSystem.cs
> (GH-338) Delete read only files

- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
See #427.
Adds `--page=#` and `--page-size=#` to `ListCommand`. Page size defaults to 25.
> (GH-427) Add paging to ListCommand

- .build.custom/ilmerge.internalize.ignore.txt
Externalizes more package information necessary to process package data returned from Chocolatey's PackageResult list.
Closes #433
> (GH-433) Externalize more Package Information

- src/chocolatey/GetChocolatey.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySourceCommand.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/runners/GenericRunner.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/CygwinService.cs
- src/chocolatey/infrastructure.app/services/IChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/ISourceRunner.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/PythonService.cs
- src/chocolatey/infrastructure.app/services/RubyGemsService.cs
- src/chocolatey/infrastructure.app/services/WebPiService.cs
- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
- src/chocolatey/infrastructure/commands/IListCommand.cs
Adds the ability to efficiently retrieve a "count" for a given list command. Usefully for when you want to total number of given packages for a command that meets certain search criteria, but you're also using paging and need a reliable "total". Mostly only relevant to NuGet at this point.
Closes #431
> (GH-431) Add Count to List Command API

- CONTRIBUTING.md
Changed the link from "Community tag" to "Up for Grabs"
> (maint) README.md - Update "Community tag" link

- src/chocolatey/infrastructure.app/templates/ChocolateyUninstallTemplate.cs
resubmitting to `stable` instead of `master`
Supersedes #536 
Closes #534
> (GH-534) packagename needed for zip uninstalls

- src/chocolatey/AssemblyExtensions.cs
- src/chocolatey/GetChocolatey.cs
- src/chocolatey/infrastructure.app/runners/GenericRunner.cs
When using the API, it should resolve merged assemblies but it may
not if there is an assembly handler registered. Before loading up
code that resolves external assemblies, register an AssemblyResolve
handler with the purpose of determining if the assembly has
Chocolatey's Public Key token or not. If it does, use Chocolatey's
merged assembly instead of the conflicting assembly.
Closes #769
> (GH-769) API - Resolve Merged Assemblies

- README.md
Fixed a typo in a readme.md file
```diff
-guidlines
+guidelines
```
missing comma added
```diff
-In the future we hope that
+In the future, we hope that
```
> Typo fixed in a readme.md

- CONTRIBUTING.md
seems like the intent is to `wrap` at `72`characters, not to `indent`.
> clarify word choice

- docker/Dockerfile.linux
- docker/README.md
- docker/choco_wrapper
This PR provides a Dockerfile and choco_wrapper script to enable easy Linux based choco.exe usage.
The Dockerfile copies the entire source tree into the container and then builds choco.exe using the build.sh script.
The choco_wrapper is copied into /usr/local/bin/choco and allows for easier execution of choco.exe using mono.
I suggest linking the repository to Docker Hub and releasing various versions of the Docker image using their build process.
> Dockerfile to Enable Mono Based Choco Builds

- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
The former fix (GH-1210) fails when the CacheLocation ends with a slash. This uses a DirectoryInfo instance to examine the last directory in the path in a more robust manner
> (GH-1231) Use DirectoryInfo to evaluate CacheLocation

- src/chocolatey/infrastructure/licensing/LicenseValidation.cs
Turn off the function within licensing framwork to re-assert license file after a set period of time.
Fixes #1500
> (GH-1500) Disable re-validation of Chocolatey License File

- .build.custom/ilmerge.replace.build
- src/chocolatey.console/Program.cs
- src/chocolatey.console/chocolatey.console.csproj
- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey.sln
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey/GetChocolatey.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyUnpackSelfCommand.cs
This includes:
* New Compilation Directive, `LibOnly` to control when certain pieces of code are compiled
* Conditional inclusion of referenced projects
* Modification to build process to only ilmerge certain projects, based on configuration
Fixes #1496
> (GH-1496) Enable ability to create a trimmed down version of Chocolatey.Lib

- nuget/chocolatey/tools/chocolateysetup.psm1
> (GH-1401) Added initial call to Chocolatey after installation

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This allows a Chocolatey Package structure similar to the following:
Which simply contain:
On installation, a `.ignore` file will be created for the alternative architecture (relative to what is being installed):
And a shim will be created pointing at the correct architecture:
Fixes #1365
> (GH-1365) Support architecture folder in tools folder

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
When no sources are active and someone is searching a local source,
allow that to continue without throwing an error. This will allow the
sources to be configured to the local source a littler further in and
then return results instead of throwing an error.
Closes #661
> (GH-661) allow local only without sources

- README.md
In order to build on a windows machine you must have .NET Framework 3.5 installed ( typically done via the windows feature functionality ).  Once installed building will continue to work.  I assume this might be installed by default on desktop O/S's but not the default on newer Windows Server O/S's due to reducing the attack surface of a box.
This Closes #1650
> (doc) .NET Framework 3.5 Feature Required for windows builds

- src/chocolatey/infrastructure.app/domain/RegistryValueExtensions.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageInformationService.cs
- src/chocolatey/infrastructure.app/services/RegistryService.cs
- src/chocolatey/infrastructure/tolerance/FaultTolerance.cs
Relates to #1581
Right now what causes a .registry file to be renamed to a .registry.bad file is not easily 
identifiable. Provide more logging surrounding that. Bump up the number of attempts 
to deserialize the file as well from one to two. This will add a little more fault tolerance 
in case something times out.
> (GH-1581) add more tolerance, logging around bad registry snapshots

- src/NuGet.Config
Depending on the end user setup, the machine level NuGet Configuration
file can include an entry for the v3 NuGet feed.  This causes problems
when restoring packages for the Chocolatey build, since two packages
(NUnit.Runners and coveralls) do not restore from the v3 feed, only the
v2 feed.  By specifying this feed in the solution level NuGet.Config
file, should mean that they restore correctly on any machine.
NOTE: The existing NuGet.Config file in the .nuget folder actually
doesn't seem to be being used at all.  Based on the documentation here:
https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior
A NuGet.Config file is looked for at the location of the sln file,
upwards to the root of the drive.  As a result, the existing file is
being ignored.
Fixes #1816
> (GH-1816) Add NuGet.Config beside sln file

- src/chocolatey/infrastructure.app/nuget/NugetList.cs
find_package will either return the package that was found, or null.
The case for null being returned needs to be handled, so that upstream
callers are not affected.
Fixes #1837
>  (GH-1837) Handle potential for null package

- .github/ISSUE_TEMPLATE/SecurityDisclosure.md
- .github/SECURITY.md
This addition, changes the following:
To this:
Which, once you click on it, show the policy, rather than starting to create a new issue:
We might want to expand on the content a little bit.  For example, this is what @AdmiringWorm (who I am stealing the idea from) is using:
https://github.com/WormieCorp/.github/blob/master/.github/SECURITY.md
And also another example here:
https://github.com/standard/.github/blob/master/SECURITY.md
Thoughts?
> (doc) Add security.md file

- .uppercut
- build.official.bat
- src/chocolatey.console/Program.cs
- src/chocolatey.console/chocolatey.console.csproj
- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey.sln
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey/GetChocolatey.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure/licensing/License.cs
This will be used when preparing for an official release of Chocolatey,
to ensure that the correct strong name key is being used, and also that
the necessary checks are being done when loading the Chocolatey Licensed
assembly into the Chocolatey process.  The FORCE_CHOCOLATEY_OFFICIAL_KEY
compilation symbol if used in if/def statements to make this logic
happen.
A new build.official.bat file was also created to make the calling of
this specific build easier to do as well.
Relates to #1949
> (GH-1949) New official release build configuration

- README.md
removed gratipay "badge" as the service is [offline since End of 2017](https://gratipay.news/vive-la-liberapay-14057a25eacb)
> (doc) Update README.md, removing gratipay "badge"

- docker/Dockerfile.linux
Installs git in the docker container before building chocolatey so the build script is able to get version information.
> (GH-2023) Install git in the docker container.

- CONTRIBUTING.md
Previously the contribution documentation linked to clahub
which was used as a way for contributors to sign the CLA.
This PR changes this to cla-assistant which is now
being used.
Unfortunately, this also meant removing the link regarding what a CLA is, and why anyone should care as I could not find any equivalent page for this.
> (doc) Changed cla links from clahub to cla-assistant

- src/chocolatey/infrastructure.app/templates/ChocolateyTodoTemplate.cs
This used to be housed within ferventcoder's GitHub profile, but this
has now been moved under the Chocolatey GitHub Organisation.
Fixes #2105
> (GH-2105) Update link to Chocolatey workshop

- CONTRIBUTING.md
GH- is specific to GitHub, where as, # works across different version
control systems, so it makes sense to get into the habit of using
something that works everywhere.
> (doc) Update to prefer # rather than GH-

- .travis.yml
Fixes https://github.com/chocolatey/choco/issues/2227
> (#2227) Bring Ubuntu to 18.04 in Travis

- src/chocolatey.resources/helpers/chocolateyInstaller.psm1
The Chocolatey GUI Extension is a "special" extension in the sense that
it isn't intended to work with Chocolatey directly, but it is shipped as
a "normal" Chocolatey extension. We don't want to load the
chocolateygui.licensed.dll into the choco.exe process, but rather leave
it alone, and allow Chocolatey GUI to load it when required.
We are already skipping one existing folder when looking for extension
paths, so this has been extended to include the chocolateygui foler.
Fixes #2078
> (#2078) Skip importing Chocolatey GUI Extension

- src/chocolatey/infrastructure.app/commands/ChocolateyVersionCommand.cs
Update the deprecation note from `choco upgrade pkgname --noop` to `choco outdated`
Fixes #2048
> (GH-2048) update deprecation note to outdated

- src/chocolatey/infrastructure.app/configuration/ConfigFileApiKeySetting.cs
Fixes `Equals` implementation of `ConfigFileApiKeySettings`.
This is the line which failed due to `Equals` not working correctly:
https://github.com/chocolatey/choco/blob/98f80533574bd4b7bd8c59698ee2441a164ccebc/src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs#L338
Closes #1889.
> (GH-1889) Fixes Equals implementation of ConfigFileApiKeySettings

- src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1
> (GH-2203) Get-ChocolateyUnzip add unzipLocation as an alias to Destination

- src/chocolatey/infrastructure.app/tasks/RemovePendingPackagesTask.cs
fixes #1866
fixes #1941
fixes https://github.com/actions/virtual-environments/issues/3010
Created a repro over at https://github.com/jetersen/test-choco-pack-github-action
Opened this PR as #1941 was not signed, which I assume was blocking.
This should help alleviate the initial choco startup on CI systems.
> (#1866) Avoid recursive search for pending package removal

- src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
Fixes #1364 
Changes the encoding of `.nuspec` files created from templates to UTF8 with BOM to UTF8 without BOM according to best practices in the [Creating Chocolatey Packages](https://chocolatey.org/docs/create-packages#character-encoding) documentation. Applies to both the default template and to custom templates.
Adjusted template services tests to include UTF8 no BOM files, otherwise nuspec files would not be detected anymore.
I moved only the nuspec over to no BOM for both the default template and custom templates. The other `.txt` files from the default template could be moved over to no BOM very easily if that is wanted.
> (GH-1364) Template create .nuspec encoded without BOM

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
It is possible that the installation of an application can generate
multiple registry keys within the snapshot file that is craeted.  Rather
than looking at only the first registry key when deciding if an installed
application is covered by a Chocolatey package, look at all keys within
the snapshot file.
Fixes #2092
> (GH-2092) Take all registry keys into account

- src/chocolatey/infrastructure.app/services/NugetService.cs
The log message when trying to downgrade a program
shows a variety of switches, --force, --allow-downgrade
One of these is formatted as prose, side by side
Changed to reflect proper switch syntax.
> (maint) Improve log message

- src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
- Add a ScriptBlock parameter to Install-ChocolateyPackage.ps1 that if present, is called after download but before install.
Closes #1060
> (GH-1060) Add BeforeInstall parameter to Install-ChocolateyPackage.ps1

- CHANGELOG.md
- README.md
- src/chocolatey/infrastructure.app/templates/NuspecTemplate.cs
[RawGit](https://rawgit.com/) is shutting down since October 2018, the content already been                                                                                                                          
serving will continue to be served until at least October of 2019, but                                                                                                                        
new content will not be served, the homepage https://rawgit.com/ says:                                                                                                                        
> If you're currently using RawGit,                                                                                                                                                           
> please …
> (maint) Replace RawGit with raw.githack.com CDN

- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyNewCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPackCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUnpackSelfCommand.cs
This improves the terminology in choco.exe help output with the suggestions and new terminology.
Fixes #1861
> (#1861) This improves the terminology in choco.exe help output

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
Currently, the method logs that the command was "completed" even if it failed. A log that says the step failed would make more sense to the user in this case.
Closes #1962.
> (#1962) Use different message on error

- src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyZipPackage.ps1
Add / clarify the SpecificFolder parameter for the PowerShell helper functions.
Closes #2190.
> (#2190) Clarify help for SpecificFolder parameter

- src/chocolatey.tests/infrastructure/filesystem/DotNetFileSystemSpecs.cs
The should_find_existing_executable() test has a hardcoded path to the
ls executable, which is incorrect on systems with a merged usr
directory, as they have binaries under /usr/bin instead of under /bin
Switches the test to work with both path.
Fixes: #2236 
I'm pretty sure `ShouldBeInRange` is the correct thing to use, but feel free to correct if there is a better method to use.
> (#2236) Mono test work with merged usr systems

- README.md
- docker/Dockerfile.linux
- Bumps version of Mono in the Dockerfile
- Adds Ubuntu 20.04 instructions
- Removes instructions for RHEL and Fedora as they were out of date (and pretty much unmaintained AFAIK), link to official Mono install instructions instead.
> (#2227) Update Mono version and installation instructions

- .build/compile.step
Removes basedir from Mono build on non-windows platforms.
This lets xbuild be located at other locations, as long at it's on the path
Fixes: #2238 
I'm not %100 sure that this is the best solution, but it seems to work everwhere I have tested it.
Ubuntu, Debian, Docker, and MacOS (in Github actions) all build.
I'm not super familiar with uppercut, so if there is a better way to do this, I'm all ears.
> (#2238) Mono build don't hardcode xbuild path

- src/chocolatey/infrastructure.app/services/NugetService.cs
Always deep copy the config when making a backup originalConfig. This
ensures that when the config is reset it gets fully reset. Fixes issues
with reuse of arguments when useRememberedArgumentsForUpgrades is
enabled.
Hopefully fixes: #1443
Fixes: #2111
I have tested this with the procedure in [this comment](https://github.com/chocolatey/choco/issues/2111#issuecomment-759124896), and with this patch, it no longer upgrades python3 to a prerelease build, while without this patch it does.
> (#2111) Deep copy config

- src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1
(GH-2044) This fixes a problem when a package is installed under the System credentials (typically how centralized management software -- e.g. SCCM -- operate):
Running as `SYSTEM`, the `$env:Temp` variable is normally *C:\Windows\Temp*. If the **first** package to ever use `Update-SessionEnvironment.ps1` happens to be running as `SYSTEM`, the location of `$env:Temp` changes to *C:\Windows\system32\config\systemprofile\AppData\Local\Temp* for the duration of the session.  This change to `$env:Temp` does not occur in subsequent calls to `Update-SessionEnvironment.ps1`.  It is unknown why this change occurs at all and likewise is unknown why it occurs for only the first time.
The `Update-SessionEnvironment.ps1` normally gives priority to user-scope environment variables over machine-scope …
> (GH-2044) Fix for changing $env:Temp

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyExportCommandSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyExportCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/registration/ContainerBinding.cs
- src/chocolatey/infrastructure.app/services/INugetService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This will allow the creation of a packages.config file of all the
currently installed packages on the machine.  Usage of this command
will be:
choco export -o c:/temp/packages.config --include-version-numbers
This command is particularly useful when re-building a machine.  i.e.
First export all packages currently installed on machine, and then
replay this packages.config via choco install packages.config on new
machine.
Fixes #357
> (#357) Add Export Command

- src/chocolatey/infrastructure.app/services/NugetService.cs
When using a relative path, pack only works if the current directory is
the same as the directory containing the nuspec. This switches the
relative path to an absolute path for non-windows platforms (windows
already uses an absolute path). This change allows pack to work from
any directory.
Previously, in c0b23a6 and e5a02a0, non-windows platforms were switched
to using a relative path for files, so that the default files separator
in the nuspec files element could be switched to a backslash (#2166)
However, the issue with forward/back slashes is fixed by
chocolatey/nuget-chocolatey#19, so the previous change can now be
reverted.
Fixes #2263
> (#2263) Pack on Mono pass absolute path to PackageBuilder

- README.md
This pull request adds two new badges to the Readme.md documentation.
It adds 1 badge for the new GitHub Action builds added, as well as 1 badge for the upcoming docker image.
fix #2244
> (#2244) Add badges for GitHub Action and Docker

- src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1
Fixes #2112 
* Adds support for the msp file type in `Install-ChocolateyInstallPackage
Verified no additional changes were required to wire this up in `Start-ChocolateyProcessAsAdmin`
> (GH-2112) Add msp installer support to Install-ChocolateyInstallPackage

- README.md
Fixed GitHub format in README.md.
```diff
-  Github
+  GitHub
```
> (doc) fix typo in Readme

- .build/compile.step
Add flag to invocation of NuGet.exe when running on Ubuntu to prevent failures when restoring packages
Closes #2313
> Prevent failing builds on Ubuntu

- src/chocolatey/GetChocolatey.cs
This PR makes changes to the API initialization method to allow
Chocolatey to allow the initialization to happen without enabling
logging.
Additionally changes have been made to allow adding extra loggers to be
added without overriding the logging
to the applications main chocolatey.log file.
These changes were necessary to allow programs (like ChocolateyGUI)
to add its own logging infrastructure without disabling logging
to the main log file.
fixes #2124
> (#2124) Add ability to initialize without logging

- Scenarios.md
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/context/exactpackage/exactpackage/0.9.0/exactpackage.nuspec
- src/chocolatey.tests.integration/context/exactpackage/exactpackage/0.9.0/tools/purpose.txt
- src/chocolatey.tests.integration/context/exactpackage/exactpackage/1.0.0-beta1/exactpackage.nuspec
- src/chocolatey.tests.integration/context/exactpackage/exactpackage/1.0.0-beta1/tools/purpose.txt
- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
Due to a prior fix in the logic for `list -e -a`, all packages with the target ID were being returned, regardless of whether the user uses the `--pre` flag or not. Since the same search without `--exact` does not return prerelease versions unless the `--pre` option is also passed, the behaviour for `list -e -a` should match this.
This fix modifies the search logic used when listing all package versions with `--exact` to also check for and respect the `--pre` flag from the configuration context, much like other list commands use the setting in this file in other places.
- (breaking) `choco list $x --all --exact` no longer lists prerelease packages by default
- `choco list $x --all --exact --pre` lists everything, prereleases included
Fixes #2304 
You can either build choco from this branch …
> (#2304) Make list --exact --all-versions to filter out prereleases by default

- nuget/chocolatey.lib/chocolatey.lib.nuspec
- nuget/chocolatey/chocolatey.nuspec
Use PNG instead of GIF for the iconUrl in the nuspec. The PNG icon 
is also available next to the GIF icon, and it is able to be used with 
integrations that may not recognize GIF files.
Closes #2322
(recreated from ferventcoder fork - did not feel comfortable force pushing to upstream)
> (#2322) Use PNG for nuspec iconUrl

- src/chocolatey.resources/helpers/chocolateyInstaller.psm1
Removed the code section where we load extension DLLs directly when preparing for a chocolatey package installation.
As there isn't a way to determine whether a DLL is a usable PowerShell module without loading it into memory, we're better off not loading DLLs directly, as it has caused issues several times in the past (see: #2078, #1041).
This has previously required us to create an ever-expanding list of exceptions to the loading behaviour.
Instead, if folks want to load DLLs as powershell modules, they can package them alongside a PSM1 file that handles the DLL import itself. (See #2333 for some examples)
This removes the need for Chocolatey to guess which dlls are powershell modules and which should not be loaded.
- Create a new chocolatey package in `C:\Packages`:
```powershell …
```
> (#2333) Disable loading of DLL under extensions path

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/utility/ArgumentsUtilitySpecs.cs
This is starting to be used in other places, so we should have some
tests around the execution of the logic contained within this class to
ensure that there are no regressions if/when editing this class.
For now, all the current expectations are covered within the different
TestFixtures, but this should be extended if any changes are made to
the class.
> (test) Add unit tests for ArgumentsUtility class

- GenerateDocs.ps1
Several places in the documentation reference `https://comminty.chocolatey.org/packages` (e.g. [commands/list](https://docs.chocolatey.org/en-us/choco/commands/list)), which is not a valid domain as of right now, and I can't find any other occurrences of this. So I assume `comminty` is a typo of `community`.
> (doc) Fix typo in community feed URL

- build.debug.sh
- build.official.sh
Fixes: #2358
I think we may have to dig into uppercut as well to get the code signing working on Mono.
> (#2358) Add official and debug Mono build scripts

- docker/Dockerfile.linux
- docker/README.md
- docker/choco_official_wrapper
- docker/choco_wrapper
Rework the Dockerfile for Linux. Move to a multi-stage build so the
source code is not brought along into the final image (#2364). Add
build args to select the build script and mono version to use. Remove
deprecated MAINTAINER instruction and add metadata with LABEL (#2361).
Add "choco.exe" to path, so both "choco" and "choco.exe" can be used,
like Windows supports (#2362). Change the install location to
"/opt/chocolatey" as that is more in line with the Linux filesystem
hierarchy (#2360). Create the "lib" directory to prevent the warning
about the directory not being found (#2363).
The choco_official_wrapper is used for official builds, where the
"--allow-unofficial" argument is not needed.
Fixes: #2360
Fixes: #2361 
Fixes: #2362 
Fixes: #2363 
Fixes: #2364 
The debug and official build …
> (#2364) Rework Linux Dockerfile

- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure/filesystem/DotNetFileSystem.cs
Fixes #2370 
Fixes #2369 
This prevents absolute paths being converted to relatives paths by the removal of the leading forward slash.
Fix created by @AdmiringWorm, I just typed up a repro and packaged it up into commits.
> (#2369 #2370) Do not trim forward slashs prefixes on Linux

- README.md
Fixes #2025
If another location for this documentation is more appropriate (perhaps somewhere in the docs repository), feel free to redirect this or point me in the right direction.
> (#2025) Document install process on other platforms.

- src/chocolatey.resources/helpers/functions/Get-WebFile.ps1
The explicitly added Authorization header does not get added to the request object (re instead of req).
That means downloading a file by choco, which requires an Authorization header to bet set, is currently not possible.
An error message like this will be shown: "The property 'Authorization' cannot be found on this object. Verify that the property exists and can be set."
> Fix typo in setting Authorization header

- src/chocolatey/infrastructure.app/nuget/NugetPack.cs
Mono does not truncate streams in System.IO.Packaging.Package.Open
when using FileMode.Create, while .Net does. mono/mono#21055
This always truncates the stream at the start.
Fixes #2076
> (#2076) Pack always truncate stream

- src/chocolatey/infrastructure.app/nuget/NugetPack.cs
If there is not a <files> element in the .nuspec, then the pack command
will gather up a list of all of files the in the directory which is
used to include them in the package. However, the nuspec should not be
included in this list, because it is auto-regenerated. The .nupkg also
should not be included. Therefore, there is a filter to remove the
.nuspec and .nupkg from the list of files.
However, this filter has the directory separator hardcoded as a
backslash. This does not work correctly on platforms where the
directory separator is a forward slash. Therefore, this fixes
the directory separator to be correct depending on what platform choco
is running on.
This patch was written by @AdmiringWorm, I just created the reproduction and packaged it up into a commit. …
> (#2379) Correct pack files filter for Linux

- src/chocolatey/infrastructure.app/templates/ChocolateyReadMeTemplate.cs
When creating the PR to alow ChocolateyExitOnRebootDetected, it was
planned to be released on 0.10.16+, but that version was never released
Changed to the next version number that is actually released.
> (docs) Change incorrect version number.

- src/chocolatey/infrastructure.app/templates/NuspecTemplate.cs
Remove the "Building from Linux?" note from the built-in template nuspec.
Now that #502 has been fixed, it is not longer relevant.
Fixes #2384
> (#2384) Remove building from linux note from template

- src/chocolatey/infrastructure/filesystem/DotNetFileSystem.cs
Linux and MacOS do not normally have a "SystemDrive" environment
variable since they have everything under a single root of "/".
This switches to use "/" instead of "SystemDrive" on non-Windows
platforms. These two instances are the only ones I see in the C#
codebase. There are a couple of uses of "SystemDrive" in the PowerShell
helpers, but those are not run on non-Windows platforms.
Fixes #2383 
How this PR was tested:
- Debugged with VS on Windows, validated that "systemDrive" variable was "C:"
- Built on Linux, ran `choco --verbose --debug` to validate the warning about not being able to cleanup NuGet temp folders went away.
> (#2383) Use "/" instead of SystemDrive on non-Windows platforms

- src/chocolatey/infrastructure.app/services/AutomaticUninstallerService.cs
The InstallLocation can sometimes have quotes around the file path. When this happens we don't detect the directory as existing even when it does. As such, the uninstall doesn't actually happen. This change removes the quotes before we ask the File System Provider if the directory exists.
Tested this by Installing the Lastpass Chocolatey package then running `choco uninstall --fromprograms` (This is a licensed feature) and confirmed that it successfully called the uninstaller.
I have created a test package `uninstall-from-programs` that can be used for testing this as well (it creates an install entry with quotes and does not successfully uninstall without this change).
Fixes #2336 
The manual testing documentation for chocolatey.extension has been updated to include testing the …
> (#2336) Remove quotes from InstallLocation

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/services/ChocolateyPackageServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This commit updates the handling of packages when they are read from
a `.config` file to make sure that the SourceType property will be
correctly set.
This was needed for subsequent code to resolve the Source Runner correctly
when the specified source is not a normal Chocolatey package source.
fixes #877
The following packages.config file was created:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
<package id="IIS-WebServerRole" source="windowsfeatures" />
<package id="windirstat" version="1.1.2.20161210" />
</packages>
```
And then the command `choco install test.config` file was run.
When running with current released version of Chocolatey, this causes an error, since the IIS-WebServerRole package can't be found.
When running with the code from this branch, the feature was …
> (#877) Set SourceType for packages parsed from config

- src/chocolatey/infrastructure.app/services/CygwinService.cs
- src/chocolatey/infrastructure.app/services/PythonService.cs
- src/chocolatey/infrastructure.app/services/RubyGemsService.cs
- src/chocolatey/infrastructure.app/services/WebPiService.cs
- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
This throws an exception if running on a non-windows system for all sources
except for nuget.
If there is a better place to add the checks, let me know, not a big deal to change.
All of the alternates sources were broken on non-windows platforms, so this displays a
helpful error message instead of the misc error messages.
Later on, the python and ruby sources could theoretically be fixed to work on
non-windows.
Built the code and ran these commands on a windows system to validate that each source gets past the added check:
```
choco install invalid-id -s python
choco install invalid-id -s windowsfeatures
choco install invalid-id -s cygwin
choco install invalid-id -s ruby
choco install invalid-id -s webpi
```
On a side note, it looks like the `ruby.portable` package is broken.
Built the …
> (#2424) Disable alternate sources on non-windows

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/utility/PackageUtilitySpecs.cs
- src/chocolatey/infrastructure.app/utility/PackageUtility.cs
Two variables appeared to have been swapped accidentally when this
check was created in e91f209. The "package" is the var from the config,
while the "packageName" is the var that is being checked if it is in
the config. This fixes that swap.
This also changes the check for a directory separator in the name to
work on non-windows as well.
Also, this adds tests for the package_is_a_dependency method to make sure that this issue does not regress.
There is a bug when installing via a direct path to a nupkg that the package is incorrectly determined to be a dependency. These changes should fix that bug.
1. Added unit tests
2. Installed a package via `choco install \\path\\to\\package.nupkg --verbose --debug --ia="shouldseeargs"` and validated that the `chocolateyInstall.ps1` was called with …
> (#2089) Fixes package_is_a_dependency when install called with direct path to nupkg

- src/chocolatey/infrastructure.app/utility/ArgumentsUtility.cs
Remove redundant checks for `-api-key` and `-apikey`.
The check for potentially sensitive parameters was checking for both `-api-key` and `-apikey` twice. This PR removes the redundant check.
I ensured both `test.bat` and `build.bat` still ran successfully.
Small maintenance change, didn't open an issue (can open one if we feel it's needed).
> (maint) Remove duplicate sensitive parameter check

- .build/analyzers/nunit.test.step
- .build/analyzers/test.step
- .github/workflows/build.yml
- .github/workflows/test.yml
- test.bat
- test.sh
- Adds a `full` target to the uppercut testing, which runs all tests but `NotWorking` and `Ignore` tests. It can be called with `test.bat full`
- Adds a `test.sh` script for non-Windows systems. 
- Adds a scheduled workflow to run `test.bat full` on the Windows, runs `test.sh` on non-Windows. 
Running the integration tests on the Actions workflow is needed for feature parity with the Appveyor CI run.
N/A, see github actions workflow
Fixes #2432
> (#2432) Actions workflow run integration tests

- src/chocolatey/infrastructure.app/commands/ChocolateyApiKeyCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
Replaces outdated bit.ly links with updated ch0.co links.
https://ch0.co/nexus2apikey points to
https://help.sonatype.com/repomanager3/formats/nuget-repositories/deploying-packages-to-nuget-hosted-repositories
https://ch0.co/packages_config points to
https://docs.chocolatey.org/en-us/choco/commands/install#packages.config
The apikey help link was updated to the latest nexus 3 documentation from the previous
bit.ly link to nexus 2 documentation
The install help link was updated to the docs site from the previous bit.ly link to the
now removed GitHub wiki.
Ran `choco install -h` and `choco apikey -h` to validate that the links are updated correctly.
Fixes #2401
> (#2401) Replace bit.ly with ch0.co links

- src/chocolatey/infrastructure/cryptography/DefaultEncryptionUtility.cs
When running on mono on a non-Windows system, the ProtectedData methods
use /usr/local/.mono/keypair as the folder to save keypairs. This
folder is not normally writable by non-root users, thus erroring when
used by a normal user.
This catches that error and falls back to using the CurrentUser scope.
Also, during data unprotection, it will try to fall back to CurrentUser
scope if the decryption fails for other reasons, so as to attempt to
decrypt data encrypted with CurrentUser if the LocalSystem scope starts
working.
I'm not convinced that this is the best way to fix this issue, if people have better ideas, I'm all ears.
1. Built source on Linux machine
2. Removed all files under `/usr/share/.mono/keypair` (don't do this if you use mono for other things on that install)
3. Ran `mono …
> (#2437) Fall back to CurrentUser scope when permission denied

- .github/workflows/test.yml
- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/infrastructure.app/services/FilesServiceSpecs.cs
- src/chocolatey.tests.integration/infrastructure/commands/CommandExecutorSpecs.cs
- src/chocolatey.tests.integration/infrastructure/filesystem/DotNetFileSystemSpecs.cs
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
Get integration tests working on non-windows platforms. 
Skips most of the tests that are not working.
Misc fixes (TODO, describe) to get some tests working. Path seperator, casing, typo in string, etc
Currently, the integration tests can only be run on Windows platforms. It would be good to get as many as possible running on all platforms, both to find bugs in the first place, and prevent regressions.
Ran `./test.sh integration` on both an Ubuntu system (wsl) and a Debian system to validate that the integration tests run, and all of the non-skipped tests pass.
Ran `.\test.bat integration` on a Windows system to validate that the integration tests still work correctly.
Fixes #2434
Depends on #2433 (Merged)
Depends on #2437 (Merged)
> (#2434) Integration tests run on non-windows platforms.

- src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
Create the full directory structure of a custom template before
the files are written. 
Tests still need to be added, but I want to get some feedback on if this change is good and how I should add tests first.
This is so empty directories in the template are
replicated in the new package.
1. Installed zip.template into debug build install location
2. Added two empty directories to root of zip template folder (`empty-1` and `empty-2`), and created an empty sub folder (`empty-1\empty-subdir`).  
3. Ran `choco new --template=zip --name=temp-pkg`
4. Validated that the empty directories were created under `temp-pkg`
Fixes #1003
> (#1003) Include empty directories from templates

- src/chocolatey/infrastructure.app/nuget/NugetPush.cs
This checks the error message of a push error more thoroughly and will display the full
error message if it does not match a specific message and the push url
is not the CCR source.
Also, this improves the error message displayed if the package already
does exist and is immutable.
Previously, if there was an error with pushing a package and the error
was a 406 or 409, then it was assumed to be due to an existing
immutable package. However, CCR uses a 409 code for other errors as
well. So if there was an issue with a package, a misleading message
may be shown.
1. Get the package source for a package that you maintain on CCR
2. Get the apikey for your CCR account
3. Edit the package `.nuspec` to a version that exists and is immutable on CCR
4. Pack and try to push the package to CCR and …
> (#2007) Push errors display more information

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
Set the install location to the package folder under lib for nuget
packages that do not have a chocolateyinstall.ps1. This will display
the install location correctly for portable packages that just include
binary(s) that get automatically shimmed.
Fixes: #2241 
This is definitely up for discussion on the implementation
This might be related to #1370.
This has been tested in a debug build, installing a number of packages, with everything working as expected:
- Packages that are "purely" portable, without an install script: `curl`, `balcon`, `sumatrapdf.portable` , `iperf2`. These all reported the install location correctly as being inside the `lib` directory. This is the one changed behavior I found, as expected.
- Packages that extract an archive: `wget`, `curl`. These all reported the …
> (#2241) Set install location to package dir for portable packages

- src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
A new configuration value has been added to the chocolatey.config file, name `defaultTemplateName`.  This allows the user to specify the name of a template which should be used by default when executing the `choco new` command.
While it is currently possible to override the files that are used by default when running `choco new`, this requires the user adding the files into a known location.  By adding this configuration option, it allows the user to run something like:
```
choco install zip.template
choco config set --name=defaultTemplateName --value=zip
```
And then, going forward, anytime that `choco new bob` is run, and new package called `bob` will be created using the zip template.
If the user were to run something like the following:
```
choco new bob --template-name=msi
```
Then …
> (#2377) Add ability to configure default template name

- src/chocolatey.tests.integration/NUnitSetup.cs
Don't hardcode the platform type in the config to windows in the
Nunit Setup.
If the platform type is set to windows, it will try to
run powershell when the tests are run on Linux.
Ran integration and unit tests on both windows and linux.
Part of #2434
> (#2434) Don't hardcode platform in NUnitSetup

- nuget/chocolatey/tools/init.ps1
- src/chocolatey.resources/helpers/functions/Get-CheckSumValid.ps1
- src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUninstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This sets the beforemodify script to only run on windows platforms.
This put a check on the powershell uninstall script, shimgen uninstall,
autoUninstaller and shutdown /a calls during uninstall. They will now
only run on windows.
None of these services work on non-windows, so
they should not be run.
See #2434 for more context
- Build choco and run integration tests on non-windows
- Remove the upgradepackage install
- Run `choco install --version=1.0.0 -s ./context upgradepackage`
- Run `choco uninstall -s ./context upgradepackage`
- Ensure that the beforemodify and uninstall scripts do not try to run, ensure that the shimgen and automatic uninstall services do not try to run.
Fixes #2510
Related to #2434
Based on #2509
> (#2510) Stop Beforemodify scripts from running on non-windows

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This runs configTransformService and capture_package_files on
non-Windows platforms. Both appear to be fully functional, so there is
no reason not to run them. They were added to non-Windows side of the if/else instead of being
moved from the Windows side so as to not screw up the functionality of
create_ignore_files_for_executables.
Also re-enables the integration tests that validate the config transform
service on non-Windows platforms. These can be enabled now that the
config transform service runs on non-Windows platforms.
It would be good to get these two features working on non-Windows, as they both should be working. 
It also lets more integration tests work on non-Windows
1. Build choco on non-windows
2. Run `mono choco.exe install --allow-unofficial msi.template zip.template …
> (#2450) Enable configTransform and FilesSnapshot on non-Windows 

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
This enables more scenarios on non-windows platforms where the only
issues were that the facts relating to validating shimgen or powershell
script behavior did not work. These failures were expected as neither
shimgen or powershell run on non-windows platforms. So the individual 
tests can be skipped, while enabling the rest of the scenario.
This corrects the casing of the "chocolateyInstall.ps1" to now be
"chocolateyinstall.ps1". This allows these tests to work on case 
sensitive filesystems. The associated scenarios are no longer skipped
on non-windows platforms.
More integration tests running on non-windows = better
The changes in this PR (and the dependent PRs) takes the count of skipped tests for non-windows down from ~350 to under 200
Integration tests ran on a Linux system, all …
> (#2434) Enable more integration tests on non-windows

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyNewCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyTemplateCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyExportCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyNewCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyTemplateCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/domain/TemplateCommandType.cs
- src/chocolatey/infrastructure.app/registration/ContainerBinding.cs
- src/chocolatey/infrastructure.app/services/ITemplateService.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
Renames noop to generate_noop in the template service.
Adds `template` command, and associated functions in the template service.
This allows a user to get information about all installed templates, or
a specific template. The list subcommand lists all installed templates.
The info subcommand lists verbose information about a specific template
Usage with -r should output a machine parsable list of the installed
templates. Usage with verbose (implied with the info subcommand) 
outputs more information about the template(s).
The information displayed here can be gathered by running the list
command, config command and inspecting the contents of the
TemplatesLocation. However, this command allows the information to be
displayed in one location.
Both manually installed templates and templates …
> (#449) Add template command

- src/chocolatey/infrastructure.app/services/NugetService.cs
This adds a check for non-Windows systems that warns if the package id
does not end in .template on install. 
This check is added to help
provide guidance to users, as templates are the only package type
currently supported on non-Windows systems.
In the future, this check may be expanded to allow other packages
types, as needed.
1. Build choco on linux
2. Run `mono choco.exe install curl --allow-unofficial` and confirm that the warning appears
3. Run `mono choco.exe install msi.tempalte --allow-unofficial` and confirm that the warning does not appear
Fixes #2481
> (#2481) Warn about unsupported packages on non-Windows

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
This add support for tab completion of the template command.
It has two subcommands, list and info, and one option, --name.
The template command has been added, it should be added to the tab completion as well
- Dotsourced the tab completion into a powershell window
- Validate that tab completion on `choco ` brings up `choco template` after a couple of presses
- Validate that tab completion on `choco t` bring up `choco template` after one presses
- Validate that tab completion `choco template ` brings up `choco template info`, `choco template list`, `choco list --name`, and global options
- Validate that tab completion `choco template list ` brings up `choco template list --name` (and global options)
- Validate that tab completion `choco template info ` brings up `choco template info …
> (#2518) Add tab completion for template command

- src/chocolatey/infrastructure.app/commands/ChocolateyTemplateCommand.cs
This fixes #2546 and adds the correct command to the usage statement.
> (#2546) Fix template help usage statement

- .teamcity/pom.xml
- .teamcity/settings.kts
This commit adds a the build definition to be used by the Chocolatey internal TeamCity servers.
It matches the current build (though using the official.bat), with the addition of optionally loading the official signing keys.
This PR will help us transition to importing and maintaining our builds as code, and ensuring they are maintained along with the code appropriately.
We've tested this on our internal TeamCity servers deployed via Ansible.  
To test it elsewhere, import the repository/branch containing the `.teamcity\*` files into any TeamCity instance:
1.  Go to `Create project` and select `From a repository URL`
1. Fill in a link to the appropriate repository URL, e.g. `https://github.com/jpruskin/choco.git`
1. Import using a branch containing the `.teamcity` files, e.g. …
> (#2542) Adds TeamCity Build Definition

- .build.custom/codeSign.step
- .teamcity/settings.kts
- .uppercut
There was an issue with using `signtool.exe` during the TeamCity build
This PR fixes the UppercuT build to work with signing in our environment by:
- Adding a property to be able to pass in the certificate subject name
- Adding a property to track if the build is running in TeamCity or not
- Adding a third potential path to signtool.exe, in the Windows SDK 7.1 folder
- Adding logic to use a certificate stored in the local machine store if running in TeamCity
It also adds better handling for failure during the build.
> (maint) Fixes TeamCity Signing in UppercuT

- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/infrastructure.app/configuration/ConfigurationOptionsSpec.cs
- src/chocolatey.tests/packages.config
Adds the NUnitTestAdapter nuget package to the chocolatey.tests and chocolatey.tests.integration projects.
The NUnit test adapter extension does not work with VisualStudio 2022
and will not be updated to work it. The recommended alternative is to
use the nuget package instead of the extension. This PR adds the nuget
package to the packages.config for the test projects, so the tests can
be run directly in VisualStudio 2022.
- Open up this PR in Visual Studio 2022
- Attempt to run the choco unit and integration tests from the test explorer
- They should run
Depends on #2530
N/A Tests to cover my changes, have been added
N/A PowerShell v2 compatibility checked.
> (maint) Add NUnitTestAdapter nuget package

- src/chocolatey.tests/infrastructure.app/configuration/ConfigurationOptionsSpec.cs
Since there is a `new` ChocolateyConfiguration before each spec, it
invalidates the action that sets the configuration from the passed in
option because the old config is no longer used. Thus, the options set
should be reset so the help option can be re-added for each spec,
pointing to the new ChocolateyConfiguration object.
Run configuration options tests from the test explorer in VS 2019
Fixes #2529 
* N/A Tests to cover my changes, have been added
> (#2529) Reset configuration options before each test

- .build/nugetBuild.step
A very minor update to the UppercuT steps to use the artifact version as the build number, which allows us to have a far more user-friendly experience when finding linked builds / artifacts in our systems.
Please note that though this shows as `level="Warning"` it doesn't appear in the build logs - but needs to be at that level, otherwise TeamCity won't consume it.
This has been shown to work on the dev and local build server(s), and in the Licensed builds.
> (build) Updates TeamCity BuildNumber

- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
This pull request removes the todo comment about resealing the upgrade
command.
This is removed due to our usage in Chocolatey Licensed Extension
means that we can not reseal the command without breaking
the Licensed Extension, or doing major rework of the Extension
to allow it to happen.
> (maint) Remove todo comment about resealing commands

- nuget/chocolatey/tools/chocolateysetup.psm1
This pull request updates the comment injected to the powershell profile to also include additional details about what the Chocolatey Profile is, and what will happen if the code is not present in the profile.
To give more information to users, so they do not remove the injected import without understanding the implications of doing so.
N/A
Fixes #2443
> (#2443) Update comment about chocolatey profile

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/services/ChocolateyConfigSettingsServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
This pull request updates the config settings service to
store a list of supported features. This is done so we
know which features we should handle without reporting
to the user that the feature is not supported, and will have
no effect when running Chocolatey.
To handle features that we support and don't support, and to notify the user if it isn't supported.
1. Run build.bat to ensure that the build and unit tests has not been broken
2. run `choco feature disable -n checksumFiles` and make sure there is no mention it is unsupported
3. Run `choco feature enable -n checksumFiles` and make sure there is no mention it is unsupported
4. Ensure that the feature `scriptsCheckLastExitCode` is set in the configuration file, with a disabled value
5. Run `choco feature enable -n …
> (#2538) Store a list of supported features

- src/chocolatey/infrastructure/licensing/License.cs
Removed mention of trials not being able to install the extension in the normal way (this is no longer the case), and clarified the error and warning a little more succinctly.
The error message is outdated and gives trial customers the wrong information, as well as linking to docs that now contradict the error message.
1. Build and run/install the `choco` from the repo
2. Add a valid `chocolatey.license.xml` without installing `chocolatey.extension`
3. Run `choco list -lo` (or any other `choco` command)
4. Note the error message and warning emitted when the chocolatey.licensed.dll cannot be found
Fixes #2407
> (#2407) Update licensed assembly not found warning

- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
This PR adds some clarity to the `choco list` command help.
There was confusion around `choco list --local-only` and if it supported `--source` (see issue #2545). This addition to the help line for `--local-only` makes it clearer that searching your local machine won't filter further by source. Given that this is the line after the help output for `--source` it seemed like it didn't need to be clarified there.
Fixes #2545
I worry that it's a little terse, but any further words seemed to add potential confusion. Happy to modify it as folk prefer.
Please note that this won't show up in docs until the docs are regenerated and pushed.
> (#2545) Adds Clarity to List Command Help

- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
This commit updates the note about using a default source
being deprecated and removed in v1 to instead be removed
in v2.0.0.
Additionally, its own section called `DEPRECATION NOTICE`
was added to make it more visible that the functionality
will be going away.
The removal of using the default source has been pushed back to instead be removed in v2, as such the help page should mention this.
N/A (other than running `--help`)
fixes #2634
> (#2634) Update push command default source deprecation

- .teamcity/settings.kts
This definition is joyfully case-sensitive - this way round imports nicely.
> (build) Fix XmlReport Dependency

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPushCommandSpecs.cs
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
This pull request removes the deprecated argument `-t` as a valid argument when pushing packages.
Additionally some maintenance is done for the formatting, and the documentation to use the correct URL's in the documentation help page for push.
The `-t` argument has been deprecated for some time, and instead it was recommended to use `--execution-timeout` instead.
There are no functional differences in these two.
1. Run `choco push --help` to ensure that `-t` is not showing up
Fixes #2627
> (#2627) Remove deprecated `-t` argument for the push command

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPushCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
This pull request removes the deprecated ability to fallback to an older URL for pushing packages to the community repository when no sources is configured, but an API Key is present for the old URL.
Additionally, another commit is added that ensured that the fallback was working previous to this change (added for historic purposes and for testing).
To get rid of deprecated functionality when we can.
1. Run `choco push` with an API key only configured for `https://chocolatey.org/`
2. Make sure there is a message that no api key is configured (this is expected, as we use `https://push.chocolatey.org/`).
3. Run `build.bat` to ensure the new tests work
Fixes #2628
> (#2628) Remove deprecated fallback to old community push URL

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyListCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
This pull request deprecates the argument local only and the arguments only relevant when calling remote sources when the list command is used.
Additionnaly it also adds several deprecation noticed both in the help page, as well as when running the list command to ensure that users are truly notified of the change to make it local only in v2.0.0.
To make the list command only handle local/installed packages, and to notify users to the best of our ability that this change will happen.
1. Run build.bat to ensure that the build and unit tests has not been broken
2. Run `choco list chocolatey` and ensure that there is a warning mentioning the list command will be made local only
3. Run `choco list chocolatey --noop` and ensure the same as step 2.
4. Run `choco list chocolatey --local-only` …
> (#2462) Add deprecation notices for list with remote sources before making it local only

- docs/legal/CREDITS.md
Updated the CREDIS.md file with modern / relevant information that reflects the project today:
* Contributors
* Community Team
* Committers
* 7zip and Shimgen licenses
Note that the Shimgen license _prior_ to this update pointed to a specific commit. Because Shimgen, with the new license hasn't been pulled in yet, I've just pointed to master. This may or may not need to be amended once Shimgen is pulled in.
Finally, I added a whitespace commit as the Markdown linter was shouting at me.
This closes #2614
> (#2614) Update CREDITS.md with relevant contributors, committers and licenses

- NOTICE
In response to [this issue](https://github.com/chocolatey/choco/issues/2549) the CREDITS.md file has been updated with the latest Shimgen license (see #2644) and this PR will reference the updated CREDITS file in the NOTICE file.
Open to changes in the wording.
Closes #2615  #2549
> (#2615/#2549) Reference CREDITS file for other licenses

- COMMITTERS.md
This commit updates the COMMITTERS.md file to use the
correct links to the documentation, as well as updating the
links that are pointing to pages that no longer exist to use
an archived version of the page.
The archive links should be updated to later posts that
are more up to date and still exists without having to rely
on the web archive, however in the interest of time and to
have valid links that users can use I opted to only point
to the web archive now.
This PR updates the COMMITTERS.md file use to valid/correct links to the documentation page which previously was only available on the wiki page.
Additionally this PR also updates the links that pointed to pages that no longer exist to instead point to their web archive equivalent instead.
While the best would be to link these links …
> (docs) Update committers documentation with correct/fixed links

- src/chocolatey/infrastructure.app/configuration/ConfigFileSettings.cs
This pull request updates the deprecation notice mentioned for
obsolete settings values which had initially been slated to
be removed in Chocolatey CLI v1.0.0. However, these are
required by CCM 0.7.0 and needs to be available until we
stop supporting this version.
As such, the deprecation notice is updated to reflect the
status, and the possibility of it being removed in v2.
> (maint) Update deprecation notice for config settings

- nuget/chocolatey/tools/chocolateysetup.psm1
Fixed a couple minor misspellings in the comments we're adding to folks' profiles in the Chocolatey install.
Noticed it in the testing, figured we may as well fix it.
N/A, only code comments edited.
#2443
> (#2443) Fix misspellings for profile text

- src/chocolatey/infrastructure.app/services/PythonService.cs
This throws an exception if the all keyword is used on the python
alternate source for the upgrade command.
On normal nuget sources, the
all keyword will upgrade all installed packages. However, on the python
source, it will try to upgrade a package named "all", which provides a
confusing error message for a user expecting all installed python
packages to be upgraded. This provides an explicit error message
explaining that the all keyword is not supported.
The other alternate sources do not require this, as they do not
implement upgrade at all.
Run `choco upgrade all --source=python` and ensure that it throws the exception
Run `choco upgrade wheel --source=python` and ensure that it does not throw the exception
Fixes #2540
> (#2540) Python source disable all keyword on upgrade

- src/chocolatey/infrastructure/services/XmlService.cs
Close the file reader for the config file so we can copy over top of it.
The file is locked by us for reading when we try to copy over it. This results in an unintuitive error regarding being locked.
1. Opened file and added a `</config>` immediately following the opening `<config>` tag
2. Ran a Chocolatey command
3. Verified that no error was presented.
Fixes #2525
> (#2525) Close config file before we try to put a new copy in it's place

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This corrects the check for if exit code 2 should be used to only
include unpinned packages, like the log output does.
If there are no outdated unpinned packages, but there are are outdated
pinned packages, then an enhanced exit code of 2 will be incorrectly
used, while it should be an exit code of 0. This assumes enhanced exit
codes are enabled.
- Build choco
- Run these setup commands:
```
.\choco.exe feature disable -n showNonElevatedWarnings --allow-unofficial -y
.\choco.exe feature enable -n allowGlobalConfirmation --allow-unofficial -y
.\choco.exe feature enable -n useRememberedArgumentsForUpgrades
.\choco.exe feature enable -n useenhancedexitcodes --allow-unofficial
.\choco.exe install iperf2 --version=2.1.1 --allow-unofficial
.\choco.exe pin add -n iperf2  --allow-unofficial
```
- …
> (#1896) Outdated with ignore-pinned use correct enhanced exit code

- nuget/chocolatey/tools/chocolateysetup.psm1
**NOTE: I did not raise this PR. I'm adding this here, so we can get it moving and merged.**
A check has been added to determine if it is running on Windows PowerShell or PowerShell Core and uses the correct encoding parameter.
In PowerShell Core the `-Encoding` parameter from Windows PowerShell is actually `-AsByteStream`. To allow it to work in PowerShell Core _and_ Windows PowerShell we need to perform a check.
I cannot confirm how this was tested. Neither this PR or the [original PR](https://github.com/chocolatey/choco/pull/2119), mention it.
Fixes #2083
> (#2083) Fix Powershell Core profile edit, minor indentation change

- src/chocolatey.console/Program.cs
- src/chocolatey/infrastructure/licensing/LicenseValidation.cs
When running choco.exe with no Chocolatey Licensed Extension in play the
compatibility warnings were still showing when they shouldn't. Make sure
to initialize the ChocolateyLicense with IsCompatible defaulting to true
until found to be anything else, as well as to only show the warnings
when it is known that a licensed version is being used.
This was missed in the original PR for this issue, but was caught during testing.
1. Get a system that has Chocolatey 0.12.1 installed
1. Run choco list -lo and ensure that it outputs as expected - i.e. no warnings
1. Install the built alpha package from this PR
1. Run choco list -lo and ensure that it outputs as expected - i.e. no warnings
1. Install Chocolatey Licensed Extension v3.2.0 installed
1. Run choco list -lo and see that there is a new …
> (#2660) Check for valid license before checking for compatibility

- nuget/chocolatey/tools/chocolateyInstall.ps1
Ensure that we catch the exception if there is no buffer (PSRemoting, Background Agent, etc) and thus no buffer width.
An example of what happens when trying to upgrade (or reinstall) Chocolatey when run as Background agent: 
Test Kitchen tests were failing on reinstalling the Chocolatey package but only in Test Kitchen runs, not when run manually.
I'm starting with getting a PR up so I can get a build for my local test kitchen, then I will run it through the tests, in particular the ones that have been troublesome. The testing will also mirror #2664 
So my testing (on Windows 7 and Test Kitchen through PSRemoting):
1. Capture package from Team City server (`1.1.0-alpha-20220330-118`)
2. Push this package to internal repository (Test Kitchen needs it here to do it's reinstall)
3. Install …
> (#2659) Handle scenario where install has no buffer

- src/chocolatey/infrastructure/licensing/LicenseValidation.cs
Removes comments that suggest there is a warning provided when a license expires.
Closes #2584
> (#2584) Remove license leeway comments

- tests/Vagrantfile
Updated the Vagrantfile provided for the test environment to use Windows 2019 instead of 2022.
As described in #2690, using 2022 for this test environment is likely to cause test failures.
We can revisit when #2690 has been more fully investigated, but for now this is a known working environment for the purposes of our tests.
Thanks to @corbob for noticing this mistake had snuck in under our noses!
Run the test script under the Vagrant environment and verify all tests pass.
#2690
- N/A PowerShell v2 compatibility checked.
> (#2690) Use Windows 2019 for Vagrant VM

- tests/chocolatey-tests/choco-feature.Tests.ps1
- tests/chocolatey-tests/choco-list.Tests.ps1
- tests/chocolatey-tests/choco-removed.Tests.ps1
- tests/chocolatey-tests/chocolatey.Tests.ps1
There are times we run these tests together we other projects that we provide, as the tests do not consider that that may happen some tests are failing due to changes having been made to the basic installation of Chocolatey before these tests has run.
As such, updating the tests to ignore such scenarios where there are polluted files and/or features being available is needed.
To only test what we want to test, and fix failing tests.
1. Run all changed tests through test kitchen, together with CCM builds
#2728
> (#2728) Update failing tests running together with other projects

- .gitignore
- build.bat
- build.debug.bat
- build.official.bat
- recipe.cake
- tests/Vagrantfile
* Enhance the build process to work without input when not an administrator.
* Enhance build batch files to exit with proper exit code if build fails.
* Update testing vagrantfile to take advantage of the proper exit code and provide build output in a file if the build fails.
* The build process runs `choco unpackself` which by default requires administrator permissions. In this scenario they're not needed, so we can at least get around the prompt by passing `-y`.
* Currently the build exits 0 regardless of the results. Exiting with non-zero when fail allows CI/CD automations to keep using the build.bat file.
* If the build fails for the test environment, it would be helpful to have the output somewhere to reference.
1. From a non-administrator prompt run `./build.bat`
2. Confirm that at …
> (#2743 #2742) Enhance the build and test environment

- GenerateDocs.ps1
- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
- setup.ps1
- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1
- src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1
- src/chocolatey.resources/helpers/functions/Get-PackageParameters.ps1
- src/chocolatey.resources/helpers/functions/Get-UninstallRegistryKey.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyPinnedTaskBarItem.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyShortcut.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyVsixPackage.ps1
This PR expands all of the PowerShell aliases in helper functions and
other PowerShell files included in the repository, excluding the pester
tests in the `tests` folder.
Using full cmdlets is best scripting practice, as it prevents issues if an alias is not available or removed.
Checking that #2556 is fixed was tested by:
- Adding this to my powershell profile: `If (Test-Path Alias:where ) {Remove-Item Alias:where -Force}`
- Opening a new powershell window. 
- Importing the modified `chocolateyProfile.psm1`
- Checking that tab completion works normally.
I used this command to ensure that no aliases where missed: `Get-Childitem -Path . -Exclude "tests" | Invoke-ScriptAnalyzer -IncludeRule 'PSAvoidUsingCmdletAliases' -Recurse`
Fixes #2556
> (#2556) Expand PowerShell aliases

- src/chocolatey/infrastructure.app/services/NugetService.cs
Sets the correct config item instead of setting the Username with
three incorrect values.
The username was being set incorrectly three times.
N/A - Gary is going to YOLO
Fixes #2752
> (#2752) Set correct items when overriding remembered arguments

- src/chocolatey.resources/helpers/functions/Get-ChocolateyUnzip.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyZipPackage.ps1
Adds a switch "disableLogging" to Get-ChocolateyUnzip and
Install-ChocolateyZipPackage. This switch disable 7zip logging of
extracted filenames and does not write out the log of extracted
files. Install-ChocolateyZip passes the switch to Get-ChocolateyUnzip,
and the functionality is implemented into Get-ChocolateyUnzip.
This is useful for large archives with a very large number of files as
logging the extracted files can significantly slow down the extraction
process.
- Imported `chocolateyInstall.psm1` into a `powershell.exe -version 2` window, the module loads fine.
- Ran `.\choco.exe install filespy --verbose --debug` to validate that the files are still correctly logged into the debug output and to the file
- Downloaded the filespy package, edited the `chocolateyInstall.ps1` to add …
> (#1332) Add switch to disable logging for archive extraction

- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/configuration/PackagesConfigFilePackageSetting.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
Added support to timeout and force in packages.config
This is now supported
```
<package id="packagename" timeout="1000" force="true" />
```
Relates to #886.
Other PR's will be required to bring in the other options that can then be controlled via the packages.config file.
> (#886) added support for force and timeout in packages.config file

- src/chocolatey/infrastructure.app/configuration/PackagesConfigFilePackageSetting.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This adds the remaining arguments in the install command's OptionSet and some more arguments in the global OptionSet as elements to the packages.config xml serialization schema. 
This is useful for users wanting arguments that were previously not
available. It is also a pre-requisite for exporting remembered 
arguments, as some of the remembered arguments were not available
in the previous available schema.
Some of the global arguments were not added:
- debug
- verbose 
- trace
- nocolor
- noop
- allowunofficial
- proxy
- proxy-user
- proxy-password
- proxy-bypass-list
- proxy-bypass-on-local
- log-file
All of these appeared to either not be applicable to a single package (e.g. proxy related) or required earlier than the packages.config would get read (like log-file).
Save this as a …
> (#886) Add support for more arguments in packages.config

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyInstallCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyUpgradeCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/configuration/PackagesConfigFilePackageSetting.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This adds a parameter to pin packages after install or upgrade.
It re-uses the code in save_package_information to create the pin file.
See #798
- Installed `wget` with `--pin`, checked that it was pinned with `choco pin list`
- Unpinned and uninstalled
- Install `wget` without `--pin`, checked that it was not pinned with `choco pin list`
- Unpinned and uninstalled
- Upgraded `wget` with `--pin`, checked that it was pinned with `choco pin list`
- Unpinned and uninstalled
- Upgraded `wget` without `--pin`, checked that it was not pinned with `choco pin list`
- Unpinned and uninstalled
Create this `packages.config` file:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
<package id="wget" pinPackage="true" />
</packages>
```
Install via that file and then check that wget is pinned with …
> (#798) Add parameter to install and upgrade commands to pin after install

- src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
- src/chocolatey/infrastructure/tokens/TokenReplacer.cs
This adds the ability for the template command to list the parameters
in templates. If the template is installed via a package, the
parameters get cached in a file called .parameters in the template's
directory. This file is ignored by calls to choco new, as it is
excluded from being copied.
There another method added to TokenReplacer to get the parameters via
regex. This keeps the regex in the TokenReplacer class.
It it useful to be able to list the available parameters in a template. 
The parameters are cached to reduce the number of files that need to be read to get the parameters. Only templates installed via a `.template` package have the parameters cached. This is because those cache files would get deleted as a part of the package upgrade process, so any cache files from those …
> (#2500) List parameters in templates

- .git-blame-ignore-revs
- CONTRIBUTING.md
Adds a `.git-blame-ignore-revs` file for use both with `git blame` and with the Github web UI.
Updates the contributing documentation to show how to set git to use it locally. 
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
This is in preparation for code linting, so the formatting commits can set to be ignored when looking at previous changes.
Compared git blame on a file on the develop branch vs on the pr branch:
https://github.com/TheCakeIsNaOH/choco/blame/254a52cd4ac39a2bcc09ccb429eccb77232118ac/src/chocolatey/AssemblyExtensions.cs
https://github.com/TheCakeIsNaOH/choco/blame/1f34adf2645f11befa4eaae1bbbd0c2c4feb0415/src/chocolatey/AssemblyExtensions.cs
Also ran git blame locally after making git config change. …
> (maint) Add git blame ignore file.

- src/chocolatey/infrastructure.app/templates/ChocolateyInstallTemplate.cs
- src/chocolatey/infrastructure.app/templates/ChocolateyUninstallTemplate.cs
- tests/packages/business-only-license/tools/chocolateyinstall.ps1
- tests/packages/business-only-license/tools/chocolateyuninstall.ps1
- tests/packages/get-chocolateyunzip-licensed/tools/chocolateyinstall.ps1
- tests/packages/hasbeforeinstallblock/1.0.0/tools/chocolateyinstall.ps1
- tests/packages/msi.template/templates/tools/chocolateyinstall.ps1
- tests/packages/msi.template/templates/tools/chocolateyuninstall.ps1
- tests/packages/zip.template/templates/tools/chocolateyinstall.ps1
Removed the trailing semicolon from PowerShell Code.
PowerShell does not need a trailing semicolon on code so it should be removed to be PowerShell like.
N/A
Fixes #2807
> (#2807) Removed trailing semicolon for PowerShell code

- src/chocolatey.resources/helpers/functions/Get-WebHeaders.ps1
Removed the notes section of the function comment based help.
The notes suggested the function was not recommended for use in the package scripts. With changes to the [Package Validator rules](https://blog.chocolatey.org/2022/08/upcoming-changes-validator/) we want to avoid suggesting this cannot be used in lieu of `Invoke-WebRequest`, for example.
N/A
N/A
> (doc) Remove Get-WebHeaders notes

- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
Get and Set ACLs using PowerShell cmdlets instead of .Net calls.
The methods we were using to get and set ACLs were removed sometime after PowerShell 5.1 (I would guess in .Net core), and so installation of Chocolatey did not work under PowerShell Core or newer.
On a Windows 7 PowerShell 2 system, and on a Windows 10 PowerShell 7.2.6 system performed the following steps:
1. Download `https://community.chocolatey.org/install.ps1` to the local system (This is mostly because the Windows 7 system can't access much due to TLS versions).
2. Copy Chocolatey nupkg to system
3. Run `install.ps1 -ChocolateyDownloadUrl <Path to Chocolatey.nupkg>` (Note: I made a slight change to the 7za.exe download for Windows 7 due to TLS)
4. Confirmed that Chocolatey installed and did not encounter the error …
> (#2789) Use PowerShell to get and set ACLs (CU-ENGTASKS-1480)

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUninstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/domain/ChocolateyPackageInformation.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyPackagePathResolver.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageInformationService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/chocolatey-tests/choco-info.Tests.ps1
- tests/chocolatey-tests/choco-install.Tests.ps1
- tests/chocolatey-tests/choco-list.Tests.ps1
- tests/chocolatey-tests/choco-uninstall.Tests.ps1
- tests/chocolatey-tests/choco-upgrade.Tests.ps1
This pull request makes the necessary changes in the codebase to deprecate the ability to do side by side installations, as well as informing the user about side by side installation deprecation as best as we can.
There have been too many problems with side by side installations, and it do not work as was originally intended.
As such removing this functionality is appropriate, and something else will need to be implemented if we plan to support similar scenarios in the future.
1. Run `choco install --help`.
2. Verify the side by side argument is labeled as deprecated.
3. Verify the deprecation notice contains information about side by side being deprecated and will be removed.
4. Run `choco upgrade --help` and do the same checks as step 2 and 3.
5. Run `choco uninstall --help` and do the …
> (#2787) Deprecate side by side installations

- tests/chocolatey-tests/choco-template.Tests.ps1
This commit updates the end to end tests to add regression
testing for the incoming template parameters.
This pull request is a followup from the PR #2507 that implemented the functionality to list parameters in templates.
To have E2E regression tests available.
1. Ran all template command tests in test kitchen
#2500
https://app.clickup.com/t/20540031/ENGTASKS-1480
> (#2500) Add E2E tests for template parameters

- Invoke-Tests.ps1
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/Vagrantfile
- tests/chocolatey-tests/choco-upgrade.Tests.ps1
This adds a parameter to the upgrade_run method, which
is used to pass an action which resets the configuration in the
function that calls upgrade_run.
This fixes a bug when useRememberedArguments is enabled that causes
arguments to be reused in the chocolateyInstall.ps1 when multiple
packages are upgraded. It happens because OptionSet.parse() sets the
configuration via the actions specified in the UpgradeCommand optionSet
setup (and likewise in configuration builder as well). It only sets
options that are saved, so if a later package does not have an option,
it is not set, and the previous option is reused.
This fixes the bug because it resets the configuration at the
ChocolateyPackageService level, which is enough to reset the
configuration for action that runs the PowerShell as well. …
> (#1443) Reset config via action after every package upgrade

- src/chocolatey/infrastructure.app/services/IPowershellService.cs
- src/chocolatey/infrastructure.app/services/PowershellService.cs
This pull request updates the PowershellService class and interface to re-add the original `run_host` method to prevent the need to do a breaking release.
We need to keep the old method contract around until we create a new breaking major release of Chocolatey CLI so it will be backwards compatible with other projects we own, or projects that make use of the Chocolatey.Lib API library.
1. Built Chocolatey Licensed Extension together with this change.
#1185  
https://app.clickup.com/t/20540031/ENGTASKS-1480
> (#1185) Add original powershell host run as deprecated method

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
Add tests for `packages.config` options to ensure they're being set properly.
This PR also adds debug logging so that Pester tests can see these options.
We added the ability to use these options, but didn't have tests to ensure they were working as intended. Case in point one of the Checksum Types was being set as the Checksum.
1. Fetched the branch into Test Kitchen
2. Ran Test Kitchen tests against the build from the build server.
3. Ran the Testing Vagrantfile.
Fixes #886
> (#886) Add tests for packages.config options

- tests/chocolatey-tests/commands/choco-outdated.Tests.ps1
Update the pester tests for the `outdated` command to pin all of the Chocolatey packages to prevent inadvertent test failures when CI/CD builds new versions automatically.
Occasionally CI will build a new version while Test Kitchen is running. This results in a failure as there's an outdated Chocolatey package that wasn't expected.
1. Ran in Team City indicating to pull from `https://github.com/corbob/choco.git` for the repository, `outdated-tests` for the branch, `1.2.0-alpha-20220813-368` for the Chocolatey CLI version (latest on internal repository at this time is: `1.2.0-alpha-20220822-371`), and `OutdatedCommand` for the Tags to test: https://sra-soteria-web.ch0.co/buildConfiguration/TestKitchen_AdHoc/3721?buildTab=tests which resulted in 0 failed tests.
2. Ran in Team City …
> (#2801) Pin Chocolatey packages for outdated tests

- src/chocolatey/infrastructure.app/services/PowershellService.cs
Always pass the hook parameters to `chocolateyScriptRunner` even if we're just passing them `$null`
There is a manual test that we have where we try to install a package thusly: `choco install test-params --package-parameters="/NoDesktop 'Not Displayed' /InstallDir:'C:\tools\package destination'"` this was resulting in the following in the log: `2022-09-26 16:08:41,822 7016 [DEBUG] - Running 'ChocolateyScriptRunner' for test-params v0.0.0 with packageScript 'C:\ProgramData\chocolatey\lib\test-params\tools\chocolateyinstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\test-params', installArguments: '', packageParameters: '/NoDesktop ', preRunHookScripts: 'Not', postRunHookScripts: 'Displayed /InstallDir:C:\tools\package',` which is clearly not correct.
1. I have run this through the …
> (#1185) Always pass in hook scripts event if empty

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure/registration/AssemblyResolution.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
Update the debugging output for the install from packages.config file to clearly delineate the start and end of the configuration output.
Add back the original definition of resolve_or_load_assembly to AssemblyResolution.
The output of the Configuration when Licensed Extension is installed is different from when just Open Source is in play. As such, the tests for the new functionality was failing. This updates the output to enable us to better test the command.
Chocolatey GUI fails to load with the update to `resolve_or_load_assembly`, so added back the original definition.
1. Downloaded build artifacts from build server and installed on VM
2. Installed Chocolatey GUI
3. Launched Chocolatey GUI
4. Confirmed it launched successfully
5. Installed Licensed Extension
6. Ensured the Pester …
> (#886, 2693) Update packages.config install logging and add back resolve or load method for Assembly Resolution

- recipe.cake
- src/chocolatey.console/chocolatey.console.csproj
- src/chocolatey.console/packages.config
- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey.tests.integration/App.config
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey.tests/App.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/registration/SimpleInjectorContainerRegistrator.cs
- src/chocolatey/packages.config
> (#2738) Uplift to .Net 4.8

- README.md
Update the `Troubleshooting` and `FAQ` URLs. The correct locations were taken from the `SUBMITTING-ISSUES.md` file.
Remove confusion - point users to valid pages.
I clicked the changed links.
Doc fix.
N/A
> (doc) Fix broken URLs in README.md

- Invoke-Tests.ps1
Add a test to ensure we don't exceed maximum path lengths in Test Kitchen.
When run with some Test Kitchen configurations, files where the path exceeds about 120 characters from the `tests` directory don't get copied to the Test Environment. This results in failing tests due to missing files.
1. Set the Max length variable in `Invoke-Tests.ps1` to `50`
2. Ran `vagrant up` from the `tests` directory
3. Confirmed that after building the script errored indicating files to shorten.
* Fixes #2910 
* ENGTASKS-2346
> (#2910) Ensure Pester test file paths don't exceed Test Kitchen maximum lengths.

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
The underlying framework NuGet.Client has changed how it
resolves dependencies. Because of this we no longer have
information about the dependencies that will be installed
until everything has completed its run successfully.
As such, if a failure happens during the dependency handling
we only show the amount of total packages that was passed
into the executable, instead of the old handling that also included
the dependencies.
For successful runs, even the dependencies will be listed as
the amount of total packages.
To get a working build for Chocolatey CLI.
1. Run `.\build.ps1 --testExecutionType=all --shouldRunOpenCover=false`
Related to #508
> (#508) Fix unit tests for new dependency handling

- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- When restoring configuration backups, do not overwrite/change the value of the PromptForConfirmation configuration option.
The configuration that choosing "yes to all" modifies for the run should be remembered, even if we need to take/restore config backups, so that the option works as intended.
1. Ensure the allowGlobalConfirmation feature is disabled
1. Run choco with arguments `install curl wget -f`
2. When prompted to run the scripts for `curl`, select "[A] Yes to all"
3. No further prompts should appear and both installations should complete
- Windows 11
Fixes #2872
> (#2872) Fix selecting All for interactive prompts

- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/packagewithscript.nuspec
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/tools/chocolateyBeforeModify.ps1
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/tools/chocolateyinstall.ps1
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/tools/chocolateyuninstall.ps1
- tests/helpers/common/Chocolatey/Invoke-Choco.ps1
- Add test package and test for functionality of `[A] Yes to all` prompt actions
- Add test for functionality of `choco upgrade` when given multiple packages to upgrade at once.
Keepin' up with the tests.
1. Run vagrant image tests for `choco install` and `choco upgrade` command
2. New tests should pass on build from `hotfix/1.2.1` but fail under choco `1.2.0`.
N/A
Tests for #2872
> (#2872, #2884) Add automated regression tests for v1.2.1

- src/chocolatey/infrastructure/registration/AssemblyResolution.cs
- Fix case in assembly resolver for when it's blindly loading the licensed extension due to finding a valid license.
Previously, the change to the assembly resolver had one edge case; if there is a chocolatey.license.xml that is found, choco will attempt to load the licensed extension specifically. It does not check before that whether the extension is installed or the file is anywhere it should be expected to be, all that is offloaded to the resolver.
This change ensures that if we're looking for that extension due to loading a valid license, we cannot return the base Chocolatey assembly which would be completely incorrect and confuse a lot of choco's built in license assertions and assembly version logic for that extension.
1. Install a valid and current `chocolatey.license.xml`, but DO …
> (#2865) Don't resolve chocolatey for licensed ext

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/packages.config
This pull request updates all of the NuGet.Client libraries
that we need for Chocolatey CLI to the latest version
we have available on nuget.org. As part of this update, the package
name and assembly name was changed for the packages as well.
To be kept up to date, and to allow people outside of the team to be able to build the project.
1. Ran unit and integration tests through `build.ps1`
- Windows 11/10
N/A
> (maint) Update NuGet Libraries to latest version

- recipe.cake
- src/chocolatey.sln
Now that we are building specifically for .NET 4.8, we should add the
generated chocolatey.dll file to the correct TFM folder within the
NuGet package, so that it is correctly located, and extracted when
consuming the NuGet package.
The Credits.txt file has been left at the root level of the lib folder,
rather than replicating into each TFM folder.
This makes it clear what framework the assembly is targetting.
Ran build.bat locally, and then verified that the net48 folder existed in the generated nupkg file. This was done using NuGet Package Explorer.
Relates to #2738
> (#2738) Add net48 TFM folder in NuGet package 

- src/chocolatey.console/Program.cs
This adds a registry check to `chocolatey.console` to validate that .Net 4.8 or later is installed. This check is added because Chocolatey CLI can start to execute but runs into errors when the system has an older version of .Net framework installed. The check is very early on in the execution so as to print out a helpful error before any errors due to incompatibilities with the older .Net version show up.
It is better to have a check and helpful message than various unhelpful error messages.
1. Build PR 
1. On Server 2012 R2 (with the default .Net 4.5.2 installed), upgrade from Chocolatey CLI v1.2.1 via the nupkg built in step 1
1. Validate that `choco` commands cause an error (which happens too early in execution for a check to be added)
1. Update .Net to 4.6.0 and reboot
1. Validate …
> (#2738) Check installed .NET version installed is at least 4.8

- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/scenarios/InfoScenarios.cs
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey.tests/TinySpec.cs
This pull request intends to add future tests that can be used when we have a chance to look at reimplementing/implementing support for source priority support.
It includes a couple of tests that are related to sources, but are currently broken in vNext of Chocolatey CLI.
THe first commit in this PR is intended to be cherry-picked into our support/1.x branch.
To have future covering tests.
1. Ran the unit tests.
2. As the feature is not working, it can not be tested completely.
- Windows 11
- Windows 10
#1541  
https://app.clickup.com/t/20540031/PROJ-313  
https://app.clickup.com/t/20540031/PROJ-407
> (#1541) Add tests for future implementation of source priority

- src/chocolatey.tests/MockLogger.cs
- src/chocolatey.tests/TinySpec.cs
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/nuget/ChocolateyNuGetProjectContextSpecs.cs
- src/chocolatey.tests/infrastructure.app/nuget/ChocolateyNugetLoggerSpecs.cs
- src/chocolatey.tests/packages.config
- src/chocolatey/infrastructure.app/nuget/ChocolateyNuGetProjectContext.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyNugetLogger.cs
This pull request updates the custom nuget logger we are using to not log normal informational output to the console unless `--verbose` is being used.
Additionally, this pull request updates the nuget logger, and the custom project context logging functionality to get rid of duplicated code.
We do not want to obscure normal output for the user by including the information from NuGet.
While these can be helpful in some cases, hiding it behind a verbose flag by default make sense.
1. Run `choco search 7zip.install`
2. Verify no output from NuGet is being shown
3. Run `choco search 7zip.install --verbose` (verbose in this case is synanymous with `--detailed`).
4. Verify the output from NuGet is shown with green text.
5. Run `choco info firefox`
6. Verify no output from NuGet is being shown …
> (#508) Change NuGet normal logging to be verbose logging

- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
If a source is a http/https source, this sets nuget http cache directory to a folder inside the Chocolatey cache location. 
This prevents conflicts with the NuGet http cache. If this is not set, then cached http results will be located alongside results from NuGet.
- Open `%temp%\Chocolatey` (aka Chocolatey cache location) and remove `NuGetHttpCache` if it exists
- Run `.\choco search chocolatey --source=https://api.nuget.org/v3/index.json`
- Validate that the `NuGetHttpCache` folder appears and that it contains a subfolder with cached results from the search.
- Run `.\choco install curl` 
- Validate that the `NuGetHttpCache` folder has a subfolder with cached results for `curl`
- Open `%localappdata%\NuGet\v3-cache` and remove contents
- Rerun above `choco` commands and validate that …
> (#508) Set NuGet http cache directory

- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This fixes `--page` and `--page-size`. These arguments are inefficient because they require querying for all packages, and throw away everything but the page requested.
When the list command was switched to use NuGet.Client libraries, support for `--page` and `--page-size` was removed 
- Run `.\choco.exe search google --source=https://community.chocolatey.org/api/v2`, validate that about 248 packages are returned
- Run `.\choco.exe search google --source=https://community.chocolatey.org/api/v2 --page=0`, validate that 25 packages are returned
- Run `.\choco.exe search google --source=https://community.chocolatey.org/api/v2 --page=2`, validate that 25 packages are returned and that they are the different from `--page=0`
- Run  `.\choco.exe search google …
> (#508) Fix --page and --page-size arguments

- src/chocolatey.tests.integration/context/uppercase/1.0.0/UpperCase.nuspec
- src/chocolatey.tests.integration/context/uppercase/1.0.0/tools/chocolateyBeforeModify.ps1
- src/chocolatey.tests.integration/context/uppercase/1.0.0/tools/chocolateyinstall.ps1
- src/chocolatey.tests.integration/context/uppercase/1.0.0/tools/chocolateyuninstall.ps1
- src/chocolatey.tests.integration/context/uppercase/1.1.0/UpperCase.nuspec
- src/chocolatey.tests.integration/context/uppercase/1.1.0/tools/chocolateyBeforeModify.ps1
- src/chocolatey.tests.integration/context/uppercase/1.1.0/tools/chocolateyinstall.ps1
- src/chocolatey.tests.integration/context/uppercase/1.1.0/tools/chocolateyuninstall.ps1
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure/results/PackageResult.cs
The NuGet.Client libraries will install nuspec files with a lowercase filename, even if the package ID contains uppercase character(s) and the nuspec in the nupkg is also uppercase. This behavior means that on non-Windows platforms, the nuspec is not able to be found, because it has incorrect casing in the filename.
This corrects that behavior on non-Windows platforms by renaming the nuspec to the correct cased filename. On Windows, there is no need to adjust the casing, because the filesystem is case-insensitive.
The `to_lower()` calls when setting the PackageResult.Name are removed, so the output of the name of the package will match the actual casing of the name.
Also, integration tests are added to ensure that packages that have IDs
with uppercase character(s) can be installed, …
> (#508) Fix nuspec casing on non-Windows

- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
This moves the setup module used during install and upgrade to
check for and install .Net 4.8 instead of .Net 4.0
The timing of the check/install is moved to before the Chocolatey
installation directory is created. This allows for re-running the
install.ps1 script if a reboot is required without needing a manual
cleanup of the partial installation.
This also adds a check for the other reboot required exit code of
1641, and throws the install/upgrade if the installer requires
a reboot.
As Chocolatey CLI is being moved to .Net 4.8, it requires insuring that the required framework is installed.
Testing on Server 2012 R2:
- Upgraded from Chocolatey CLI 1.2.1 to a built nupkg from this PR. It installed .net 4.8 and threw as a reboot was required. After a reboot, a second attempt at an upgrade …
> (#2738) Move setup module to install .Net 4.8

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/TemplateServiceSpecs.cs
- src/chocolatey/EnumerableExtensions.cs
- src/chocolatey/LogExtensions.cs
- src/chocolatey/infrastructure.app/configuration/ConfigurationOptions.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyNuGetSettings.cs
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/services/IPendingRebootService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
- src/chocolatey/infrastructure/adapters/IEnvironment.cs
- src/chocolatey/infrastructure/adapters/IProcess.cs
- src/chocolatey/infrastructure/registration/AssemblyResolution.cs
- src/chocolatey/infrastructure/registration/SimpleInjectorContainer.cs
- src/chocolatey/infrastructure/results/IResult.cs
This fixes the xml comments that had warnings, and resolves a number of other warnings in Visual Studio
Reducing the number of warnings in Visual Studio and during the command line build is ideal, as it allows for easier identification of any new warnings that show up, and starts on the path to allow enabling treat warnings as errors.
Look at warnings in Visual Studio, and saw the number greatly reduced. 
Built and ensured that there were no compilation issues.
Depends on #2927
Helps prepare for #13
> (maint) Resolve a number of warnings

- src/chocolatey.tests.integration/scenarios/InfoScenarios.cs
- src/chocolatey.tests/infrastructure.app/nuget/NugetCommonSpecs.cs
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/nuget/NugetPush.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
When setting up NuGet sources, if NuGet is unable to parse the path, this tries to resolve relative paths to absolute, and then retries setting up the NuGet source. If the path is unable to be resolved, then this ignores the error and lets NuGet handle the resulting invalid source.
This path resolution requires the filesystem to be passed in. This means that various method signatures change to allow access to the filesystem.
When using NuGet.Core, then relative paths were able to be resolved. But now with NuGet.Client, relative paths are resolved by clients, not by libraries, which is why this change has to be made. https://github.com/NuGet/NuGet.Client/pull/3783
- Add wget `.nupkg` to `C:\packages`
- Open PowerShell at `C:\`
- Run `choco.exe` from this PR with `.\choco.exe info wget …
> (#508) Attempt to resolve relative paths for sources

- src/chocolatey.tests.integration/NUnitSetup.cs
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/icon.png
- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/readme.md
- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/tools/chocolateyBeforeModify.ps1
- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/tools/chocolateyinstall.ps1
- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/tools/chocolateyuninstall.ps1
- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/unsupportedelements.nuspec
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/icon.png
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/readme.md
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/tools/chocolateyBeforeModify.ps1
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/tools/chocolateyinstall.ps1
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/tools/chocolateyuninstall.ps1
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/unsupportedelements.nuspec
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/PackScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This adds a check for the new metadata elements added in NuGet.Client, which throws pack if any are found, and warns during install and upgrade.
Specifically, this checks for the `serviceable`, `frameworkReferences`, `readme`, `icon`, `repository`, `license`, and `packageTypes` nuspec elements. These elements were found by comparing `nuspec.xsd` files in the nuget-chocolatey and NuGet.Client repository.
https://github.com/chocolatey/nuget-chocolatey/blob/1162255ce5e02fc6a5ca486639e088f2cff909ee/src/Core/Authoring/nuspec.xsd
https://github.com/chocolatey/NuGet.Client/blob/6ab0442268394c0f12c4f0b42688ac55dec42337/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd
Also, an additional config value is added to disable the check during pack so the
setup for tests packages with …
> (#508) Add check for unsupported metadata elements.

- src/chocolatey/infrastructure.app/services/NugetService.cs
- Small grammar fix for wording of the nuspec errors/warnings for elements that are not currently supported.
The wording/grammar was inconsistent.
1. Attempt to `choco pack` or `choco install` a package containing some of the nuspec elements we check for as unsupported.
2. Verify the wording is given as expected, and recommendations for alternatives state `use X instead` and not `used X instead`.
Win11
#508
> (#508) Fix spelling/grammar in nuspec errors/warnings for unsupported elements

- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/helpers/common/Set-RegistryKeyOwner.ps1
Chocolatey CLI should not execute when the .Net version is below 4.8 as set in the Registry. This adds an end to end pester test that takes ownership of the key and removes the value to verify that Chocolatey behaves as expected.
We need to ensure that Chocolatey doesn't run when .Net 4.8 isn't detected as being installed.
* Used the updated vagrant file from my `test-with-net-48` branch (this updates the tests Vagrantfile to include .net 4.8), ran tests through there.
* Ran tests through Test Kitchen against latest develop build and targeting this branch. 
Test Kitchen or Vagrant: Windows Server 2016, 2019, 2022
* Related to #2738 
* CU-PROJ-442
> (#2738) Add tests for .Net registry checks

- src/chocolatey/infrastructure.app/services/NugetService.cs
The PackageResult install location should only be set by the list method if searching/listing the installed packages.
This fixes an issue where all packages on local/folder feeds show as installed when using ChocolateyGUI
- Build chocolatey.lib package from PR
- Bring into ChocolateyGUI
- Add a local folder source (e.g. `C:\packages`) that has some `.nupkg`s
- Open ChocolateyGUI and install a package that exists in that local source.
- Validate that only package(s) which are installed show up as installed when viewing the local source in ChocolateyGUI
Part of #508
> (#508) Only set package install location when local only list

- src/chocolatey.resources/helpers/chocolateyInstaller.psm1
- src/chocolatey/FileSystemExtensions.cs
- src/chocolatey/infrastructure/licensing/License.cs
- Prevent loading the chocolatey.licensed.dll for the present, and emit a warning when it is found to alert users that licensed functionality is currently not available.
Since we have a known incompatibility with the existing licensed extension dll that makes it completely unusable, we should prevent loading it for the present.
This commit should be removed once we have updated the licensed extension, prior to stable release.
1. Build and run choco with the licensed extension in play
2. A single warning should be emitted, indicating that the licensed extension will currently not work
3. Licensed functionality (e.g. the `download` command) should not be available
N/A
#2738
> (#2738) Temporarily prevent loading chocolatey.licensed.dll

- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
This ensures that it always the Chocolatey specified proxy used, and it does not attempt to get a proxy from the NuGet settings file.
See description.
See https://github.com/chocolatey/NuGet.Client/pull/18
- Replace `NuGet.Configuration.Settings.GetSection()` with a `throw new NotImplementedException();` 
- Build NuGet and Chocolatey (with the NuGet build)
- Run `choco search wget`
- Run `choco install wget`
- Run `choco uninstall wget`
- Validate that choco does not trigger that exception for any of these.
- Windows 
Part of #508 
https://app.clickup.com/t/20540031/PROJ-444
> (#508) Always override proxy

- tests/Vagrantfile
Update Vagrantfile to install .Net framework 4.8
Develop branch now requires .Net framework 4.8 in order to build and run.
1. From the `tests` directory run `vagrant up`
2. Note that the project builds and tests complete as expected
**Note:** #2690 means that some tests are expected to fail here. For reasons I have not yet determined, Windows Server 2019 fails to build, but Windows Server 2022 doesn't.
I'm running macOS Ventura with Vagrant 2.3.3 and VirtualBox 7.0.
Related to: #2738
> (#2738) Upgrade To .Net Framework 4.8 for testing

- tests/chocolatey-tests/commands/choco-apikey.Tests.ps1
- tests/chocolatey-tests/commands/choco-config.Tests.ps1
- tests/chocolatey-tests/commands/choco-export.Tests.ps1
- tests/chocolatey-tests/commands/choco-feature.Tests.ps1
- tests/chocolatey-tests/commands/choco-help.Tests.ps1
- tests/chocolatey-tests/commands/choco-info.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
- tests/chocolatey-tests/commands/choco-new.Tests.ps1
- tests/chocolatey-tests/commands/choco-outdated.Tests.ps1
- tests/chocolatey-tests/commands/choco-pack.Tests.ps1
- tests/chocolatey-tests/commands/choco-pin.Tests.ps1
- tests/chocolatey-tests/commands/choco-push.Tests.ps1
- tests/chocolatey-tests/commands/choco-source.Tests.ps1
- tests/chocolatey-tests/commands/choco-template.Tests.ps1
- tests/chocolatey-tests/commands/choco-uninstall.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- tests/chocolatey-tests/commands/choco-version.Tests.ps1
- tests/helpers/common/NuGet/Get-NuGetPaths.ps1
- tests/helpers/common/NuGet/Remove-NuGetPaths.ps1
- tests/helpers/common/NuGet/Test-NuGetPaths.ps1
Add end to end tests to ensure that NuGet directories aren't being created by Chocolatey CLI.
Our code shouldn't touch anywhere that creates these directories. This ensures we don't accidentally introduce anything.
1. Ran tests in the Vagrant environment
2. All added tests completed successfully.
- Windows Server 2022 (Vagrant file from #2971)
- Windows Server 2019 (Test Kitchen)
- Windows Server 2016 (Test Kitchen)
* Related to #2738 
* CU-PROJ-443
* https://github.com/chocolatey/NuGet.Client/pull/17
> (#2738) Add tests to ensure NuGet configuration directories aren't created

- src/chocolatey/infrastructure.app/services/NugetService.cs
This enables the download progress message output from NuGet. 
See chocolatey/NuGet.Client#12
If any other downloads of `.nupkg` files are added, then a similar line should be added before the download to enable the download progress
- Build nuget libraries
- Set Chocolatey to use them
- Run `.\choco install wget --force`
- Run `.\choco install wget --force --no-progress`
- Run `.\choco install WGETWindows --force --source=https://api.nuget.org/v3/index.json`
- Run  `.\choco install WGETWindows --force --source=https://api.nuget.org/v3/index.json --no-progress`
- Validate that download is progress is shown or not shown as appropriate.
Part of #508 
Enablement of chocolatey/NuGet.Client#12
https://app.clickup.com/t/20540031/PROJ-430
> (#508) Enable download progress in NuGet

- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-pack.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- Adds some end to end tests for how choco behaves when handling a package with unsupported metadata elements in the nuspec.
We should have some tests confirming the end-user behaviour of package installs and packs when choco finds unsupported elements in the nuspec metadata.
1. Locally tested with Invoke-Tests.ps1
2. Tests will be run in TeamCity
The added tests should pass with no issues.
Win11
#508
> (#508) Add Pester tests for unsupported metadata

- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/scenarios/InfoScenarios.cs
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/PackScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This adds pack tests to ensure that leading zeros are removed, and that a zero in the fourth part of the version will be trimmed down to three parts. 
More scenarios are added to ensure that pre-existing packages with non-normalized versions can be installed/upgrade/uninstalled, and that they can be found when searching with a version.
As a part of supporting SemVer v2, some version normalization was added.
https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#normalized-version-numbers
The pack tests are to ensure that the version normalization on pack with the new NuGet assemblies is consistent into the future. There were already pack tests for removing semver v2 build metadata and that four part versions still work. 
The other tests make sure that pre-existing …
> (#1174)(#1610) Add tests for package versions with leading zeros

- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/chocolatey-tests/commands/choco-pack.Tests.ps1
This pull request updates the validation that is done when
creating packages to fail the pack when the user has
specified that the package requires license acceptance,
but the license url has not been set.
We want to keep the validation error message we had in v1.2.1 when the package requires license acceptance, but there is no license URL specified.
1. Ran through test kitchen locally for the PackCommand
2. Packaged the nuspec file in the repository called `invalid-requirelicenseacceptance.nuspec` and checked the error message
- Windows 11/10
#508  
https://app.clickup.com/t/20540031/PROJ-462
> (#508) Re-introduce license acceptance rule validation

- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/nuget/NugetPush.cs
This moves the NuGet user agent setting from only the Push command to
`NugetCommon.GetRemoteRepositories` so it is set for all commands that use remote sources.
User agent should be set to indicate that the client is Chocolatey for all commands.
- Ran `choco install wget --trace` and ensured that the user agent was set for all calls (see line starting with `user-agent:` in trace output)
- Ran `choco push --trace` with a package to an internal repository and ensure that the user agent was set
Part of #508
> (#508) Set NuGet user agent for all commands.

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/packages.config
Switch away from using local package metadata (which isn't always available, for example when running the choco info command).
Rather than relying on the metadata retrieved from the local package on disk (which isn't always available), use the newly added server side metadata to display the required information. For example, release notes, package URL's, etc.
This additional information was added into the NuGet.Client assemblies here:
https://github.com/chocolatey/NuGet.Client/pull/22
This needs to be tested in conjunction with the PR here: 
https://github.com/chocolatey/NuGet.Client/pull/22
And the steps in that test used to valid the changes here.
Windows 10 22H2
- Relates to #508 
- https://app.clickup.com/t/20540031/PROJ-459
> (#508) Use Chocolatey specific server metadata

- tests/chocolatey-tests/commands/choco-push.Tests.ps1
- tests/helpers/common/Chocolatey/New-ChocolateyTestPackage.ps1
- tests/helpers/common/NuGet/Test-NuGetPaths.ps1
Add tests for pushing to NuGet v2/v3 feeds
With the addition of v3 feed support, need to ensure we can push to them. This also adds tests  for v2 feeds.
In order for these tests to work, you must (currently) specify environment variables `$env:NUGET_API_KEY` and `$env:NUGET_PUSH_REPO`
1. Ran locally against a Test Kitchen instance
2. Ran through Team City setting the aforementioned environment variables.
Windows Server 2016, 2019
* #2738 
* PROJ-377
* https://gitlab.com/chocolatey/build-automation/chocolatey-test-kitchen/-/merge_requests/136
> (#2738) Add tests for NuGet v2 and v3 feeds

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
Completes and enables the pin command specs that were marked as pending.
Now that the NuGet uplift #508 has been completed, it is easier to complete the tests
Unit tests pass in Visual Studio and with `build.ps1`
Fixes #2501
> (#2501) Complete pending Pin command tests

- src/chocolatey.tests.integration/scenarios/PackScenarios.cs
- src/chocolatey.tests/infrastructure.app/services/NugetServiceSpecs.cs
- src/chocolatey.tests/infrastructure/guards/EnsureSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/registration/ChocolateyRegistrationModule.cs
- src/chocolatey/infrastructure.app/rules/EmptyOrInvalidUrlMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/FrameWorkReferencesMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/IconMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/LicenseMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/MetadataRuleBase.cs
- src/chocolatey/infrastructure.app/rules/PackageTypesMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/ReadmeMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RepositoryMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RequireLicenseAcceptanceMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RequiredMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/ServicableMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/VersionMetadataRule.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/RuleService.cs
- src/chocolatey/infrastructure/guards/Ensure.cs
- src/chocolatey/infrastructure/rules/IMetadataRule.cs
- src/chocolatey/infrastructure/rules/RuleResult.cs
- src/chocolatey/infrastructure/rules/RuleType.cs
- src/chocolatey/infrastructure/services/IRuleService.cs
- tests/chocolatey-tests/commands/choco-pack.Tests.ps1
This pull request extracts the existing validation messages we had into a new rule service to make it easier to add new rules or changing existing rules, as well as it re-adds back the validation rules that was present in v1 but had been removed by the NuGet Client Uplift.
The outputted validation messages has also been changed to make more sense to the user for the messages that we had readded.
To keep the same or similar validations happen when a user creates a new package.
1. This has been ran through test kitchen locally
- Windows 10 / 11
Fixes #3000  
https://app.clickup.com/t/20540031/PROJ-461
> (#3000) Create new rule service and read old validation messages

- src/chocolatey.console/Program.cs
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests/TinySpec.cs
- src/chocolatey.tests/UNCHelper.cs
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/services/ChocolateyPackageServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
This pull request removes the support that was previously available to install a package by passing in its nupkg or nuspec file directly on the Commandline when calling `choco install` or `choco upgrade`.
Instead it will now fail the installation before it even tries to read the file by throwing an exception about it not being supported, as well as giving an example to the user how the package can be installed.
This example is only available when we reliably can determine that it is a absolute local file path, a UNC path or a relative file path where the file exists.
Otherwise a generic error output about passing in a nupkg file is shown.
If a nuspec file is shown, a different error is displayed mentioning that the file need to be packaged before attempting the installation.
There has …
> (#3008) Remove support for passing in nupkg file when installing or upgrading packages

- tests/chocolatey-tests/chocolatey.Tests.ps1
Enable `local` source when running tests that install chocolatey.
When Test Kitchen is run with a local build, or a PR build, it is installed from a local source, and not from a nuget repository. This ensures that we enable the source for tests that require it.
Team City Test Kitchen Before
Team City Test Kitchen After
1. Build Chocolatey locally
2. Run Test Kitchen build with the locally built package
3. Build Chocolatey PR in Team City
4. Run Test Kitchen in Team City targeting the PR build
* Windows 2016 (test kitchen tests)
* Windows 2019 (test kitchen tests)
* Windows 2022 (vagrant tests)
N/A: This was identified when running some test kitchen tests
> (tests) Enable local source for tests that need to install chocolatey

- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
The main purpose of this pull request is to output warnings when a threshold of the amount of packages from at least 1 source has been hit, or if the threshold is very close to be hit and no page has been specified.
This will allow the user to decide to either refine their search, or to make use of the paging mechanism already built into Chocolatey CLI.
Additionally, there was a need to update the logic we use when querying sources to have a maximum amount of packages that can be returned per query.
If this maximum amount was not introduced there are sources that will return the wrong amount of packages.
To give more information to users on their next step, and to do what we can to minimize impact on different servers used as sources.
1. Run `choco search --source chocolatey` (this may …
> (#508) Warn users when a threshold has been hit, or when the threshold is close

- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
When forcing dependency reinstallations, don't mark local non-dependency packages as requiring uninstall/reinstall.
When doing `choco install hasdependencies --force --forcedependencies` Chocolatey would mark all local packages for uninstallation and reinstallation. It would then remove the local packages, but fail to reinstall any that weren't dependencies.
1. Ran in test kitchen against current develop branch (only InstallCommand) - Confirmed failed the updated tests
2. Ran in test kitchen against changes (only InstallCommand) - Confirmed no longer failed the updated tests
3. Ran Integration Tests after the first commit  - Confirmed new tests failed
5. Ran Integration Tests after the second commit - Confirmed new tests no longer fail
* Windows 10 (Manual testing with debug …
> (#508) Fix force dependencies to not remove existing non-dependency packages

- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-push.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
Update the end to end Pester tests:
* Update the upgrade and install test message when provided with a nupkg
* Update nuget v2/3 push tests to more consistently detect if the package pushed successfully
* The error message when provided with a nupkg file is not consistent with the pester tests
* Sometimes the push tests are failing, but the push itself is not failing. This seems to be a timing issue with the feeds.
1. Will run them in Team City when a team city agent is available
Server 2016/2019 (Team City Test Kitchen environments)
No issue, this is related to tests we're seeing having issues while working on other things.
> (tests) Update some tests to be more consistent

- src/chocolatey.console/choco.exe.manifest
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/helpers/common/Chocolatey/New-ChocolateyInstallSnapshot.ps1
Update Chocolatey to handle long paths, add tests for http cache being long path.
Should be able to operate with long paths since Windows has had the ability for some time.
Manually verified that the long paths worked.
https://app.clickup.com/t/20540031/PROJ-496
> (#508) Fix exception happening when http cache location is too long

- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
This pull request fixes the tests that had been included in the PR #3017 with the correct paths and the correct output that is expected for both open source and licensed extension.
To have working tests.
1. Run through test kitchen using the Tag `LongPaths`
- #508
- https://app.clickup.com/t/20540031/PROJ-496
> (#508) Correct installation E2E tests for long and cache paths

- src/chocolatey/infrastructure.app/services/NugetService.cs
There are times when the dependency resolution, and the attempt to find
a valid solution for package installation is too aggressive.  For
example, if you install a package and omit the installation of the
dependencies, then any follow up attempt to install a package will
fail, since it is checking for all dependencies to be met for all
installed packages.  This is not always valid, since it should only
worry about the package that is being installed/upgraded.
This commit adds a check to see if the package being installed has any
dependencies, and if it doesn't, don't check for dependencies for the
locally installed packages.  On top of this, check to also see if the
package being installed is an existing dependency on an existing
installed package.  If this is the case, then go through …
> (#508) Fix dependency resolution

- src/chocolatey/infrastructure.app/services/CygwinService.cs
- Wrap _rootDirectory field in CygwinService in a property that null/empty-checks and sets the field if needed.
- Remove the manual call to update the root directory in the ensure_source_app_installed.
- Update references throughout CygwinService to use the property instead of accessing the field directly.
- Move most of the logic in `set_root_dir_if_not_set()` to a new `get_root_directory()` private method
- Flag extraneous / non-ISourceRunner interface methods as [Obsolete]
Currently, `ISourceRunner` instances seem to be managed as transient. This is reasonable for many things, but it means we cannot rely on storing state in instance fields for `ISourceRunner` instances at the current time.
This change ensures that the state data created by `ensure_source_app_installed()` can be kept …
> (#2953, #3026) Ensure CygwinService can find the correct RootDirectory

- gitreleasemanager.yaml
- Added the Deprecate label to GRM configuration.
- Added config to set headers in the release notes specifically for Deprecate and Bug so that their headers match our release notes format.
**NOTE:** We should cherry-pick this commit into support/1.x branch after it's merged as well.
We're deprecating quite a few things, we should probably use a proper label for it.
Also, the auto-gen'd release notes don't quite match our release notes format, so updated the config to make that work as expected.
Ran `./build.ps1 -Target releasenotes` from the support/1.x branch with this configuration change and verified the generated release notes match up to what we want.
N/A
N/A, build adjustment only
> (maint) Update Gitreleasemanager configuration

- tests/helpers/common/Chocolatey/Invoke-Choco.ps1
Enhance the `Invoke-Choco` function to look for custom environment variables and append the proxy parameters if they're found.
We're adding some Test Kitchen instances that set custom environment variables so that we can test the proxy parameters.
1. Ran Test Kitchen locally with configuration to set these environment variables.
2. Watched the proxy logs to see it was hitting the proxy as expected.
* Windows Server 2019
* Windows Server 2016
* PROJ-374
* PROJ-478
* PROJ-479
> (tests) Enhance Invoke-Choco to force proxy use

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/packages.config
This commit switches to using the new Version property in the NuGet.Client assemblies.
NOTE: In order for this change to work, an uplift to the NuGet.Client assemblies will be required. A PR is open to provide this functionality, and therefore hasn't been brought in yet.
When searching for a specific version in Chocolatey 1.x, the orderby of the search was changed to be "Id,Version desc", and we want to use the same orderdy when using the new NuGet.Client assemblies.
1. Testing steps are detailed in this PR - https://github.com/chocolatey/NuGet.Client/pull/28
- Windows 10
- Relates to #508
- https://app.clickup.com/t/20540031/PROJ-511
> (#508) Add version to search order by

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
- src/chocolatey/packages.config
This commit changes the find_package method to make use of a new
PackageAsync method which has been added to the ListResource within the
NuGet.Clint assemblies, which provides this optimization.
In addition, this commit makes a slight refactoring to the code where
find_package is called, and removes unnecessary calls to the
GetAllVersionsAsync method.  This work is exactly the same as the work
done in the GetMetaDataAsync method of the find_package method, and
therefore not required.
In order for the new Chocolatey CLI to function in the same way as the
previous 1.x versions, we need to take into account the
UsePackageRepositoryOptimizations feature.  WHen this is enabled, as
few queries as necessary should be used.  For example, when querying
for an exact package id, or checking to see …
> (#508) Add Repository optimizations back into Chocolatey execution

- src/chocolatey/RuleResultExtensions.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/rules/EmptyOrInvalidUrlMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/FrameWorkReferencesMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/IconMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/PackageTypesMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/ReadmeMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RepositoryMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RequireLicenseAcceptanceMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RequiredMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RuleIdentifiers.cs
- src/chocolatey/infrastructure.app/rules/ServicableMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/VersionMetadataRule.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/RuleService.cs
- src/chocolatey/infrastructure/rules/RuleResult.cs
- src/chocolatey/infrastructure/rules/RuleType.cs
- tests/chocolatey-tests/commands/choco-pack.Tests.ps1
This pull request updates the new rule engine implemented in #3000 by additionally allowing an identifier and a help url being added to give more information about the rule that was triggered.
To give more information to the user and to allow us to identify as soon as possible what caused a rule to be triggered.
1. Run `choco pack` on the different nuspec files in the `tests/chocolatey-tests/commands/testnuspecs` that start with empty, invalid, missing or required.
- Windows 11
#3000
> (#3000) Add additional information in validation messages

- src/chocolatey.tests.integration/context/dependencies/hasdependency/2.0.1/hasdependency.nuspec
- tests/chocolatey-tests/commands/testnuspecs/basic-dependencies/basic-dependencies.nuspec
- tests/chocolatey-tests/commands/testnuspecs/cdata/cdata.nuspec
- tests/chocolatey-tests/commands/testnuspecs/description-long.nuspec
- tests/chocolatey-tests/commands/testnuspecs/empty-requireLicenseAcceptance.nuspec
- tests/chocolatey-tests/commands/testnuspecs/empty.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-bugtrackerurl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-character-and.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-character-lesser.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-docsurl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-iconurl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-id.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-licenseUrl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-mailinglisturl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-projectsourceurl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-projecturl.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-requireLicenseAcceptance.nuspec
- tests/chocolatey-tests/commands/testnuspecs/invalid-version.nuspec
- tests/chocolatey-tests/commands/testnuspecs/missing.nuspec
- tests/chocolatey-tests/commands/testnuspecs/required.nuspec
- tests/chocolatey-tests/commands/testpackages/chocolatey-dummy-package/1.0.0/chocolatey-dummy-package.nuspec
- tests/chocolatey-tests/commands/testpackages/too-long-description/1.0.0/too-long-description.nuspec
- tests/chocolatey-tests/commands/testpackages/too-long-title/1.0.0/too-long-title.nuspec
- tests/packages/circulardependency1/circulardependency1.nuspec
- tests/packages/circulardependency2/circulardependency2.nuspec
This commit adds a specific version number in each dependency in each of the nuspec files.  This is necessary, since moving into new NuGet.Client assemblies, the version number is a required field in the dependency element, and we have found issues where repository managers don't correctly show/find the dependencies on a V3 feed, when a version isn't available in this element.  There may be other work that needs to be done in Chocolatey to account for this new requirement, but updating all our internal testing packages to have a version number for each dependency will ensure that some automated tests work as expected.
Some end to end tests are failing when using the V3 feed, since not all dependencies are known, and therefore fail to be installed.
Once pushed, these new packages will be …
> (maint) Use specific version for dependencies

- src/chocolatey/infrastructure.app/nuget/NugetList.cs
This merge request fixes a logical operation that had previously been
added to make use of the short circuit variant of the same logical
expression. It changes the compound assignment of `|=` (which is equivalent to `x = x | y|) to make use of the short circuit logic `x = x || y` instead.
This is done to prevent the need to evaluate both of the statements
on each side of the or operator in the cases where pre release is already
marked as true, or when all versions is true already.
There are no functional difference in the results in this case, as such no additional testing has been done.
N/A
> (maint) Fix logical operation to shortcircuit

- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This commit aims to address this problem by only passing the packages to the resolver context where there are no missing dependencies. This has fixed the issue mentioned above, and also the integration tests which were previously failing when the last attempt was made to address this problem:
https://github.com/chocolatey/choco/commit/6a13edc49de1c5627bf239f5a63eb37b0f297d62
When resolving what packages need to be upgraded/installed, we were previously passing in a list of the currently installed local packages. This was used as an attempt to ensure that these packages remained being installed, after the operation was performed.  The side effect of this though was that the install/upgrade operation was too aggressive, and failed the installation/upgrade if an unrelated dependency was …
> (#508) Control packages used for requiredPackageIds

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/packages.config
This commit adds back in the usage of ByIdOnly, ByTagOnly, and IsStartsWith
to the SearchFilter, something that was lost in the uplift to the
latest NuGet.Client libraries, so that more optimixzed queries can be
emitted to the oData server, when we know we only want some information
back.
We want the outgoing queries to the server to be as optimal as possible.
See the test steps in this [PR](https://github.com/chocolatey/NuGet.Client/pull/32)
- #9  
- https://app.clickup.com/t/20540031/PROJ-510
> (#508) Optimize queries used for command line options

- src/chocolatey/infrastructure/extractors/AssemblyFileExtractor.cs
- Rename method parameter to `throwError`
Speling is important! :)
Apart from the fact it's technically a public API change, if it compiles we're good; there are zero functional changes here.
Win11
Fixes #2776
> (#2776) Fix AssemblyFileExtractor spelling error

- src/chocolatey/infrastructure.app/commands/ChocolateyConfigCommand.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
- tests/chocolatey-tests/commands/choco-config.Tests.ps1
- Remove deprecation messages regarding `config list` as they are no longer relevant
- Remove non-config-related output from the config command and service.
We have other commands for listing features, sources, apikeys, etc. Config can finally just be config. Long-awaited deprecation.
1. Build and run with `config list`
2. Ensure only config values and nothing else is listed
3. Run ConfigCommand tests and ensure nothing breaks
Tested on Win11
* I don't think this will happen until the 2.x stable release though?
Fixes #2986
> (#2986) Strip `config list` down to just config

- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
This PR changes the output of `choco config list --limit-output` to be more inline with how other commands format the returned data when `--limit-output` is passed as a parameter to the command.
Consistency in the ability to parse the returned data with a _single_ mechanism makes scripting easier to maintain
1. Debug with `choco config list -r` and observe that output of the config section is consistent with other sections
Fixes #2013
> (#2013) Fix limited output of choco config list

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPushCommandSpecs.cs
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
Adds a new config value DefaultPushSource. This config value is used to set the default source used for
choco push. It goes into config.PushCommand.DefaultSource
If DefaultPushSource is set, it should set the source assuming that
a source is not passed in explicitly with --source. If a source is
passed in explicitly, then DefaultPushSource should not override it.
If --api-key is not passed and a api key has not been saved for the
DefaultPushSource, it will fail with the standard message about an api
key being required.
If DefaultPushSource is set to "disabled", it should throw an error if
there is not an explicit source passed in. But if an explicit source is
passed in, it should not error.
The DefaultPushSource is useful for users that have an internal repository that they want to …
> (#62) Default push source config

- src/chocolatey.resources/helpers/functions/Get-ToolsLocation.ps1
- tests/chocolatey-tests/commands/choco-deprecated.Tests.ps1
- tests/chocolatey-tests/commands/choco-removed.Tests.ps1
- tests/packages/msi.template/templates/ReadMe.md
- tests/packages/zip.template/templates/ReadMe.md
- Remove Get-BinRoot alias
- Remove all mention of it from documentation, template readmes, etc.
- Update tests to ensure it is removed and no longer present
Excising the sins of our past. (It wasn't _that_ bad, but man some of the comments we left behind when we first deprecated it sound _very_ disgruntled 😂 )
Run Invoke-Tests.ps1 and ensure the removal tests pass
Win11
Fixes #2623
> (#2623) Remove Get-BinRoot alias

- tests/chocolatey-tests/commands/choco-config.Tests.ps1
Update Pester tests to remove the Feature and Source output checks.
The config command no longer outputs these.
1. Run through Test Kitchen with the "ConfigCommand" tag.
Windows Server 2016/9
N/A
> (test) Remove Features/Sources from Config tests

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey.tests.integration/scenarios/SearchScenarios.cs
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyListCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateySearchCommandSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
- tests/chocolatey-tests/commands/choco-search.Tests.ps1
- tests/helpers/common/Chocolatey/ConvertFrom-ChocolateyOutput.ps1
- tests/helpers/common/Chocolatey/Get-ChocolateyLicense.ps1
- tests/helpers/common/Chocolatey/Get-ExpectedChocolateyHeader.ps1
- tests/helpers/common/Chocolatey/Test-ChocolateyVersionEqualOrHigherThan.ps1
- tests/helpers/common/Chocolatey/Test-PackageIsEqualOrHigher.ps1
This pull requests splits out the list command to be its own command in the source codes, which can only handle local packages and not remote sources.
In this move, all arguments that had been deprecated for the list command have been completely removed from the list command, and a few remote only arguments will be warning about that they are unsupported (this won't do anything at all).
The tab completion file has also been updated with this new logic, with an adition that remote searches have had their local arguments removed from the tab completion.
To make list searching only local packages, while using search and find will be for remote sources.
1. Run `choco list`
2. Verify only locally installed packages is shown
3. Run `choco search` against a feed not containing 1 or more of the …
> (#158) Split out list command to its own command class

- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
Add all of the possible permutations for the no longer supported list command arguments
When the list of unsupported arguments was created, we missed adding the single-dash variants to the list as well as the double-dash variants.
1. Build Chocolatey CLI
2. Run `choco list -lo` and `choco list --lo` ensure that warning is emitted both times.
3. Run `choco list -all` and `choco list --all` ensure that warning is emitted both times. 
- Windows 10
Fixes #158
> (#158) Add all possible unsupported argument permutations

- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
Add removed shims to list of shims to only remove if signed.
Pester tests failures. Also we shouldn't be removing unsigned shims.
Will run these through Test Kitchen after merge.
None
Fixes #2642
> (#2642) Ensure unsigned shims aren't removed.

- tests/chocolatey-tests/commands/choco-config.Tests.ps1
- tests/chocolatey-tests/commands/choco-removed.Tests.ps1
Update a few tests for some slight changes in the 2.0.0 release.
Some slight changes mean that some of the tests needed to change.
1. Manually ran Test Kitchen against these.
2. Ran Team City Test Kitchen against this branch.
- Server 2019
- Server 2016
N/A These are tests that fail due to the test not the code.
> (maint) Update Pester tests for the 2.0.0 release.

- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/chocolatey-tests/commands/choco-config.Tests.ps1
- tests/chocolatey-tests/commands/choco-info.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-push.Tests.ps1
- tests/chocolatey-tests/commands/choco-search.Tests.ps1
- tests/chocolatey-tests/features/PythonSource.Tests.ps1
Tag tests that will not work in our Test Kitchen Proxy testing environment as `ProxySkip`.
To get a handle on what things work with a proxy and what don't, we need tests that will work in the proxy testing environment.
1. Ran multiple Test Kitchen runs targeting this branch and various Proxy configurations.
2. Ensured they all worked as expected.
* PROJ-522
> (tests) Fix end to end proxy test failures

- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/chocolatey-tests/commands/choco-config.Tests.ps1
- tests/chocolatey-tests/commands/choco-info.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
- tests/chocolatey-tests/commands/choco-push.Tests.ps1
- tests/chocolatey-tests/features/PythonSource.Tests.ps1
Tag tests that will not work in our Test Kitchen Proxy testing environment as `ProxySkip`.
To get a handle on what things work with a proxy and what don't, we need tests that will work in the proxy testing environment.
1. Ran multiple Test Kitchen runs targeting this branch and various Proxy configurations.
2. Ensured they all worked as expected.
* PROJ-522
> (tests) Fix end to end proxy test failures (stable branch)

- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
This merge request updates the tests we have for open source
Chocolatey CLI after the changes we expect to need to be
made in our internal structure to make sure they still
are able to pass.
We have a need to change our internal structure, as such we need to make minor changes to the tests as well to make sure they are still valid and have not been broken.
1. Run through test kitchen
- https://app.clickup.com/t/20540031/PROJ-532
> (maint) Fix test executions after internal changes

- src/chocolatey/NuGetVersionExtensions.cs
- Make `NuGetVersionExtensions` static class `public`
These extension methods aren't widely used, but we would prefer to be able to use them in the licensed extension directly rather than duplicating code.
N/A, no functional change from here, just making a thing public so we have an easier time in CLE.
Win11
N/A
> (maint) Make NuGetVersion extension methods public

- .github/workflows/stale.yml
Added cleanup of stale issues and PR's with the '0 - Waiting On User' label..
This will make it easier to manage the repository as stale issues will auotmatically be labelled, commented on and then closed if no follow-up work is done.
N/A
N/A
> (maint) Add stale cleanup

- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/infrastructure.app/builders/ConfigurationBuilderSpecs.cs
- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- tests/chocolatey-tests/commands/choco-removed.Tests.ps1
- tests/chocolatey-tests/features/Proxy.Tests.ps1
Read in system configured and environment variable set proxy information.
With the uplift of the NuGet libraries, the Proxy configurations were not being honoured. 
1. Update `Vagrantfile` in the `tests` directory to set `$env:TEST_KITCHEN` to `1` (uncomment line 62)
2. Run `vagrant up` from the `tests` directory
* To run just the newly added tests you can add `Tag = 'Proxy'` to the `Invoke-Tests.ps1` file after line 119
4. Ensure that all Proxy related tests pass
Tests also run in Test Kitchen on Team City.
- Windows Server 2022
* PROJ-536
* #1720
> (#1720) Ensure documented proxy settings are used

- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
The changes in this PR validate whether a custom object is null before trying to recursively set its properties.
If the object is null, we'll just make that as part of the output string instead of trying to set any of the properties on the object.
We don't want any null custom object values to prevent the running of the application, and/or unit tests.
1. Build and copy changes into debug version of Chocolatey Licensed Extension.
2. Run unit tests
3. No failures are expected.
N/A
> (maint) Fix null config value throwing exception

- tests/chocolatey-tests/commands/choco-info.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-search.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- tests/chocolatey-tests/features/PythonSource.Tests.ps1
Update the Pester tests for wording and other changes so that they all pass on Test Kitchen.
Some wording changed, as well as some testing setup.
Run within Test Kitchen to verify tests now pass.
* Windows Server 2016
* Windows Server 2019
* PROJ-534
> (tests) Update Pester tests to pass based on wording changes in latest release

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- Only add licensed / Business-only commands and options to tab completion if the user has the appropriate Chocolatey license.
Note that this check is deliberately naive; we don't look at the license too hard, just try to determine if there _is_ one and if it is a Business/Trial license. Since this only affects tab completion and Choco does its own license checks separately, we don't need to be too stringent about exactly what is needed for the licensed options to be returned.
In future, we should simply query available commands and options from choco directly, but this is a "good enough" patch in the meantime until that day comes.
Previously all commands and options would be returned from tab completion regardless of whether they could actually be used.
With this change, tab completion …
> (#2887) Tab completion: only complete license-appropriate things

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyInfoCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
- tests/chocolatey-tests/commands/choco-info.Tests.ps1
Throw errors when conditions are not correct: either no package was passed, or multiple packages were passed to `choco info`.
Currently the output of the `choco info` command without any further input states `0 packages found.` This _should_ throw an error that input is required in the form of a single package id.
1. Debug in Visual Studio with multiple input conditions: No input, single input, multiple input
Fixes #2899 
Fixes #
> (#2899) Info command should warn when no id used

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- tests/chocolatey-tests/chocolateyProfile.Tests.ps1
- Fix issue for PSv2 where `Ignore` is not a valid ErrorActionPreference
- Fix test to check for commands correctly, and actually ensure all the commands are listed by fixing up and repurposing the commented-out portion of the tab completion test
- Add missing `support` command to tab completion for folks with a Business license (which I discovered was missing when I fixed this test, woO!)
PSv2 compat is, apparently, still vaguely important, I guess. And also tab completion tests were broken. Must fix.
- Run the invoke-tests.ps1 script. Maybe set the tag to `Profile` if you just wanna run these ones.
I tested on win11, but this has previously been tested on PSv2 and this was the only issue we're aware of there. Would be good to re-check PSv2 if possible.
Related to changes made for #2887
> (#2887) Fix tab completion in v2, tests, and add `support` to tab completion

- tests/chocolatey-tests/chocolatey.Tests.ps1
- Add test for `choco list` with a missing `lib` directory
In CLE, there are cases where having a missing lib directory will break some commands.
However, the behaviour still needs to be asserted for CLI to ensure that we have the correct test here, and we will also run these tests under CLE in order to ensure that adding the extension does not break this edge case anymore.
1. Run test
2. Test does not fail.
Win11
N/A, tests only
> Add tests for missing lib directory

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyListCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
This PR addresses this by adding specific handling for the option
combinations that were previously documented on our site, showing a
warning when they are used, and directly setting the
IncludeRegistryPrograms configuration value when required.
This code will be removed in a future version of Chocolatey, most
likely in V3.
When the work was done to change the behaviour of choco list to only
include information about local packages, we missed the ability to run
a command like choco list -li.  Historically, this command would have
listed all locally installed packages, as well as information about
applications that have been directly installed outside of Chocolatey.
This was due to the fact that since -l is no longer a parsed argument.
the argument parser doesn't interpret the other …
> (#158) Add handling for -li option

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyConfigCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyFeatureCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/ChocolateyConfigSettingsServiceSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyFeatureCommand.cs
- src/chocolatey/infrastructure.app/domain/FeatureCommandType.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
- src/chocolatey/infrastructure.app/services/IChocolateyConfigSettingsService.cs
- tests/chocolatey-tests/commands/choco-feature.Tests.ps1
Allows to filter the list of features by the name parameter (-n or --name)
This makes it very easy to find a specific feature in an instant, without needing to search the entire list.
Further this feature was [requested](https://github.com/chocolatey/choco/issues/2815)
1. Run `choco feature get bob`
2. Should error that feature can't be found
3. Run `choco feature get --name bob`
4. Should error that feature can't be found
5. Run `choco feature get checksumFiles`
6. Should return Enabled
7. Run `choco feature get --name checksumFiles`
8. Should return Enabled
9. Run `choco feature get allowGlobalConfirmation`
10. Should return Disabled
11. Run `choco feature get --name allowGlobalConfirmation`
12. Should return Disabled
* Fixes #2815
* https://app.clickup.com/t/20540031/PROJ-565
> (#2815) Add new choco feature get subcommand

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPushCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
- tests/chocolatey-tests/commands/choco-help.Tests.ps1
- Move the errors / logic from the AdditionalArgumentParsing into the Validate method instead
- Update the tests to match the behaviour
We should avoid throwing from `ParseAdditionalArguments` entirely, as throwing from here means that not even `--help` works for the command at all, unless the user figures out what other params to provide to avoid the errors, which is just not how help should work.
This error was introduced as part of #2430, this PR is a follow up to fix the behaviour and the related tests.
1. Run the unit tests
2. Tests should pass
3. Run `choco push --help` with no `defaultPushSource` config and no `--source` set.
4. You should be able to see the help message
Win11
#2219
> (#2219) Defer errors from defaultpushsource until validation for ChocolateyPushCommand

- src/chocolatey.tests.integration/context/unsupportedelements/1.0.0/unsupportedelements.nuspec
- src/chocolatey.tests.integration/context/unsupportedelements/1.1.0/unsupportedelements.nuspec
- src/chocolatey.tests.integration/scenarios/PackScenarios.cs
- src/chocolatey.tests/infrastructure.app/nuget/NugetCommonSpecs.cs
The added integration tests ensure that a minClientVersion attribute that is higher
then the Chocolatey and NuGet assembly versions does not prevent installation
or packing. 
And a unit test ensures that the user agent is set, when NuGet sources are configured
and that it uses the upstream version of NuGet that the NuGet assembles are
based on. This same version is used in other areas as well, like minClientVersion,
so it applies to multiple areas.
See #1935 
With the uplifted NuGet assemblies, the `minClientVersion` is no longer checked at all, bypasses the fixes the issue of the Chocolatey assembly version being used instead of the NuGet assembly version being used.
Ran tests in Visual Studio and with `build.ps1`
Built and installed package with `minClientVersion` set to `100.0.0` to …
> (#1935) Add tests to ensure upstream NuGet version is used.

- src/chocolatey/infrastructure/registration/HttpsSecurity.cs
- Make HttpsSecurity class and the Reset method public
The old method is needed in CLE, so we should make the new one public as well.
N/A, API visibility change only.
N/A
Related to #2902
> (#2902) Make HttpsSecurity class public

- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- tests/chocolatey-tests/features/Proxy.Tests.ps1
Update Proxy configuration to parse the setting if it's specifying multiple protocols.
Windows has the concept of protocol specific proxies, as such it can store the proxy information in the registry as `http=server:port;https=server:port;ftp=server:port;socks=server:port`. We need to parse this instead of just blindly taking it.
1. Ran build locally
2. Ran build in Team City.
3. Ran Test Kitchen on Team City.
* Fixes #1720 
* PROJ-583
> (#1720) Parse multi-protocol proxy configurations

- tests/chocolatey-tests/commands/choco-search.Tests.ps1
- tests/helpers/common-helpers.psm1
- tests/helpers/common/Chocolatey/Test-HasNuGetV3Source.ps1
Mark some pester tests to skip if they're being tested against a v3 endpoint and the Licensed Extension is in play.
For some reason the results coming back from our v3 endpoint are not consistent, and we're seeing failures in these tests when licensed extension is tested against our v3 endpoint.
1. Ran Test Kitchen in Team City against both Chocolatey CLI and Chocolatey Licensed Extension
2. Noted these tests failing only on Licensed Extension with output indicating some of the packages not coming back from the repository server.
3. Added the skip conditions
4. Ran Test Kitchen in Team City against both Chocolatey CLI and Chocolatey Licensed Extension
* Windows Server 2016
* Windows Server 2019
* PROJ-518
> (tests) Skip some Pester tests if the repository endpoint is a v3 endpoint

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/services/RulesServiceSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/rules/EmptyOrInvalidUrlMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/FrameWorkReferencesMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/LicenseMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/MetadataRuleBase.cs
- src/chocolatey/infrastructure.app/rules/PackageTypesMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/ReadmeMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RepositoryMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RequireLicenseAcceptanceMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/RequiredMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/ServicableMetadataRule.cs
- src/chocolatey/infrastructure.app/rules/VersionMetadataRule.cs
- src/chocolatey/infrastructure.app/services/RuleService.cs
- src/chocolatey/infrastructure/rules/IMetadataRule.cs
- src/chocolatey/infrastructure/rules/ImmutableRule.cs
- src/chocolatey/infrastructure/rules/RuleResult.cs
This commit updates all available rules to return a read only
list of the rules each rule class implements, as well as updating
the rule engine to gather these rules so they can be used further
in the future when we have a need for this information.
Huge thanks to @corbob to get this started.
There are future plans to improve the handling of rules, and to be able to do these in the future it is required to make changes to the rule engine and its rules to give this information.
1. Run unit tests
- N/A
- https://app.clickup.com/t/20540031/PROJ-595
> (maint) Add ability to get rules from the registered rules.

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- Fix failing CI tests
- Improve error reporting when they fail
- Small fix into tab completion for ensuring expected & handled errors don't pollute $error for users. 
- This was actually the cause of some of the failing tests, as they were checking $error to determine if something failed or not. :(
Wanting to sort out our test failures before release.
Tested locally where I can, but I will also be testing in CI.
Win11
N/A, tests only.
> (maint) Fix failing Pester tests

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- Ensure we don't remove things that don't exist from $error in tab completion setup
I couldn't repro this locally, but it's been giving CI some grief and it's a simple fix, so this should sort that out.
1. Run test kitchen
2. Profit!
Win10, Win11
Related to changes from #3135
> (maint) Fix occasional errors on importing tab completion

- tests/chocolatey-tests/chocolatey.Tests.ps1
- Fix the "can we load and run signed scripts" test to actually test what we want it to test instead of worrying about occasional things getting into $error that don't actually have any impact.
Tests flaky and don't seem to work the same everywhere, plus we should test whether it actually breaks or not :<
Tested locally as thoroughly as I can, it _seems_ to be fine, but so did the prior fixes. I'll run this through teamcity as well to be sure.
Win11
Test fix only
> (tests) Fix temperamental test

- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
Mark a few upgrade tests concerning locked files FossOnly for now.
These tests fail inexplicably on teamcity only if CLE is installed, but these failures can't be reproduced locally.
Marking them as FossOnly for now, we'll file follow up issues in CLE to investigate.
N/A, just flagging partially broken CLE tests so we can follow up on them later.
N/A
N/A
> (tests) Mark some upgrade tests for locked files FossOnly

- .editorconfig
- src/chocolatey.tests.integration/scenarios/InfoScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/chocolatey-tests/commands/choco-uninstall.Tests.ps1
The changes in this pull request updates the uninstall behavior by now allowing multiple packages to be uninstalled at the same time, even if one of those packages are a dependency of the other package without it aborting all uninstalls.
To do this, it made it easier to do a custom sort of the packages to uninstall by keeping the order of dependencies being tried in the correct order. Unfortunately this is not always possible, and in these cases a Warning will be outputted to the user without stopping any uninstalls for other packages.
If the package that was warned about is still not uninstalled at the end of the entire execution, this will show up as an error/failure for the package.
Before running the uninstall script or any other uninstall related behavior, we remove any failures on a …
> (#508) Fix multiple packages being uninstall fails if one is a dependency

- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/chocolatey-tests/commands/choco-uninstall.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
THe change in this PR ensures that any warnings that are outputted as part of a failure in a before modify script is propagated to the end of any uninstall, or upgrade so it can more easily be identified by the user/maintainer.
To make errors and warnings more visible to the user.
1. Install smoke package `upgradepackage` version `1.0.0`.
2. Upgrade smoke package to latest version (`1.1.0`)
3. Ensure there is an additional warning list after upgrade that mentions an error in the before modify script.
4. Uninstall `upgradepackage` v1.1.0
5. Ensure no warning is outputted regarding the before modify script.
6. Install again the smoke package `upgradepackage` version `1.0.0`
7. Uninstall the same smoke package.
8. Verify there is an additional warning list after uninstall that mentions an …
> (#508) Add warning result if before modify script fails

- src/chocolatey/infrastructure.app/services/NugetService.cs
This commit adds a warning, to inform the user that this may be happening.
When running choco search, there are several options that would have previously caused packages to be filtered on the server side, before being returned to the client. The options were --approved-only, --download-cache, and --not-broken.  The decision was taken to no longer have these options passed to the server, since they can't (currently) be respected on a V3 feed.  Instead, the filtering is applied on the client side, within Chocolatey CLI.  The end result is that it is possible to get incomplete pages of data returned, as some packages may be filtered out on the client, and no additional packages will be requested.
1. Run `choco search randompackage` and see that no warning is output
2. Run `choco search …
> (#508) Add warning about filtering of packages

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/packages.config
- tests/chocolatey-tests/commands/choco-uninstall.Tests.ps1
The changes in this pull request make use of the changes that have been added in Chocolatey's NuGet.Client to allow uninstalls of a package to continue even if one or more of its dependencies are referenced by a different package.
Additionally, there is also a change to the order of package uninstalls to try ensuring they are uninstalled in the correct order when multiple package names has been specified.
This change was required so packages can uninstall themself with any dependencies that aren't referenced by other packages.
The change in the ordering was done to prevent warnings being outputted when they aren't needed by making sure that dependencies specified on the commandline are attempted after the parent package that was also specified (only possible if the dependency is a direct …
> (#508) Fix forcing dependency uninstall fails if dependency is referenced by other packages

- src/chocolatey/infrastructure.app/services/PowershellService.cs
- Added an explicit override to our PowerShell runner preamble to ensure TLS settings are correctly set to the SystemDefault.
See #3123 for some context in terms of the rationale.
During testing we determined that some Windows PowerShell versions, for example the builds provided on Server 2019 and below, are configured to _override_ the system's TLS settings and force the settings to `Tls, Tls11, Tls12` (though the exact setting seems like it may depend on the Windows and/or Windows PowerShell version). As covered in the related issue and previous PR, this is explicitly enabled TLS downgrade attacks if the system has been hardened, and additionally prevents users from communicating with any servers that use TLS 1.3 for the duration of the PowerShell task during package operations.
1. …
> (#2902) Ensure Chocolatey's default TLS settings are used in PowerShell tasks

- nuspec/chocolatey/chocolatey/chocolatey.nuspec
- nuspec/nuget/chocolatey.lib/chocolatey.lib.nuspec
Removed some warnings about prerelease versions and known issues links from the nuspec
Won't be relevant any longer once the v2 release is up.
1. Build the packages.
2. Inspect the nupkg and ensure the nuspec description doesn't contain the prerelease / known issues warnings.
N/A
N/A, these were only here for the prerelease alpha/beta versions.
> (maint) Remove nuspec prerelease warnings

- src/chocolatey/BannedSymbols.txt
- src/chocolatey/EnumExtensions.cs
- src/chocolatey/TypeExtensions.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/RuleService.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-uninstall.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
This pull request updates the Equals comparisons in the NuGet service to be case insensitive.
This is done as without this change the user will always have to pass in the identifier in the exact casing that is returned from the NuGet server, causing issues especially during upgrade scenarios.
Additionally, Equals and Compare methods has been added to the banned API list to prevent the use
of these without specifying a StringComparison.
The behaviour in v2.x and 1.x should behave similar, and we should not expect the user to do the work for us to ensure the casing of installed packages, server packages and passed in identifier to be the same casing
1. Install the package 7zip using `choco install 7ziP --confirm`
2. It should successfully install
3. Do a noop upgrade using `choco upgrade …
> (#508) Do case insensitive comparison on package ids

- src/chocolatey/infrastructure.app/nuget/NugetList.cs
This pull request updates the FindPackage method we use when installing
and acquiring information about a package to properly handle feeds
when there is a mix of feeds that support v2 odata queries, and when
there is one or more feeds that only support v3 feeds without the fallback
to v2 odata APIs.
Even when a user uses a mixture of v2 odata queries, v3 with odata v2 support and v3 only feeds, we should still be able to get the information about a specific package and be able to install/upgrade this package.
1. Configure Chocolatey CLI with Chocolatey Community Repository feed, and an internal v3 only feed (will send message internally about the feed).
2. Run `choco info isdependency` while having both feeds configured, or passing in both sources using `--source`
3. Verify no error was …
> (#508) Fix v3 feeds mixed with v2 feeds not finding packages

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyListCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/ChocolateyPackageServiceSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUninstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/registration/ChocolateyRegistrationModule.cs
- src/chocolatey/infrastructure.app/registration/IContainerRegistrator.cs
- src/chocolatey/infrastructure.app/registration/SimpleInjectorContainerRegistrator.cs
- src/chocolatey/infrastructure.app/runners/GenericRunner.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/CygwinService.cs
- src/chocolatey/infrastructure.app/services/IChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/ISourceRunner.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/PythonService.cs
- src/chocolatey/infrastructure.app/services/RubyGemsService.cs
- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
- Restore `--source` param for `choco list`
- Add a handful of interfaces for the functionally different pieces of `ISourceRunner`
- Add appropriate interfaces for each currently available ISourceRunner
- Add pre-checks into ChocolateyPackageService which verifies which methods that the source runner it's trying to invoke supports and throws an error (or warning, in the case of `DryRun` / `--noop` operations) before ever trying to run it if the source runner doesn't support that operation.
- Update a few affected mocks in tests to ensure they still work correctly.
Since alternate sources can list installed packages separately to our normal package list, we need to allow list to specify --source. This will have no effect for normal sources, but will select alternate source runners if …
> (#158) Restore --source for choco list

- tests/chocolatey-tests/chocolatey.Tests.ps1
- tests/chocolatey-tests/commands/choco-apikey.Tests.ps1
- tests/chocolatey-tests/commands/choco-config.Tests.ps1
- tests/chocolatey-tests/commands/choco-export.Tests.ps1
- tests/chocolatey-tests/commands/choco-feature.Tests.ps1
- tests/chocolatey-tests/commands/choco-help.Tests.ps1
- tests/chocolatey-tests/commands/choco-info.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
- tests/chocolatey-tests/commands/choco-new.Tests.ps1
- tests/chocolatey-tests/commands/choco-outdated.Tests.ps1
- tests/chocolatey-tests/commands/choco-pack.Tests.ps1
- tests/chocolatey-tests/commands/choco-pin.Tests.ps1
- tests/chocolatey-tests/commands/choco-push.Tests.ps1
- tests/chocolatey-tests/commands/choco-source.Tests.ps1
- tests/chocolatey-tests/commands/choco-template.Tests.ps1
- tests/chocolatey-tests/commands/choco-uninstall.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- tests/chocolatey-tests/commands/choco-version.Tests.ps1
- tests/helpers/common/Chocolatey/New-ChocolateyInstallSnapshot.ps1
- tests/helpers/common/Chocolatey/New-ChocolateyTestPackage.ps1
- tests/helpers/common/NuGet/Get-NuGetPaths.ps1
- tests/helpers/common/NuGet/Remove-NuGetPaths.ps1
- tests/helpers/common/NuGet/Test-NuGetPaths.ps1
This pull request updates the tests we run for 1.x of Chocolatey CLI to be equivalent to the tests we have added in Chocolatey CLI v2.0.0
To have the same area covered for both v1 and v2 of Chocolatey CLI.
A test kitchen run will be triggered.
N/A
- https://app.clickup.com/t/20540031/PROJ-322
> (maint) Migrate 2.0.0 tests to 1.x

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
The changes in this pull request reintroduces the ability to get the amount of packages available on remote and local nuget sources, which had been overlooked during a previous refactor.
Without the changes made in this PR it will cause Chocolatey GUI to not function properly when it tries to get packages from remote and local sources configured in `chocolatey.config`.
When this is attempted Chocolatey GUI would crash with an exception that a normal source runner could not be found (due to NuGetService not being seen as a source runner anymore).
1. Clone the changes in this PR.
2. Clone the latest tag of Chocolatey GUI.
3. Run `Get-ChocoUpdatedDebugVersion.ps1 -ChocoSourceLocation "<PATH_TO_CLONED_PR_CHANGES>"`.
4. Build Chocolatey GUI.
5. Run Chocolatey GUI.
6. Navigate to one of the …
> (#3165) Update count method to support nuget service

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyListCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
- Relegate the warnings for `-lo` / `-li` etc to log file only.
- Update relevant tests
After some discussion internally we determined that for folks to have smooth migration paths a log-file-only warning makes the most sense.
1. Run `choco list -lo`
2. Verify no warning is shown
3. Check the log file
4. The logs should contain a warning about the unsupported option
5. Repeat with `-li` instead of `-lo`
Win11
Fixes #158
> (#158) Relegate the -lo/-li warning to log-file-only

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyListCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
- Ensure the warning for using `-lo` is visible when not using `-r`
- Add an exit code along with the visible warning (not added when using `-r`)
- Update tests accordingly
Because we do want people to see it, but we don't necessarily want it getting in the way of automation tools.
1. `choco list -lo`
2. Warning should be shown, and the exit code should be `1`
3. `choco list -lo -r`
4. Warning should not be shown, and the exit code should be `0`
5. Check the log file and ensure the warning still appears in logs.
Win11
#158
> (#158) Restore `list -lo` warning when not using -r

- src/chocolatey/infrastructure.app/utility/ArgumentsUtility.cs
This commit adds the various forms that the user option can be passed
to the Chocolatey CLI, to ensure that it is always caught.
Since user is one half of the information that is needed for a
credential, let's treat the user as sensitive information, in the same
way that we treat password.
Follow the steps in this PR: https://github.com/chocolatey/ChocolateyGUI/pull/1002 and ensure that both user and password are not displayed.
This will require running the `Get-ChocoUpdatedDebugVersion.ps1` script to pull through the latest version of Chocolatey CLI through to Chocolatey GUI.
Windows 10
Relates to #948 where this functionality was first introduced.
> (#948) Add user as sensitive argument

- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
`LocalOnly` is mentioned in help text and needs to be removed.
but as this has now been removed, it no longer makes sense and should be removed.
This is just help text that has been amended.
This has not been tested.
* [ x Requires a change to the documentation.
#3177
> (#3177) Remove LocalOnly from help text

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UninstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/AutomaticUninstallerService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageInformationService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/PowershellService.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
- src/chocolatey/infrastructure/results/PackageResult.cs
Went through all references to `ToStringSafe` which were being called on a NuGetVersion instance and changed them all to `ToNormalizedStringChecked`.
Additionally, found a place in the upgrade dry-run code that was just missing a call to this method and outputting a non-normalized version string and added it.
We should be consistent in how we internally and externally represent versions as strings, so that folks relying on our output for consistent comparisons don't need to think too hard about it.
1. `choco install 7zip --ignore-dependencies`
2. `choco upgrade --noop 7zip -r`
3. The output result should display `7zip|22.1.0|22.1.0|false` exactly (unless a new version of 7zip has been installed, so just verify the version numbers match exactly)
We _might_ be able to add a smoke test …
> (#3174) Apply version number normalizing consistently

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
For the pin commands add and remove, find the package to pin/unpin
using an exact list, not a normal search, to ensure that only an exact
matching package ID is returned, and therefore pinned/unpinned.
A test is also added for this, using the mingw and gstreamer-mingw
package IDs, which is what was reported causing problems in the issue.
Fix pinning/unpinning.
After some testing, the problem affects both pinning, not just unpinning. 
Ran:
```
.\choco.exe install mingw -n
.\choco.exe pin add -n mingw
.\choco.exe install gstreamer-mingw -n
.\choco.exe pin add -n gstreamer-mingw
.\choco.exe pin remove -n mingw
```
Then ensured that the `mingw` package was unpinned, not the `gstreamer-ming` package.
As a second test, unpinned both `mingw` and `gstreamer-mingw` and tried `.\choco.exe pin add …
> (#3196) Pin add/remove use exact package ID

- src/chocolatey.tests/TinySpec.cs
- src/chocolatey.tests/infrastructure.app/services/RulesServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/RuleService.cs
When finding the distinct rules that are available in Chocolatey CLI
and its extensions, the equals and GetHashCode was incorrectly
implemented which in some cases causes the incorrect rules to be
returned, or not returned.
This commit updates these two methods to handle the check for
getting the hash code, and comparing immutable rules in the way
that we expect them to behave.
To have a functional way to get all available rules in Chocolatey CLI and its extensions.
1. Run unit tests.
- Windows 10
Fixes #3182
> (#3182) Fix rule distinction comparison

- CONTRIBUTING.md
Added a great PR example to the CONTRIBUTING.md file.
We need a good example to help people when contributing.
This is just a change to a markdown document.
N/A
#3108
> (#3108) Add PR example

- src/chocolatey.tests.integration/Scenario.cs
- src/chocolatey.tests.integration/scenarios/SearchScenarios.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
There was a threshold warning added to Chocolatey CLI v2.0.0 that
would warn users about searches issued when one of the sources used
has equal or more packages available than what the threshold is set to.
Unfortunately this was only working when a single source was being used
in Chocolatey CLI v2.0.0.
The changes in this PR makes the necessary changes to have this
functionality work as expected again for multiple sources.
We want the threshold warning to show up when the user hits this threshold, both when a single source is used and when multiple sources are used.
1. Create the directory "C:\testing"
2. Ensure the `chocolatey` source is enabled.
3. Add the testing directory as a new source (`choco source add -n local -s C:\testing`)
4. Run `choco search 7zip --page-size 2`
5. Verify a …
> (#3190) Fix threshold warning missing on multi-source

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/configuration/ConfigurationOptions.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateySourceCacheContext.cs
The changes here will add a global option that can be used
by the user to ignore any existing http cache that has been
created prior to the execution of the current command.
Using the option will still create a new cache for the running
execution and reuse that created cache in the current context,
and can be reused normally when not using the argument in the
future.
To give the user the ability to bypass the cache when needed, as well as being able to bypass the cache in other products we have.
1. Run `choco outdated` (To generate an up to date cache)
2. Open up fiddler
3. Run `choco outdated --ignore-http-cache`
4. Verify requests are sent out for each package.
5. Remove items in the folders `C:\ProgramData\ChocolateyHttpCache` and `C:\Users\<YOUR_USERNAME>\.chocolatey\http-cache`
6. …
> (#3193) Add ability to ignore current http cache

- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- tests/chocolatey-tests/features/EnvironmentVariables.Tests.ps1
Previously, in this commit:
https://github.com/chocolatey/choco/commit/da19356578e3c90850ac766f150ccebf809c6ce2#diff-cb6a0471e41268b22a928bd57a59d51b70b7024e9beb30e89a330e193a089eba
The usage of the top level CacheLocation and
CommandExecutionTimeoutSeconds values had been removed, since these top
level properties within the chocolatey.config had been replaced with
values contained within the config section of the chocolatey.config
file.
However, the changes in that commit were too aggressive, and removed
the call to the set_config_item (which has subsequently been renamed to
SetConfigItem).  The method call does the work of taking any value that
is defined in the chocolatey.config for a given property name, and
adding it to the ChocolateyConfiguration instance.  When this method
call was …
> (#3201 #3225) Re-instate setting of config properties

- src/chocolatey/StringResources.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/services/PowershellService.cs
- src/chocolatey/infrastructure.app/templates/ChocolateyReadMeTemplate.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
In a previous change we normalized all versions that was being used
in Chocolatey CLI. This caused certain packages that uses non-normalized
version numbers to start failing to look up additional information in other
products.
To work around this problem we need to store the non-normalized version
of the package when scripts are being ran. This is done by adding a new
environment variable that can be used, this environment variable is considered
private and is not for public consumption.
To be able to look up the proper information for legacy packages.
Enable the hermes choco-test-packages source.
1. Run `choco install test-environment --version 0.9`
2. Verify `chocolateyPackageVersion=0.9.0` is outputted.
3. Verify `packageVersion=0.9.0` is outputted.
4. Verify …
> (#3174) Store non-normalized package version

- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/configuration/EnvironmentSettings.cs
- tests/helpers/common/Chocolatey/Get-ChocolateyVersion.ps1
Update the logic used to determine if Chocolatey should set the Licensed Environment to include if the Assembly is loaded.
If the assembly has not been loaded, we should consider Chocolatey Licensed Extension unavailable.
1. Follow the Manual Testing steps for an [Incompatible Chocolatey Licensed Extension](https://chocolatey.atlassian.net/wiki/spaces/DEV/pages/1562771487/Manual+Testing+Process+-+Chocolatey#Testing-Incompatible-Chocolatey-Licensed-Extension-with-Chocolatey).
2. Run some manual commands with `--skip-compatibility-check`.
3. Ensure that you get an exception about unable to load chocolatey.lib with the official strongname public key.
4. Enable the feature (`choco feature enable -n disableCompatibilityChecks`) to disable the check and run some manual commands.
5. Ensure that …
> (#3224) Do not try to use the Licensed Assembly when it is not loaded for compatibility reasons.

- src/chocolatey/infrastructure.app/validations/GlobalConfigurationValidation.cs
- src/chocolatey/infrastructure.app/validations/SystemStateValidation.cs
This commit updates the output from the validation results to adhere to
this best practice.
When using the full name of an option, the recommendation is always to
use -- and not a single -.
Not required.
- Windows 10
N/A
> (doc) Apply scripting best practices to output

- Invoke-AuthedTests.ps1
- src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
Attempt to use the default credentials for the first attempt at a source.
Important note of behaviour change: If we are not able to authenticate with a source, we now prompt 3 times instead of 4, and the first one is prefaced with an `Invalid credentials specified` warning.
When attempting a query to a source that requires credentials, we were always prompting for credentials. This prevents attempting the default credentials unless entering an empty password. We should attempt initially with the default credentials, and only prompt if it's a retry for credentials.
1. Ran Test Kitchen test suites. All tests behaved as expected.
2. Ran some manual tests against an authenticated source without username/password. Confirmed it still prompted for credentials.
3. Ran some manual tests against a …
> (#3242) Attempt default credentials for sources

- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This optimizes the flow of the upgrade command. First, it uses the
list of locally installed package from the if all is specified check,
instead of throwing that away. Then, it will re-use the list for each
package upgrade attempt, only refreshing the list when a package
upgrade/install is attempted. This speeds up upgrade all runs,
especially when a large (200+) number of packages are installed.
Upgrades on my machine are really slow as compared with their speed on v1.4.0
1. Clean the debug directory, then build debug choco from develop
1. Create this `packages.config` file:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
<package id="7zip" />
<package id="7zip.install" />
<package id="adobeair" />
<package id="adobereader" />
<package id="adobereader-update" />
<package …
```
> (#3231) Don't refresh local package info during upgrade no-ops

- src/chocolatey/ExceptionExtensions.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NuGetEndpointResources.cs
- When resolving resources for a repository, take the initial warning we have and then inspect its inner exceptions.
- Log _all_ exception messages found this way to Debug, except for the last one which is logged as a warning again.
The reason the outermost and innermost exceptions are logged as warnings and the rest are relegated to debug is so that we have the best chance of giving users the most actionable information -- often the surface or the deepest exception contain the real problem, while the ones in the middle are often not as useful. However, should we encounter cases where the others are needed, users can inspect the log file for the additional messages, or use `--debug` to see them on a re-run.
Previously all that was logged was the surface exception, which in quite a few …
> (#3258) Expand logging for nuget resources errors

- tests/chocolatey-tests/commands/choco-push.Tests.ps1
Clear the HTTP caches before trying to get the pushed package.
We are seeing sporadic failures of this test when the package is in fact there. This should help resolve that.
Running in Test Kitchen (about the only place we see these failures)
N/A
> (tests) Clear HTTP Cache before getting packages

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPushCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
This commit expands the existing exception message, to explain how the defaultPushSource can be set via the choco config command, rather than only showing how a source can be passed directly.
Based on some feedback that came in via Twitter from a package maintainer, providing information about how to set the defaultPushSource via the choco config command would be helpful when in this situation.
1. Build the project
2. Run `choco push`
3. Verify that the error output now contains information about how to set defaultPushSource via `choco config` command
- Windows 10
N/A
> (doc) Improve error message for defaultPushSource

- src/chocolatey/infrastructure.app/services/NugetService.cs
Removed 'You are smarter than the average bear...' from being displayed. 
It's fun, and it's been there for some time, but from issue #3186 the humour maybe doesn't travel well. Rather than adding a feature just to turn this off, I don't think there is anything lost by removing it.
I wasn't sure whether to remove the final newline, so let me know.
This isn't parsable output, so _I_ don't believe this is a breaking a change.
None. This is just removing a string of text.
N/A
Fixes #3186
> (#3186) Remove easter egg "You are smarter than the average bear ..."

- src/chocolatey/StringExtensions.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/registration/ChocolateyRegistrationModule.cs
- src/chocolatey/infrastructure.app/validations/CacheFolderValidationLockdown.cs
- src/chocolatey/infrastructure/filesystem/DotNetFileSystem.cs
- src/chocolatey/infrastructure/filesystem/IFileSystem.cs
These changes introduces a new validation check to ensure that
the system cache folder that is used for storing NuGet responses
have been properly locked down to administrators.
When the directory exists, and allows modifications or creations of
files by normal user this will output a validation warning about steps
that can be taken to lock down the directory.
When the directory does not exist, this same validation check ensure
that the directory is created while only allowing Administrators to
modify, create or delete anything in the folder.
We should do what we can to prevent malicious users to make modifications to something that can have reporcussions for the user that is installing a package.
1. Create directory `C:\ProgramData\ChocolateyHttpCache` and delete any log files
2. Run the …
> (#3281) Add validation for cache folder permissions

- src/chocolatey.install/chocolatey.en-us.wxl
- src/chocolatey.install/chocolatey.wxs
Update the MSI settings to prevent an upgrade, and to not remove the Chocolatey files.
If you try to upgrade Chocolatey using the MSI with an already installed MSI, the upgrade was attempting to uninstall the old Chocolatey, and did not actually upgrade to the new Chocolatey.
1. Build the PR and grab the MSI from the Artifacts directory
2. Using the build MSI perform two phases of testing:
1. Install Chocolatey CLI from the built MSI
2. Ensure that Chocolatey works (run `choco --version --allow-unofficial`)
3. Uninstall Chocolatey CLI from the Add/Remove Programs control panel
4. Ensure that Chocolatey still works (run `choco --version --allow-unofficial`)
1. Install Chocolatey CLI 2.2.0 through the MSI
2. Attempt to upgrade Chocolatey CLI using the built MSI
3. Ensure that you get an …
> Update MSI installer to prevent upgrades and not partially remove Chocolatey

- docs/legal/CREDITS.md
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/packages.config
To fix a bug in licensed extension when downloading packages and the cache location is set to a restricted folder, there was a need to update Chocolatey.NuGet.Client and pull in the changes to Chocolatey CLI. This PR makes the necessary changes for this.
See description
See the testing step in the NuGet.Client PR: https://github.com/chocolatey/NuGet.Client/pull/47
- Windows 10
- Windows Server 2022
Fixes #3291
> (#3291) Update Chocolatey.NuGet.Client libraries to 3.4.2

- tests/pester-tests/chocolatey.Tests.ps1
- tests/pester-tests/commands/choco-apikey.Tests.ps1
- tests/pester-tests/commands/choco-config.Tests.ps1
- tests/pester-tests/commands/choco-deprecated.Tests.ps1
- tests/pester-tests/commands/choco-export.Tests.ps1
- tests/pester-tests/commands/choco-feature.Tests.ps1
- tests/pester-tests/commands/choco-help.Tests.ps1
- tests/pester-tests/commands/choco-info.Tests.ps1
- tests/pester-tests/commands/choco-install.Tests.ps1
- tests/pester-tests/commands/choco-list.Tests.ps1
- tests/pester-tests/commands/choco-new.Tests.ps1
- tests/pester-tests/commands/choco-pack.Tests.ps1
- tests/pester-tests/commands/choco-pin.Tests.ps1
- tests/pester-tests/commands/choco-push.Tests.ps1
- tests/pester-tests/commands/choco-removed.Tests.ps1
- tests/pester-tests/commands/choco-source.Tests.ps1
- tests/pester-tests/commands/choco-template.Tests.ps1
- tests/pester-tests/commands/choco-uninstall.Tests.ps1
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
- tests/pester-tests/commands/choco-version.Tests.ps1
Normalize the exit code checking of the Pester tests. Add proper Chocolatey License check where needed.
This normalizes the exit code checking of the pester tests so that if they don't return as expected we have the output of the command. Also to bring some of the install/upgrade tests in line with the develop branch.
Ran through Test Kitchen in Team City (see link to gep13 in Slack)
Windows Server 2016/2019
* Related to #2712
> (#2712) Normalize ExitCode pester test on Support Branch

- tests/pester-tests/chocolatey.Tests.ps1
- tests/pester-tests/commands/choco-apikey.Tests.ps1
- tests/pester-tests/commands/choco-config.Tests.ps1
- tests/pester-tests/commands/choco-export.Tests.ps1
- tests/pester-tests/commands/choco-feature.Tests.ps1
- tests/pester-tests/commands/choco-help.Tests.ps1
- tests/pester-tests/commands/choco-list.Tests.ps1
- tests/pester-tests/commands/choco-new.Tests.ps1
- tests/pester-tests/commands/choco-pack.Tests.ps1
- tests/pester-tests/commands/choco-pin.Tests.ps1
- tests/pester-tests/commands/choco-removed.Tests.ps1
- tests/pester-tests/commands/choco-search.Tests.ps1
- tests/pester-tests/commands/choco-source.Tests.ps1
- tests/pester-tests/commands/choco-template.Tests.ps1
- tests/pester-tests/commands/choco-uninstall.Tests.ps1
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
- tests/pester-tests/commands/choco-version.Tests.ps1
Normalize the exit code checking of the Pester tests.
This normalizes the exit code checking of the pester tests so that if they don't return as expected we have the output of the command.
Ran through Test Kitchen in Team City (see link to gep13 in Slack)
Windows Server 2016/2019
* Related to #2712
> (#2712) Normalize ExitCode pester tests

- .github/workflows/build.yml
- .teamcity/settings.kts
- recipe.cake
This PR splits the current general TeamCity build which runs unit tests on a version control trigger and unit + integration tests on a schedule into two separate builds:
* Chocolatey CLI (Built with Unit Tests) `ID: Chocolatey`
* Chocolatey CLI (Scheduled Integration Testing) `ID: ChocolateySchd `
It also introduces an additional build specifically for running Code Analysis and Dependency Checking:
* Chocolatey CLI (SonarQube) `ID: ChocolateyQA`
Note: Please advise if these names are appropriate, and recommend alternatives as needed.
This change enables TeamCity to accurately track how long each build configuration should take to run and how many tests each should run.
This has been tested on a non-Production TeamCity instance, the KTS file imported successfully and the three builds ran …
> (#3342) Separate TeamCity Builds: Unit test, Scheduled integration test, QA

- .teamcity/settings.kts
This PR installs the `dotnet-6.0-runtime` package required for the QA Build / Dependency-Check to run.
Older versions of the build agent had this baked in, but it is no longer in newer versions. Instead of re-introducing it to the build agent image, we'll install it when needed in order to run the Dependency-Check task.
To test that the build agents can install `dotnet-6.0-runtime` and that installing it allows the Dependency-Check task to run, the user data script was temporarily amended to add this install at that point in the build process.
This worked and the Dependency-Check task ran as expected.
Build
N/A
> (build) Install dotnet-6.0-runtime for QA Build

- recipe.cake
- src/chocolatey.console/Program.cs
Add the ability to debug Self Service Mode from Chocolatey Agent.
Chocolatey Agent adds `--run-actual` on every Chocolatey CLI command run. When we're in debug mode and `--run-actual` is passed to Chocolatey CLI, we should not pause execution at the end as we're likely in agent and cannot acknowledge the pause.
This also adds a change to the cake recipe to add `--run-actual` on the `unpackself` step as when we're building a debug version we don't want to pause for the user to press a key.
1. Ran `./build.debug.bat` and confirmed it didn't wait for me to press any key.
2. Ran debug build with `--run-actual` and configmred it didn't wait for me to press any key.
3. Debugged Chocolatey GUI through agent in https://github.com/chocolatey/ChocolateyGUI/issues/967
Windows 10
* Chocolatey GUI PR: …
> (maint) Add ability for Agent debugging

- docker/Dockerfile.linux
Updates the dockerfile to use the archive backports repository to install git, as the backports for debian 10 (buster) are no longer actively maintained.
Docker build was failing.
https://github.com/chocolatey/choco/actions/runs/8707820224/job/23883728475
Tested in docker locally, and GitHub actions passes.
https://github.com/TheCakeIsNaOH/choco/actions/runs/8715912320/job/23908561086
N/A
N/A, build maintenance.
> (build) Linux Dockerfile switch to archive backports repository

- README.md
There is no `zip.sh` in the repository, hence remove its reference. Also, use wildcards so the docs still apply in case more changes are made in the future.
Outdated docs.
N/A
N/A
N/A
> (doc) Remove reference of `zip.sh` from README.md

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyFeatureCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyConfigCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyFeatureCommand.cs
Fixing typos and punctuation for the feature command messages.
Typos and punctuation.
N/A
N/A
As this was just a maint fix to typos and punctuation in strings, no issue was created.
> (maint) Fix typos and punctuation in Feature command messages

- src/chocolatey/infrastructure.app/validations/SystemStateValidation.cs
Changed 'Pending Reboot' warning message to be more accurate grammatically.
Fixes no issue
> (maint) Fix grammatical issue in pending reboot warning message

- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
Update the wording of the Proxy help output to be clear about what is expected.
The help output is not clear that Proxy Bypass List is expected to be a regular expression.
1. Ran build script.
2. Ran `GenerateDocs.ps1`
3. Copied files over to `chocolatey/docs` repository to verify updates.
N/A This is just an update to the help output/docs.
- Fixes #3401 
- chocolatey/docs#958
- chocolatey/docs#952
> (#3401) Update Proxy documentation

- src/chocolatey.tests/TinySpec.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/ChocolateyConfigSettingsServiceSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/ChocolateyPackageServiceSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyApiKeyCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyConfigCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyFeatureCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySourceCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This adds enhanced exit codes to the `apikey`, `config`, `feature`, `pin`, `source` and `upgrade` commands. Specifically, it adds exit code 2 for when there is nothing to do. All of these commands except `upgrade` have a `NOCHANGEMESSAGE` that is output, this sets exit code 2 if the conditions are met for that message to be logged, enhanced exit codes are enabled, and there is not another preexisting exit code set other than zero.
The upgrade command required returning more information from a method to allow checking if no packages were outdated. The check is done by checking that there are no successes or failures.
Adding support for enhanced exit codes in more commands is useful for users that script choco, as it gives more information in a easily usable format of an exit code.
I did …
> (#1759) Add enhanced exit codes for multiple commands

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/services/CygwinService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/PythonService.cs
- src/chocolatey/infrastructure.app/services/RubyGemsService.cs
- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
- tests/pester-tests/features/PythonSource.Tests.ps1
This adds the ability to install all packages from a source via the all
keyword. It runs a list against the current sources, and sets the
package names from that list of packages. 
This functionality is only intended to be used with internal
repositories. Therefore a list of public repositories has been added,
and the current sources are checked against it to ensure only internal
sources are specified.
Renames the `set_package_names_if_all_is_specified function` to
`set_local_package_names_if_all_is_specified`. This is to increase
clarity with the `set_remote_package_names_if_all_is_specified` now being added.
Also this throws a not implemented exception if the all keyword is used with
non-nuget alternate sources. This is because the all keyword only has
handling built in for normal …
> (#23) Handle all keyword for install

- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
This commit introduces the idea that the dotnet installation needing a reboot should not immediately halt the Chocolatey installation, but instead proceed as far as possible - then prompt for a reboot without throwing.
The install script currently throws after dotnet 4.8 is installed, which requires the user reboot and then re-run the install script. This, at least, reduces the need for an additional step post-reboot.
1. Build or finagle Chocolatey package with updated setup functions
I downloaded the [Chocolatey 2.2.2 package](https://community.chocolatey.org/api/v2/package/chocolatey/2.2.2) and used 7zip to overwrite `chocolateysetup.psm1` with my changes.
2. Download [Install.ps1](https://community.chocolatey.org/install.ps1)
3. Run `Install.ps1 -ChocolateyDownloadUrl …
> (#3327) Improves UX of Chocolatey Install without 4.8

- src/chocolatey/infrastructure/platforms/Platform.cs
This allows Chocolatey CLI to detect Windows 11, Server 2019 and Server 2022.
Which will allow the OS_NAME environment variable to be set correctly on those
operating systems.
See #2754
N/A
Fixes #2754
> (#2754) Add support for detecting newer Windows versions

- src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This logs the package source uri to info before downloading nupkgs
during both install and upgrade. Additionally, it debug logs the
download URI that the nupkg available at. 
The information outputs for both individual package installs/upgrades,
and for dependencies that get installed/upgraded by their parent 
package. This information is especially useful when multiple sources
are in play, so the user can determine where individual packages 
are coming from.
See #1485
Now that Chocolatey CLI is using NuGet.Client libraries, this was trivial to implement.
See added NUnit tests for installing/upgrading from a local source.
For remote sources:
1. Run `.\choco.exe install wget --force --skip-powershell --debug`
1. Validate that the previous command logged the source and download url
1. Run …
> (#1485) Display package source during install/upgrade

- src/chocolatey.resources/helpers/functions/Start-ChocolateyProcessAsAdmin.ps1
Add a guard into Start-ChocolateyProcessAsAdmin to ensure we don't accidentally recurse in the case of calling back into helper commands that themselves call Start-ChocolateyProcessAsAdmin.
I don't _like_ how messy the error is, but it's better than spawning infinite processes, and I'm not clear on how to tidy up the error in this case as the clixml is not correctly consumed by the receiving PowerShell process.
This shouldn't recurse like this, if the first elevation fails, retrying it is silly.
I'd _like_ to add tests for this, but I think all our testing currently runs in an admin context, so there's... not much we can do there.
1. Download the following test package to the `C:\packages` folder: [add-path.1.0.0.zip](https://github.com/chocolatey/choco/files/15044790/add-path.1.0.0.zip) …
> (#3424) Fix potential recursive elevation attempts

- src/chocolatey/infrastructure.app/commands/ChocolateyUnpackSelfCommand.cs
This commit adds deprecation notices around the `unpackself` command, in order to make people aware
that this command in going away in v3.0.0.
Based on internal conversations, while the unpackself command is currently being used as part of the overall build process, it is not something that is "required". So, rather than leave this command in place, let's deprecate it, and then remove the command completely in the next major version of Chocolatey CLI.
With this command removed, it will be necessary to change the build process to sign the PowerShell files earlier in the build process than they currently are, but it shouldn't impact on the end result at all.
1. Run `choco -h`
2. Ensure that the deprecation notice can be seen in the section that lists out all the commands
3. Run `choco …
> (#3426) Add deprecation notice for unpackself

- src/chocolatey/infrastructure.app/domain/ChocolateyPackageInformation.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageInformationService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
Saves the location of where the contents of the Chocolatey package
(whether that is a native installer, or an extraction of a zip file, or
whatever else is in the package) is deployed to into a
".deploymentLocation" file inside the package info directory.
This allows Chocolatey CLI or GUI to later retrieve it and display it to
the user when listing the details of locally installed package(s).
See #3315
1. `.\choco.exe install wget --force`
1. Ensure that the software location is logged and a `.softwareLocation` file containing the path is created in the folder under `.chocolatey`
1. `.\choco.exe install wget --skip-powershell --force`
1. Ensure that there is no software location logged and there is no `.softwareLocation` file 
1. `.\choco.exe install balcon`
1. Ensure that the software …
> (#3315) Save software installation location

- TESTING.md
- tests/Vagrantfile
Enhance the local testing setup to allow faster writing and iterating on Pester tests
The existing setup required rebuilding the Chocolatey CLI package every time you wanted to test changes to tests.
1. In the `tests` directory run `vagrant up`
2. Verify that the tests run.
3. Delete some (or all) of the pester test files.
4. Run `vagrant provision default --provision-with test`.
5. Verify that the deleted pester file is no longer executed (when I tested, I went from 29 files evaluated to 28 files evaluated).
6. Run `vagrant provision default --provision-with clear-packages,test`.
7. Verify that the `clear-packages` provisioning script runs, followed by the test packages being packaged during the `test` provisioning script.
- Host: Windows 10
N/A
> (maint) Enhance local testing developer experience

- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
This updates the NuGetCommon class to better handle lookups of package dependencies when an exact version range is used as the dependency.
Additionally, some optimizations when looking up valid packages are also implemented, by only look up the dependencies of a dependency that is inside of the valid version range that the package specifies.
Some optimizations, and better handling of exact version ranges. Additionally, without this change users of CCR will not be able to install a meta package and its dependency until both have been approved or exempted.
Testing have been performed against an internal testing repository which will be called out as hermes.
1. `choco install hasbetadependency --version 1.1.0-beta --ignore-http-cache --verbose --source hermes`
2. Verify queries used for …
> (#3433) Optimize queries used when resolving dependencies of exact versions

- src/chocolatey.tests.integration/scenarios/ListScenarios.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/utility/ArgumentsUtility.cs
This adds the listing of remembered arguments to the list/info commands
It only grabs the arguments when --local-only is specified, then
decrypts and outputs them. Requires --verbose to be listed on the
command line.
If `useRememberedArgumentsForUpgrades` is enabled, it is useful to know what argument are remembered.
1. Install some packages, like `.\choco install iperf2 --pre --ia="argument" --params="/param"` and `.\choco install wget --params="/param"`
1. Run `.\choco.exe list --verbose` and check that the remembered arguments are listed.
1. Run `.\choco.exe info iperf2 --local-only` and check that the remembered arguments are listed.
1. Run `.\choco.exe info iperf2` and check that the remembered argument are NOT listed.
Fixes #1310
> (#1310) List remembered arguments

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyRuleCommandSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyRuleCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/utility/ArgumentsUtility.cs
- src/chocolatey/infrastructure/services/IRuleService.cs
This adds a new command called ´rule` with an alias of `rules` to be able to view any Validation Rules that have been implemented by Chocolatey CLI, or the details of a specific view.
To give visibility to users an what will happen/validated when they package their Chocolatey CLI package, as well intended enhanced functionality that will be implemented outside Chocolatey CLI that can reuse this same command.
1. Run `choco rules` (also try `choco rule list`). You should then see something similar to  
2. Run `choco rule get --name CHCR0002`. You should then see something similar to  
3. Run `choco rules -r`. You should then see something similar to  
4. Run `choco rule --name missing`. You should see something similar to
5. Run `choco rule get --name missing`. You should see something …
> (#3381) Add new rule command

- Invoke-Tests.ps1
- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyInstallPackage.ps1
- tests/Vagrantfile
- tests/packages/install-chocolateyinstallpackage-tests/chocolateyinstall.ps1
- tests/packages/install-chocolateyinstallpackage-tests/install-chocolateyinstallpackage-tests.nuspec
- tests/pester-tests/chocolatey.Tests.ps1
- tests/pester-tests/commands/Install-ChocolateyInstallPackage.Tests.ps1
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
Fix a bug where concatenating `$silentArgs` and `$additionalInstallArgs` adds a trailing space at the end of `$silentArgs` even when `$additionalInstallArgs` is empty. Such trailing space can change the meaning of the last positional argument (that may contain spaces).
Final arguments are now created as space joined string arrays filtered down to only non-empty items. Fix is applied to all installer types.
I have some installers doing similar thing as Total Commander (mentioned in #2345 ) - passing installation destination as last positional argument allowing spaces in it. Added trailing space caused by `"$silentArgs $additionalInstallArgs"` when `$additionalInstallArgs` is empty breaks this mechanism and attempts to install to path that ends with space.
NOTE: I am just an ordinary …
> (#2345) Avoid any trailing spaces after silentArgs

- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
Adds back the overload in NuGetList that had been changed to only used the base class.
This is reintroduced, as it was causing problems with Chocolatey Licensed Extension.
Not possible to properly test, until it has been built by soteria.
1. Install Chocolatey CLI from this PR (officially strong named)
2. Install Chocolatey Licensed Extension
3. Attempt to install a package that have dependencies.
4. Verify no errors are reported.
- Windows 10
Related to #3433
> (#3433) Add overload for FindPackages method

- src/chocolatey/infrastructure/registration/SimpleInjectorContainer.cs
This commit puts back in place the default values for the property,
using the exisitng cmpilers directives.
In a previous commit:
https://github.com/chocolatey/choco/commit/8c422301e4589b879d866e710d1261abf0bdab4e#diff-56c83e4e3e69e032ca2de3fefe172645908c9db983ef1a9080cc3aa87ea5b773R45
A change was made to fix IDE0032 on some parts of the
SimpleInjectorContainer class.  However, the change that was made
missed the fact that there was a compiler directive in place that
changed the default value for the property. While in debug mode, it
defaulted to true, but in anything else, it defaulted to false.
Initially during testing, this didn't cause any problems, however, when
using Chocolatey Agent, it caused errors to occur during start up of
the service.  This was due to the fact that in …
> Revert change made to way that IoC Container verification is performed

- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
- src/Chocolatey.PowerShell/Helpers/EnvironmentHelper.cs
- src/chocolatey.resources/helpers/chocolateyInstaller.psm1
- tests/pester-tests/chocolatey.Tests.ps1
- tests/pester-tests/commands/choco-apikey.Tests.ps1
- tests/pester-tests/commands/choco-config.Tests.ps1
- tests/pester-tests/commands/choco-feature.Tests.ps1
- tests/pester-tests/commands/choco-info.Tests.ps1
- tests/pester-tests/commands/choco-install.Tests.ps1
- tests/pester-tests/commands/choco-outdated.Tests.ps1
- tests/pester-tests/commands/choco-pin.Tests.ps1
- tests/pester-tests/commands/choco-push.Tests.ps1
- tests/pester-tests/commands/choco-rule.Tests.ps1
- tests/pester-tests/commands/choco-search.Tests.ps1
- tests/pester-tests/commands/choco-source.Tests.ps1
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
- tests/pester-tests/features/CygwinSource.Tests.ps1
- tests/pester-tests/features/PythonSource.Tests.ps1
- tests/pester-tests/features/RubySource.Tests.ps1
- tests/pester-tests/features/WindowsFeaturesSource.Tests.ps1
- tests/pester-tests/powershell-commands/Get-EnvironmentVariable.Tests.ps1
- tests/pester-tests/powershell-commands/Install-ChocolateyPath.Tests.ps1
- tests/pester-tests/powershell-commands/Set-EnvironmentVariable.Tests.ps1
- tests/pester-tests/powershell-commands/Uninstall-ChocolateyPath.Tests.ps1
- tests/pester-tests/powershell-commands/Update-SessionEnvironment.Tests.ps1
A number of new Pester tests have been added to cover functionality that has been added.
A lot of new functionality has been added into the develop branch ahead of the 2.3.0 CLI release.
We need to add tests to verify all of this new functionality, and to ensure that there are no regressions going forward.
This also includes a minor bugfix for an issue that surfaced in our test environment.
These tests have been validated locally, but we will also kick off some tests runs once this PR is raised.
N/A
> Add Pester tests to cover functionality added in Chocolatey CLI 2.3.0

- .teamcity/settings.kts
This PR makes each build configuration in the TeamCity KTS file reference a template containing standard Slack notification configuration, which applies said configuration to the build configuration without having to duplicate it in each.
Enables standard notification configuration across all build configurations in this project.
This has been tested by pointing a development TeamCity instance at the branch from which this merge request is originating.
N/A
Build configuration change (non-breaking)
~~* [ ] Bug fix (non-breaking change).~~
~~* [ ] Feature / Enhancement (non-breaking change).~~
~~* [ ] Breaking change (fix or feature that could cause existing functionality to change).~~
~~* [ ] Documentation changes.~~
~~* [ ] PowerShell code changes.~~
N/A
> (build) Add templated notifications to all build configurations

- .github/CODEOWNERS
Add CODEOWNERS file, so that we can track future changes to files.
This is an attempt to ensure that any changes to our dependencies, whether that is:
* changes to NuGet packages through packages.config files
* updates to custom assemblies which are not tracked through NuGet packages
* updates to custom executables/assemblies which are added directly to the Chocolatey CLI Chocolatey Packages
Are tracked and updated properly.  By making these files/folder owned by the new @chocolatey-credits-reviewers group, it means that a member of that group will be flagged on any PR's that we raised that contain these files.
N/A
N/A
N/A
> (maint) Add CODEOWNERS files

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
Updated the NUnit3TestAdapter package from 4.4.2 to 4.5.0.
NOTE:  There have been no changes to the license for this package, it remains under the MIT license.
It was found that this was out of date during some internal review, and the decision was made to update.
With the changes in place, a full build was done on my development machine, and the full suite of tests have been run through the Test Explorer within Visual Studio, and everything works as expected.
N/A
N/A
> (maint) Update NUnit3TestAdapter

- .gitignore
- .vscode/extensions.json
- docs/legal/CREDITS.md
This commit addresses this by updating all version numbers, both in the
table of contents, and the main body of the document, to match what is
actually being used.  In addition, the license that is in place for the
Microsoft.Web.Xdt dependency is updated to reflect that correct one, as
this was recently updated.
Finally, a small typo was fixed:
Licensed Terms -> License Terms
Also, adds a new extension recommendation for VSCode.
This extension is useful when editing Markdown files, especially when
it contains a Table Of Contents. This extension will update the TOC
simply by making changes to the main body.
In order to get this new file to be included, it was necessary to add
another exclusion to the rules in the .gitignore file.
During a review, it was found that the CREDITS.md file, …
> (doc) Update CREDITS.md file to match what is actually being used

- src/chocolatey.tests.integration/App.config
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
This commit addresses the issue by first checking to see if the package folder exists.  If it doesn't, then it doesn't attempt to create the .chocolateyPending file, and simply returns early.  This then allows the remaining operations, i.e. returning the package folder from the lib-bkp folder, back to the lib folder.
The MarkPackagePending method is used to create a .chocolateyPending file in the package folder to indicate that there is a pending operation that needs to be completed.
However, during an upgrade operation, the package folder is moved to the lib-bkp folder, and as a result, doesn't exist anymore in the lib folder.
If during the upgrade operation, something fails, for example, an exception when trying to download the nupkg file, a process of returning the package folder to …
> (#3489) Return early when folder doesn't exist

- src/chocolatey/infrastructure.app/templates/ChocolateyInstallTemplate.cs
Fixed a type on an incorrect parameter name as pointed out on [Discord](https://discord.com/channels/778552361454141460/897090709914517544/1276269212318306324).
The parameter name is `WorkingDirectory`, however we use `workDirectory` in the template.
N/A
N/A
N/A
> (doc) Fixed parameter name typo

- src/chocolatey.resources/helpers/functions/Install-ChocolateyPinnedTaskBarItem.ps1
Deprecate the Install-ChocolateyPinnedTaskBarItem command to prepare for it to be removed in v3.
The function is being deprecated as the functionality in Windows is constantly changing and breaking.
N/A
N/A
Fixes #3520
> (#3520) Deprecate Install-ChocolateyPinnedTaskBarItem

- .vscode/settings.json
- README.md
- recipe.cake
- setup.ps1
Add documentation on how to complete build of Chocolatey CLI.
We got some feedback that is wasn't clear on how to build Chocolatey CLI
New VM in Azure Portal was created, and steps executed as documented.
N/A
N/A
> (doc) Update build instructions

- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
- Remove code relating to migration from a `C:\chocolatey` install folder from the `chocolateysetup.psm1` module used for installing Chocolatey.
This migration path hasnt been supported or used since pre-1.0 versions of Chocolatey and is dead code.
Removing this now to simplify the install process somewhat and get the old code out of the way as it's not used at all.
1. Run `build.ps1` to generate a package
2. Copy the generated nupkg to a fresh VM and take a snapshot
3. Install Chocolatey using the following PowerShell code from an admin shell, substituting the nupkg path for the nupkg you copied over:
```powershell
${function:Install-Choco} = [scriptblock]::Create((Invoke-WebRequest https://community.chocolatey.org/install.ps1))
Install-Choco -ChocolateyDownloadUrl …
```
> (#3501) Remove old install migration code

- src/chocolatey/infrastructure.app/services/NugetService.cs
Updated the threshold text to make it easier to understand.
The text that Chocolatey CLI displays can be confusing. Particularly, when the search result shows less than 1000 packages on-screen (as they have been filtered out).
N/A
N/A
N/A
> (maint) Make threshold limit text clearer

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- src/chocolatey.resources/helpers/chocolateyProfile.psm1
(A continuation of https://github.com/chocolatey/choco/pull/3387. Most descriptions below are copied from there)
Fix broken tab completion (expansion) in PowerShell v7.4+ by using the new Register-ArgumentCompleter API
TabExpansion is not used since PowerShell 7.4, so the export of legacy `TabExpansion` function is made conditional on the PowerShell version.
As discussed in https://github.com/chocolatey/choco/issues/3364:
* Chocolatey's tab completion broke in v7.4.0, due to an intentional breaking change in PowerShell (removal of legacy code, as a side effect of which PowerShell no longer calls custom TabExpansion functions, if defined).
* The recommended approach (since v5.0) is to use Register-ArgumentCompleter
Interactively (tab completion).
Windows 10 22H2
I don't have access to …
> (#3364) Fix broken tab completion (expansion) in PowerShell v7.4+

- src/Chocolatey.PowerShell/Commands/InstallChocolateyPathCommand.cs
- src/Chocolatey.PowerShell/Commands/SetEnvironmentVariableCommand.cs
- src/Chocolatey.PowerShell/Commands/UninstallChocolateyPathCommand.cs
- src/Chocolatey.PowerShell/Commands/UpdateSessionEnvironmentCommand.cs
- src/Chocolatey.PowerShell/Helpers/EnvironmentHelper.cs
- tests/helpers/common/Get-WhatIfResult.ps1
- tests/pester-tests/powershell-commands/Install-ChocolateyPath.Tests.ps1
- tests/pester-tests/powershell-commands/Set-EnvironmentVariable.Tests.ps1
- tests/pester-tests/powershell-commands/Uninstall-ChocolateyPath.Tests.ps1
- tests/pester-tests/powershell-commands/Update-SessionEnvironment.Tests.ps1
- Add ShouldProcess support to `Set-EnvironmentVariable`, `Install-ChocolateyPath`, `Uninstall-ChocolateyPath`, and `Update-SessionEnvironment`
- Add unit tests verifying just the base logic of the commands, that the ShouldProcess lines get hit when you use -WhatIf in the appropriate circumstances.
- Tag potentially destructive / system-state-modifying tests with `VMOnly` so they do not run by default in typical dev environments
In discussion with @gep13 we realised there is value in having the ability to non-destructively verify the logic paths taken in the code here. As such, I have augmented the existing commands and associated helper classes with ShouldProcess semantics to make this workable.
1. Run `build.ps1`
2. Run `./Invoke-Tests.ps1 -Tags WhatIf`
WIn10
Part of #3318
Docs PR: …
> (#3318) Add ShouldProcess support to rewritten helper cmdlets

- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
- Add a null check to the Command Name when determining if we should decrypt the stored arguments.
- Exclude packages installed on Test Kitchen from the upgrade commands downgrade tests.
- The CommandName is missing when calling the List method from alternate sources.
- Test Kitchen has some extra packages on it that will get upgraded unless we exclude them.
1. Run tests through Test Kitchen.
- #3503 
- #3513
> (#3503, #3513) Add null check to Command Name

- tests/helpers/common/Get-WhatIfResult.ps1
- tests/pester-tests/features/PageSize.Tests.ps1
- tests/pester-tests/powershell-commands/Install-ChocolateyPath.Tests.ps1
- tests/pester-tests/powershell-commands/Set-EnvironmentVariable.Tests.ps1
- tests/pester-tests/powershell-commands/Uninstall-ChocolateyPath.Tests.ps1
- tests/pester-tests/powershell-commands/Update-SessionEnvironment.Tests.ps1
Fix some small test errors
A couple of small errors in the -WhatIf tests showed up on teamcity, so this should hopefully fix those.
Testing in test kitchen
Win 2016 & 2019
#3318
> (#3318) Fix -WhatIf tests

- tests/pester-tests/features/UserAgent.Tests.ps1
- Pick out a single user agent / process tree to check in tests
Licensed does queries in the background before / while normal commands are running, so we can end up with multiple user-agent debug lines.
Resolve this by just looking at the most recently-outputted user agent, as these should all look the same (and if not, the last one should be the one from the actual command run).
1. Test in test kitchen w/ CLE
2019
#3526
> (#3526) Fix user agent test for licensed

- .github/workflows/build.yml
- .teamcity/settings.kts
- recipe.cake
- tests/pester-tests/features/ArgumentsDecryption.Tests.ps1
Update the Recipe used to default to not build an MSI. Update the CI configurations to allow building the MSI with the addition of the `--shouldBuildMsi=true` parameter.
Ease the experience of making adjustments to the MSI. Allow us to get an MSI more regularly for testing.
1. Ran `./build.bat --target=Build-Msi`
2. Noted that it failed to build as a previous task was skipped.
3. Ran `./build.bat --target=Build-Msi --shouldBuildMsi=true`
4. Noted that it completed successfully.
5. Checked the `code_drop/Artifacts` and `code_drop/MSIs/en-US` directories to confirm that an MSI was generated.
6. Monitored the GHA for this PR to note that an MSI was generated and included with the artifacts.
7. Monitored the Team City build for this PR to note that an MSI was not generated (because it's not a …
> (#3465) Allow building an MSI during outside of tagged commits.

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/infrastructure.app/nuget/NugetListSpecs.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
This updates the handling of searching for packages while at the same time specifying the version that is wanted of the packages.
This ensures that packages will be looked up to verify it has the version the user wants, before returning any results.
When a v3 only feed was being used, no package would be outputted to the console.
1. Run the integration tests
2. Copy the contents of the index.json file from one of your sources.
3. Remove the entry in the file mentioning LegacyGallery.
4. Upload the file to a remote location, and update your sources.
5. Run choco search <PACKAGE_NAME> --version <PACKAGE_VERSION> (replace values with known values of a package and older version)
6. Run the same command against your original feed that have a entry for LegacyGallery
7. Compare the results and …
> (#3396) Add specific version check on v3 searches

- src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySourceCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
- tests/helpers/common/Chocolatey/Disable-ChocolateySource.ps1
- tests/helpers/common/Chocolatey/Enable-ChocolateySource.ps1
- tests/helpers/common/Chocolatey/Get-ChocolateySource.ps1
- tests/pester-tests/features/CredentialProvider.Tests.ps1
Backport #3568 to Chocolatey CLI 1.x
See https://github.com/chocolatey/choco/issues/3566 - the credentials are being reused in places that they shouldn't.
Ran through Test Kitchen locally and in Team City.
To test with CLE locally I editted the `nupkg` produced by Team City and changed the  version reported to be `1.5.0-pullreques` and then tested with CLE `5.0.6`.
Screenshot from local test kitchen run:
- Fixes #3566
> (#3566) Avoid credential bleed from saved sources with the same hostname

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/nuget/ChocolateyNugetCredentialProviderSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
- tests/helpers/common/Chocolatey/Disable-ChocolateySource.ps1
- tests/helpers/common/Chocolatey/Enable-ChocolateySource.ps1
- tests/helpers/common/Chocolatey/Get-ChocolateySource.ps1
- tests/pester-tests/features/CredentialProvider.Tests.ps1
- Rework handling in ChocolateyNugetCredentialProvider to ensure we only match credentials from the full URL
- Add a config property so we can actually tell what the literal arguments passed to `--source` on the command line are, and start making use of it here to aid with looking up source credentials.
- In discussions with Gary, we have agreed the behaviour of looking up a source based purely on the URL here is bad In General, because choco should probably just use the literal command line arguments and not assume you want it to look things up in the config when you did not ask, so this will later be expanded upon and some of the searching functionality here can be removed at a later date.
- Add unit tests for this credential provider
See #3565 - the credentials are being reused in …
> (#3565 #2421) Avoid credential bleed from saved sources with the same hostname

- .github/workflows/build.yml
- .teamcity/settings.kts
- recipe.cake
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/infrastructure.app/nuget/NugetListSpecs.cs
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/nuget/ChocolateyNugetCredentialProviderSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInfoCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyListCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyOutdatedCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpgradeCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- tests/helpers/common/Chocolatey/Disable-ChocolateySource.ps1
- tests/helpers/common/Chocolatey/Enable-ChocolateySource.ps1
- tests/helpers/common/Chocolatey/Get-ChocolateySource.ps1
- tests/pester-tests/commands/choco-push.Tests.ps1
- tests/pester-tests/features/ArgumentsDecryption.Tests.ps1
- tests/pester-tests/features/CredentialProvider.Tests.ps1
- tests/pester-tests/features/UserAgent.Tests.ps1
This is the finalization of the Chocolatey CLI 2.4.1 release.
This includes the milestone [2.4.1](https://github.com/chocolatey/choco/milestone/70)
> (release) 2.4.1

- src/chocolatey.console/Program.cs
- src/chocolatey/GetChocolatey.cs
When an attempt is made to use trace logging in a non-elevated session, a warning will be shown, and no trace logging will be shown.  In addition, if the -r option is in play, the warning about no trace logging will go to the log file, but won't be displayed.
Prior to this change, trace level logging was available to everyone. However, due to the sensitive nature of some of the output, the decision has been taken to restrict trace logging to only elevated sessions.
1. Run `choco search --trace` as an administrator - see the trace logging displayed
2. Run `choco search --trace` as a non-administrator - see a warning about not using --trace and no trace logging
3. Run `choco search --trace -r` as a non-administrator - see that there isn't a warning and also no trace logging, check the log …
> (#3603) Don't allow trace logging when no elevated

- src/chocolatey.console/Program.cs
- src/chocolatey/GetChocolatey.cs
When an attempt is made to use trace logging in a non-elevated session, a warning will be shown, and no trace logging will be shown.  In addition, if the -r option is in play, the warning about no trace logging will go to the log file, but won't be displayed.
Prior to this change, trace level logging was available to everyone. However, due to the sensitive nature of some of the output, the decision has been taken to restrict trace logging to only elevated sessions.
1. Run `choco search --trace` as an administrator - see the trace logging displayed
2. Run `choco search --trace` as a non-administrator - see a warning about not using --trace and no trace logging
3. Run `choco search --trace -r` as a non-administrator - see that there isn't a warning and also no trace logging, check the log …
> (#3604) Don't allow trace logging when not elevated

- CONTRIBUTING.md
- src/Chocolatey.PowerShell/CONTRIBUTING.md
- src/Chocolatey.PowerShell/Chocolatey.PowerShell.csproj
- Added CONTRIBUTING.md document to the Chocolatey.PowerShell project.
Given we use some slightly custom bits in Chocolatey.PowerShell that will alter how contributors are expected to work with the cmdlets in this project compared to how more bare-bones projects handle C# cmdlets, this document outlines some of the more notable changes as well as the common design practices we will be using here.
N/A, doc only.
N/A
Fixes #3539
> (#3539) Add design documentation for C# cmdlets

- .github/workflows/build.yml
Update GitHub Actions to use `ubuntu-22.04` so they have access to `mono`
`mono` is not available on `ubuntu-latest` and this is causing our GitHub Actions to fail.
This PR should have all of the GitHub Actions pass.
N/A
* Fixes #3607
> (build) Update GHA to pin ubuntu version

- src/chocolatey.console/Program.cs
- src/chocolatey/GetChocolatey.cs
This is the finalization of the Chocolatey CLI 1.4.2 release.
This includes the milestone [1.4.2](https://github.com/chocolatey/choco/milestone/72?closed=1).
> (release) Chocolatey CLI 1.4.2

- .github/workflows/build.yml
- .github/workflows/test.yml
This updates the version used in the GitHub workflows to be a version
of upload-artifact that does not throw an exception.
The current version we are using started throwing an exception yesterday
due to it no longer being recommended to be used.
So to be able to continue building through the GitHub workflows, we must update this dependency.
N/A
N/A
N/A
> (maint) Update version for upload-artifact

- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
- src/chocolatey/infrastructure.app/nuget/ChocolateyPackageDownloader.cs
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/registration/ChocolateyRegistrationModule.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
This adds a new Package Downloader class and have it call a resolve
redirection for download URIs to the original source URI.
This allows the same credentials to be used for the download URI as with
the source URI when the server is configured to store binary files in
a different location.
Without this change, it makes it impossible to install packages that have a download location that do not have the source URI as its prefix.
1. Install a package from the following location. CCR, Licensed Feed, Nexus Feed and ProGet feed, local package directory and a remote package directory.
2. Install another package, that have one or more dependencies with the above feed types.
- Windows 10
- Fixes #3613
> (#3613) Add source uri override for download uris

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
The System.Linq.Dynamic.Core package is actually not being used, so it is safe to remove from the project.
This came up as a Depdendabot security report, which prompted us to check whether this was being used.  When it was found that it isn't, the decision was made to remove it, rather than updating it.
Run full suite of integration tests.
N/A
N/A
> (maint) Remove unused dependency

- .teamcity/settings.kts
- recipe.cake
This updates the branch filter for the normal Chocolatey build to
exclude any support branches from being built by our internal build
server.
We do not want support branches to build directly when they are not tagged, similar to how we are expecting builds to happen for the master branch.
N/A, can this be tested?
N/A
N/A
> (maint) Exclude support branches to branch filters

- recipe.cake
- src/chocolatey.console/Program.cs
- src/chocolatey/GetChocolatey.cs
This updates the warning that is outputted in non-elevated mode to not
be outputted when the user has not specified `--trace` on the
commandline.
Without this change, any time a use are running in a non-elevated mode,
they will always have the trace warning outputted even when they haven't
used the argument.
Do the following tests in a non-elevated window.
1. Run `choco search chocolatey` (or any other command not requiring admin privileges).
2. Ensure that the warning about `--trace` not being supported are not shown.
3. Run the same command again and specify `--trace` .
4. Ensure that the warning about `--trace` are now outputted.
In an admin window repeat the above tests, verifying that the trace warning is not outputted.
- Windows 10
Fixes #3621
> (#3621) Skip trace warning when trace not used

- .teamcity/settings.kts
This updates the settings.kts file by moving the support filter from VCS
to the VCS filter.
This is believed to be the correct place to be able to filter out the
support branch, while still being able to manually initiate a build on
the branch.
N/A
N/A
N/A
> (maint) Move support exclusion to VCR filter

- docs/legal/CREDITS.md
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/packages.config
This updates the Chocolatey NuGet package references to the latest
version available that was just recently created.
This new version fixes a problem in Chocolatey CLI where we are unable
to search for packages that starts with a prefix in an identifier.
We want to fix the bug in Chocolatey CLI where you are unable to search for anything other than the prefix `chocolatey` when using `--id-starts-with`.
1. Run `choco search sysinternals --id-starts-with`.
2. Verify that the sysinternals package is listed.
- Windows 10
Fixes #1836
> (#1836) Update Chocolatey NuGet references

- .github/workflows/build.yml
- .github/workflows/test.yml
Update to action/cache v4.
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
The GHAs attached to this PR should complete successfully.
N/A
* Fixes #3650
> (#3650) Update GitHub Action to use cache@v4

- src/chocolatey/infrastructure.app/configuration/ConfigurationOptions.cs
combintation -> combination
Fixed a typo that was noticed while reviewing other code.
Once seen, it cannot be unseen, and must be fixed.
N/A
N/A
N/A
> (doc) Fix typo

- src/chocolatey.tests/infrastructure/commandline/InteractivePromptSpecs.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/services/PowershellService.cs
- tests/pester-tests/commands/choco-install.Tests.ps1
Changed the prompt of `Do you want to run this script?([Y]es/[A]ll - yes to all/[N]o/[P]rint)` to `Do you want to run this script?([Y]es/[A]ll/[N]o/[P]rint)`
Unnecessary info as the command line app should assume the user knows what `[A]ll`, and this feature already exists for every other modern package manager on linux.
No tests have been performed.
Resolves #2848
> Removed `[A]ll - yes to all`

- src/chocolatey.resources/helpers/functions/Install-ChocolateyZipPackage.ps1
`Install-ChocolateyZipPackage` calls `Get-ChocolateyUnzip` which outputs
the passed in `$destination`. Consequently, `Install-ChocolateyZipPackage`
outputs the passed in `$unzipLocation`.
> Fix documentation for `Install-ChocolateyZipPackage` output

- src/chocolatey/infrastructure/licensing/LicenseValidation.cs
- tests/pester-tests/features/LimitOutput.Tests.ps1
Update the logic used in LicenseValidation class to correctly detect when regular output is desired and when it's not.
When there are certain license conditions, Chocolatey would report things to standard output even if the command issues was requesting to limit output.
1. Put a file in the `license` directory and ran `choco list --local-only --limit-output`
2. Then ran `choco list --local-only --limitoutput`
3. Then ran `choco list --local-only -r`
4. Noted that there is some warnings and errors about missing directories (I followed these as far as I could, at least one is generated by a System provided library, and unlikely that we can suppress)
5. When the lib directory is there (which it is on a standard Chocolatey install), no errors are output.
6. Set an empty file as …
> (#2851) fix license validation output

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateySupportCommandSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateySupportCommand.cs
- tests/pester-tests/commands/choco-support.Tests.ps1
This commit introduces a new choco support command for Chocolatey CLI. This command already exists for Chocolatey Licensed Extension, but the decision was made to also introduce it into open-source, for consistency reasons.  The output from this version of the command is different to what is shown when you have a license in play, as it points the user to the open-source resources, rather than to reach out to the support team.
Also included is some unit tests and some pester tests, to ensure that the command is working as expected.
After discussion with the support team, having the `choco support` command in both CLI and CLE makes a lot of sense, and will help people find the help that they need.
1. Check out and build PR
2. Run `choco support` and verify the output
3. Run `choco support …
> (#3668) Add choco support command

- src/chocolatey.resources/helpers/functions/Install-ChocolateyFileAssociation.ps1
This commit adds additional parameter to the function, with the default value that maintains full backwards compatibility.
This allows for greater control over the arguments that are passed through when setting up the file association.  This allows for scenarios where you might need to do something like `-o "%1"` when the default is to do something like `"%1" "%*"`.
This change allows for full backwards compatability, so no additional testing has been completed.
N/A
Fixes #1176
> (#1176) Extend Install-ChocolateyFileAssociation

- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyFeatureCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyLicenseCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateySourceCommandSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyLicenseCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/domain/LicenseCommandType.cs
- tests/pester-tests/commands/choco-license.Tests.ps1
- tests/pester-tests/commands/choco-support.Tests.ps1
This PR adds a delightful new command, `choco license`.
It should offer read _and_ write, but at the moment just offers a basic output of the current license.
It doesn't yet have tests, either.
This has been requested by awesome folk!
1. We have tested it locally
Fixes #2829
> (#2829) Adds Basic choco license Command

- .gitignore
- nuspec/chocolatey/chocolatey/chocolatey.nuspec
- nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
- nuspec/chocolatey/chocolatey/tools/init.ps1
- tests/Vagrantfile
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
- tests/pester-tests/powershell-commands/Get-EnvironmentVariableNames.Tests.ps1
1. Remove the mention of `choco list -lo` from the NuSpec file.
2. Update an `upgrade all` test to ensure that it does not report failure if a newer Chocolatey version is available on internal repositories.
3. Use `PowerShell` instead of `powershell`.
4. Fix `Get-EnvironmentVariableNames` tests to run.
5. Update Vagrant box used for building and running tests to use the `chocolatey/test-environment` box.
1. Local Only on the `list` command was removed in 2.0, and is an error now.
2. When tests are running as we come up towards a release, we end up with reports of failures of the upgrade all command because for instance it will be testing version `2.4.1-beta-20241204`, but because of the way the builds work, CI will have build and published to our repository version `2.5.0-alpha-20241204` …
> (maint) Correct some typos and fix some tests

- src/chocolatey/StringResources.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/configuration/EnvironmentSettings.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- tests/pester-tests/features/EnvironmentVariables.Tests.ps1
This commit adds the ability to output the previous package version, during say a `choco upgrade` command, as an environment variable. Prior to this commit, it was only the package version that was currently being installed/upgraded that was presented as an environment variable.
The method that is responsible for writing the environment variables is the PreparePowerShellEnvironment method, which is defined by the IPowershellService interface.  Rather than make a change to the interface to pass in this information, it was decided to add a property to the ChocolateyConfiguration class, which is currently being passed through to this method.  This means that there is some maintainability in place, where additional information can be passed through as environment variables in the future, …
> (#1713) Previous package version as env variable

- src/chocolatey.resources/redirects/RefreshEnv.cmd
- tests/pester-tests/features/RefreshEnvCmd.Tests.ps1
This commit adds this replacement, in addition to moving the endlocal further down the file, so that the EnableDelayedExpansion is in place when the operation is done.
When an environment variable contains a "|" character, during the process of hydrating the values, the "|" causes an error, as it is attempting to do "something" when executing the "set" command, from the _env.cmd file.  We suspect that the underlying problem is the combination of the " which is added to the environment variable by Windows itself, and usage of the | as a logical OR operation.  To get around this problem, we needed to escape the pipe character using a ^ character.  This is done using a replacement of a single "|" with "^|".
1. Apply the changes in this PR to your local `refreshenv.cmd` file
2. Create an …
> (#3294, #1664) Handle "|" and "&" in environment variable value

- .github/workflows/build.yml
- .github/workflows/test.yml
- Updated Windows runner in CI workflow from windows-2019 to windows-latest.
- Added Mono installation steps to GitHub workflow jobs for both test and build.
- Changed runner environment to ubuntu-latest for improved compatibility.
- Included Mono repository setup and installation commands in workflows.
- To keep the build environment current with the latest Windows updates and tools.
- To ensure the required Mono runtime is available during CI runs.
- To improve compatibility and reduce maintenance overhead in CI workflows.
- To avoid build environment failing when windows-2019 is removed later in June.
- Verified CI workflows run successfully with updated runners and Mono installation. (https://github.com/AdmiringWorm/choco/actions/runs/15609863589)
- Windows (windows-latest) (_GHA_)
- …
> (#3633) Update GHA build runners and install mono on Ubuntu runner

- tests/pester-tests/commands/choco-support.Tests.ps1
- tests/pester-tests/features/CredentialProvider.Tests.ps1
Add --ignore-http-cache to credential provider test to prevent cached results from interfering when credentials differ. This ensures more reliable test outcomes for package source authentication.
Refactor support command tests by moving license check to BeforeAll for better setup consistency. Also, update test description to clarify it verifies the presence of the support command title in help output.
To update tests that have transitive failures or is make use of incorrect logic as well as making our internal test kitchen build succeed.
Some manual testing was done, but will be properly tested on internal test kitchen
- Windows 11
- PROJ-1366
> (maint) Improve credential provider and support command tests

- src/chocolatey/StringResources.cs
- src/chocolatey/infrastructure.app/services/PowershellService.cs
- tests/pester-tests/features/EnvironmentVariables.Tests.ps1
This commit introduces a new ChocolateyNotSilent environment variable, which will be set when the user makes use of the --not-silent command line argument.
In addition, a new Pester test assertion has been added to check for the presence of the environment variable.
This is useful, as it will allow package maintainers to take additional actions in their scripts, when required.  An example of this would be when a package uses an autohotkey script to perform the installation. Passing the --not-silent argument here does nothing, and the autohotkey script is still ran.  The presence of this environment variable can now be used as a trigger for "if" the autohotkey should be run.
1. A new pester test assertion has been added to ensure that this new environment variable is output
N/A
Fixes #3666
> (#3666) Add ChocolateyNotSilent env variable

- .vscode/settings.json
- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- tests/pester-tests/chocolateyProfile.Tests.ps1
Using a newly created spreadsheet which lists all the
command/subcommands/options for Chocolatey CLI, update the
ChocolateyTabExpansion.ps1 file to use this "source of truth". This
includes adding missing commands/subcommands/options where required. In
addition, the new default option for each command is applied, and these
will be used elsewhere going forward, i.e. in our documentation, so that
we can start to get some consistency.
We need to ensure consistency across Chocolatey CLI's "API", and this is a first
pass at getting to a known set of command/subcommands/options for tab
completion, and once this is rolled out, these default options will flow into
our documentation.
We will complete a Test-Kitchen execution on this PR branch to ensure everything works as expected.
Windows 11 …
> (#3700) Overhaul ChocolateyTabExpansion.ps1

- src/chocolatey.tests/infrastructure.app/utility/ArgumentsUtilitySpecs.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/PowershellService.cs
- src/chocolatey/infrastructure.app/utility/ArgumentsUtility.cs
- tests/pester-tests/commands/choco-info.Tests.ps1
- tests/pester-tests/commands/choco-install.Tests.ps1
- tests/pester-tests/commands/choco-upgrade.Tests.ps1
- Escape single quotes in PowerShell arguments by doubling them to handle parameters containing single quotes correctly; added Pester tests for validation.
- Refactor argument parsing to properly handle package arguments with double-dash syntax (--), including quoted strings and nested quotes; added tests for upgrade scenarios.
- Add warnings for unbalanced single or double quotes in package arguments during install, upgrade, and uninstall commands, with troubleshooting advice for upgrades and uninstalls; included tests for warning behavior with remembered arguments.
Packages should be possible to install and upgrade even with single quotes being used, and not having an exception about "unterminated single quotes" being thrown.
1. Enable the feature `useRememberedArgumentsForUpgrades` …
> (#2410) Update arguments utility to handle package parameters starting with dashes

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- src/chocolatey.tests/MockLoggerExtensions.cs
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateySearchCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/NugetListSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateySearchCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/domain/PackageOrder.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
This change adds a new command line option "order-by", allowing the user to specify a few sorting strategies. By default the results will be sorted by id.
To allow uses to decide how they want the results being sorted when we can.
These tests assume you only have the Chocolatey Community Repository enabled as a source.
1. Do a search using `choco search chrome --order-by='id'`
2. Verify the resulting set is ordered by the Identifier with the first entry being 1password-chrome
3. Do the same search using `--order-by='title'`
4. Verify the first entry is `choco-protocol-support` (It is prefixed with `(unofficial)` in the title, and is expected to be the first result in this case.
5. Search again using `--order-by='popularity'`
6. Verify the package with most downloads is returned first (at …
> (#3709) Add support for ordering strategies using a new `--order-by` argument on the search command

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyConfigCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyNewCommandSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyConfigCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyNewCommand.cs
This commit addresses this inconsistency, and also adds tests to cover the change.
The short -n variant for the name option was missing on the choco new and choco config command.  This is inconsistent with the name option on for example the choco feature and choco pin commands.
Ran unit tests.
- Windows 11
Fixes #3713
> (#3713) Add short -n variant of option

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- src/chocolatey/OutputHelpers.cs
- src/chocolatey/StringResources.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/ApplicationParameters.cs
- src/chocolatey/infrastructure.app/builders/ConfigurationBuilder.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyApiKeyCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyLicenseCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyRuleCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
- tests/helpers/common/Chocolatey/Invoke-Choco.ps1
- tests/pester-tests/commands/choco-apikey.Tests.ps1
- tests/pester-tests/features/Headers.Tests.ps1
When a user asks for limited output from Chocolatey, it is not uncommon to pipe that output to `ConvertFrom-String` or `ConvertFrom-Csv` and manually add headers to get back an object. This allows for getting a header row back so that the end user doesn't need to add their own headers and discern what they are.
Adds a new feature that allows the user to always display the headers if desired. This defaults to off so that we don't break any existing scripts.
Reduce the amount of work end users need to do in order to consume limited output.
Ran through the tests in the Vagrant test environment. This resulted in two failures that appear unrelated to my changes. I will investigate those further before marking this PR as ready.
**NOTE:** This will require Chocolatey Licensed Extension changes. …
> (#2591) Add headers to limit output commands

- tests/pester-tests/features/Headers.Tests.ps1
Update Pester tests to include some scenarios when only testing OSS Chocolatey CLI.
Since the concept of including a header row has _not_ yet been added to Chocolatey Licensed Extension, when running tests when it is installed will fail, as the header rows will not be output correctly. Until a new release of Licensed Extension is made (the currently released version is 6.3.1), we can only run the following tests when running open source Chocolatey CLI.
Test-Kitchen tests will be completed based on this PR.
- Windows 11
Relates to #2591
> (#2591) Update tests for failing CLE Test-Kitchen

- src/chocolatey.tests/Resources/SampleResource.txt
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/attributes/CommandForAttributeSpecs.cs
- src/chocolatey.tests/infrastructure/adapters/AssemblySpecs.cs
- src/chocolatey.tests/infrastructure/adapters/ConsoleSpecs.cs
- src/chocolatey.tests/infrastructure/adapters/EnvironmentSpecs.cs
- src/chocolatey.tests/infrastructure/commandline/InteractivePromptSpecs.cs
- src/chocolatey.tests/infrastructure/commandline/OptionsSpecs.cs
- src/chocolatey.tests/infrastructure/commandline/ReadKeyTimeoutSpecs.cs
- src/chocolatey.tests/infrastructure/commandline/ReadLineTimeoutSpecs.cs
This pull request improves test coverage and reliability across multiple components by adding comprehensive unit tests:
- Added tests for `CommandForAttribute` to verify Description, Version, and multiple attribute usage.
- Added extensive tests for `InteractivePrompt` covering timeouts, default choices, password input, and retry logic.
- Added comprehensive tests for `OptionSet` command line parsing, including various option scenarios and error handling.
- Added tests for `ReadKeyTimeout` to verify timeout behavior returns default Enter key.
- Added tests for `Assembly` adapter covering assembly retrieval, type listing, resource names, and obsolete methods.
- Added detailed tests for `Console` adapter covering input/output methods and behavior when prompts are disabled.
- Added tests for …
> (maint) Add additional unit tests to cover existing functionality

- src/chocolatey.resources/helpers/ChocolateyTabExpansion.ps1
- tests/pester-tests/chocolateyProfile.Tests.ps1
This commit improves the PowerShell Tab Completion for Chocolatey CLI, by including completions for the following commands:
* apikey
* config
* feature
* pin
* rule
* source
* template
Each of these completions rely on directly calling the equivalent "list£ sub-command for each command (with the exception of one of the pin completions, which also relies on running choco list), which unfortunately can take a second to complete.
As a future enhancement to this functionality, we should look to serializing these completions to disk, so that they can be loaded and shown from there. These files would be updated each time an associated command is executed. For example, when someone runs "choco source add" update the completions file for when doing "choco source remove".
A group of Pester tests …
> (#669) Improve PowerShell Tab Completion

- tests/Vagrantfile
- tests/pester-tests/chocolateyProfile.Tests.ps1
Update the `Vagrantfile` used in the repository to prefer and work with Hyper-V.
This also adds a Context block to the Tab Expansion tests to skip over the tests that require an official Chocolatey CLI.
The Chocolatey Software team is standardizing on Hyper-V with Vagrant, and so this repository should work with it.
1. In the tests directory, run `vagrant up`.
2. Ensure that the hyperv is used as the provider.
3. Ensure that the bulk of the tests pass. (There are a number of tests that fail for various reasons in the Vagrantfile. It is beyond the scope of this PR to address them. The main concern of this PR is that the environment builds Chocolatey, and executes tests.)
- Windows 11 host.
- Fixes #3749 
- ENGTASKS-4461
> Prefer Hyper-V for the vagrant local testing

- docs/legal/CREDITS.json
For some dependencies, they do not contain a tag or a version in the repository. Instead of linking to the license of master or main, we now link to the permalink to better track history over time. We do not want this going to master or main incase a license type changes in the future and the dependency becomes inaccurate. An "info" entry has been added as well, to explain this change further.
We want the links to be as accurate as possible, and we also want to provide information on how/why we got the link.
n/a
#3672
> (#3672) Add "info" to default license links

- Invoke-Tests.ps1
- tests/pester-tests/commands/choco-search.Tests.ps1
That is no longer the case, and it is now possible to test the following command line options:
- --download-cache
- --not-broken
- --approved-only
- --id-starts-with
- --by-id-only
- --by-tags-only
- --order-by-popularity
- --order=""
and to make assertions on the results, based on a known collection of packages existing in the repository.
The Tag that is applied to each of these tests to allow exectuion of these tests only at certain times, and not as part of the default execution of these tests.
There are a number of additional Chocolatey CLI command line options that are only intended to work when Chocolatey Community Repository is being used.  Previously, these options were not tested, as the infrastructure to exercise these didn't exist.  
Manual Developer tests were completed to …
> (tests) Add Pester tests to cover searching CCR

- tests/pester-tests/commands/choco-push.Tests.ps1
Update the Push tests to use the proper local CCR URL, and to explicitly add the push source.
- The push tests in CCR were getting the wrong response because they were pushing to the wrong endpoint.
- Pushing to Nexus requires that the nexus repository also be added as a source so that a username and password can be provided.
Running in Test Kitchen.
Windows Server 2019
N/A
> (tests) Update push tests to set API key if CCR

- tests/pester-tests/commands/choco-install.Tests.ps1
Exclude a test from CCR testing.
This test doesn't exercise anything outside of the local system, so is not needed for CCR testing.
N/A - This is merely excluding an existing test from one of the Test Kitchen suites. The only testing we could possibly do is target the CCR tests to this branch and ensure they don't run this one test.
N/A
N/A
> (tests) Exclude test from CCR testing
