chocolatey/choco

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/MockLogger.cs
- src/chocolatey.tests/TinySpec.cs
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/AutomaticUninstallerServiceSpecs.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/domain/CommandNameType.cs
- src/chocolatey/infrastructure.app/domain/PinCommandType.cs
- src/chocolatey/infrastructure.app/registration/ContainerBinding.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
Adds pin command. Nuget is giving me grief so testing specifics of
add/removing a pin isn't yet complete.
Be able to pin and suppress upgrades for pinned packages.
Closes #1
> (GH-1) pin command

- .travis.yml
> Add travis.yml file for building on mono

- nuget/chocolatey/tools/chocolateysetup.psm1
"awhile" -> "a while"
per http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Usage/faq0016.html :)
> (doc) Update chocolateysetup.psm1 - fix grammar

- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
Fixes https://github.com/chocolatey/choco/issues/480
> (GH-480) /All should be the final argument to dism.exe

- README.md
Fixed some typos in the readme.md.
> Readme typos fixed.

- src/chocolatey/infrastructure.app/services/ConfigTransformService.cs
- Use Mutex to ensure that file is only used for each transformation
- Verify by loading transformed file that it contains valid XML
- Restore backup file in the event of an error
Fixes #1482
> (GH-1482) Improve handling of XDT Transform errors

- src/chocolatey/infrastructure.app/domain/RegistryValueExtensions.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageInformationService.cs
- src/chocolatey/infrastructure.app/services/RegistryService.cs
- src/chocolatey/infrastructure/services/IXmlService.cs
- src/chocolatey/infrastructure/services/XmlService.cs
> (GH-1505) Ensure package information from registry is escaped

- src/chocolatey.resources/helpers/functions/UnInstall-ChocolateyZipPackage.ps1
> (GH-1415) Correct issue with remove zip file contents

- COMMITTERS.md
- CONTRIBUTING.md
* Replaced the invalid URL with the new location
* Fixed typo
Because this is a minor change I didn't raise an issue.
> (doc) Fix docs

- src/chocolatey/EnumerableExtensions.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/configuration/ConfigFileApiKeySetting.cs
- src/chocolatey/infrastructure.app/configuration/ConfigFileConfigSetting.cs
- src/chocolatey/infrastructure.app/configuration/ConfigFileFeatureSetting.cs
- src/chocolatey/infrastructure.app/configuration/ConfigFileSettings.cs
- src/chocolatey/infrastructure.app/configuration/ConfigFileSourceSetting.cs
- src/chocolatey/infrastructure.app/utility/HashCode.cs
So that we can rely on the generated hash code to make informed decisions about whether a change has been made to the chocolatey.config file or not.
Fixes #1612
> (GH-1612) Added consistent generation of hash code

- src/chocolatey.tests/infrastructure.app/commands/ChocolateyPinCommandSpecs.cs
- src/chocolatey.tests/infrastructure.app/services/AutomaticUninstallerServiceSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPinCommand.cs
- src/chocolatey/infrastructure.app/services/AutomaticUninstallerService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageInformationService.cs
- src/chocolatey/infrastructure.app/services/IChocolateyPackageInformationService.cs
> (GH-1580) Only output log messages when RegularOutput is enabled

- .github/ISSUE_TEMPLATE/zChocoReportIssue.md
Add missing start of comment block in issue template
> Add missing start of comment block in issue template

- GenerateDocs.ps1
- src/chocolatey.resources/helpers/functions/Get-CheckSumValid.ps1
- src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyPowershellCommand.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyVsixPackage.ps1
- src/chocolatey.resources/helpers/functions/Install-ChocolateyZipPackage.ps1
- src/chocolatey/infrastructure.app/templates/ChocolateyReadMeTemplate.cs
- src/chocolatey/infrastructure.app/templates/ChocolateyTodoTemplate.cs
https://github.com/chocolatey/choco/issues/2205
> (#2205) Update automatic-packages docs links

- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
I noticed _it could be in package or default install location *if*
installer_ and changed to _it could be in package or default install
location *of* installer_.  Then found a few more grammar and spelling
opportunities...
> (maint) Spelling and grammar fixes.

- src/chocolatey.resources/helpers/functions/Install-ChocolateyPackage.ps1
Fixes #1899 
This is my first contribution, be gentle :)
> (GH-1899) Remove unused variables

- .github/workflows/build.yml
There is a known issue with building on Mac currrently, so let's
concentrate on just these two operating systems for now.
Relates to #2244
> (#2244) Initial workflow for Windows and Ubuntu

- src/chocolatey.resources/helpers/chocolateyInstaller.psm1
- Partially revert #2335 so that we explicitly look for and load `chocolatey.licensed.dll` as a PowerShell module when setting up for package installs, if the extension is available
- Little bit of cleanup because this file was difficult to read through.
#2335 inadvertently broke any package installations that required cmdlets only available from the licensed extension as we stopped loading the extension into the PowerShell session's modules.
See #2340 
1. Install Chocolatey
1. Install chocolatey.extension
1. Install chocolatey-agent
1. Installations should all succeed.
#2340
> (#2340) Ensure licensed extension is loaded during install when available

- src/chocolatey/infrastructure.app/services/NugetService.cs
Updates message with details of the current CCR moderation process.
Adds a link to the moderation documentation.
The current message was written for an older CCR moderation process, and it not accurate anymore.
N/A
Fixes #2298
* N/A Requires a change to the documentation
* N/A Tests to cover my changes, have been added
> (#2298) Update post push to CCR message

- README.md
Checked the links, skipping the redirect HTTP => HTTPS this way for some at least 0:-)
I'm probably not completely in order of the contributing guidelines, so feel totally free to close this PR and add the changes yourself :)
> README.md: some HTTP => HTTPS

- src/chocolatey.resources/helpers/functions/Get-ToolsLocation.ps1
- src/chocolatey/infrastructure.app/templates/ChocolateyInstallTemplate.cs
- src/chocolatey/infrastructure.app/templates/ChocolateyReadMeTemplate.cs
This merge request removes the examples to use Get-BinRoot in the template as they
are deprecated as of v1.0.0.
Additionally the powershell helper is updated to note that usage of the alias `Get-BinRoot` is deprecated, and the old `Write-Host` mentioning this is changed to be a warning and mention that it is deprecated.
To remove mentions of deprecated cmdlet, and make the warning of its usage more obvious.
1. Tested by running `choco new` to ensure that no mention of `Get-BinRoot` in any of the files.
2. Tested by creating a package using `Get-BinRoot` and verify that a warning is correctly outputted
Fixes #2470
> (#2470) Deprecate Get-BinRoot Chocolatey helper function

- src/chocolatey.tests/infrastructure.app/services/RegistryServiceSpecs.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyInstallCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyNewCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyPushCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyTemplateCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyUpdateCommand.cs
- src/chocolatey/infrastructure.app/commands/ChocolateyVersionCommand.cs
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure.app/domain/installers/MsiInstaller.cs
- src/chocolatey/infrastructure.app/domain/installers/MsiPatchInstaller.cs
- src/chocolatey/infrastructure.app/domain/installers/SetupFactoryInstaller.cs
- src/chocolatey/infrastructure.app/domain/installers/WindowsUpdateInstaller.cs
- src/chocolatey/infrastructure.app/registration/ContainerBinding.cs
- src/chocolatey/infrastructure.app/runners/GenericRunner.cs
- src/chocolatey/infrastructure.app/services/AutomaticUninstallerService.cs
- src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/ShimGenerationService.cs
- src/chocolatey/infrastructure.app/services/WindowsFeatureService.cs
- src/chocolatey/infrastructure.app/utility/ArgumentsUtility.cs
- src/chocolatey/infrastructure/commands/ExternalCommandArgsBuilder.cs
- src/chocolatey/infrastructure/licensing/ChocolateyLicense.cs
- src/chocolatey/infrastructure/licensing/LicenseValidation.cs
- src/chocolatey/infrastructure/registration/SecurityProtocol.cs
Adds in issue numbers for todo comments. There is also a minor amount of reformatting of some comments to make the todo format consistent.
There is also a commit to remove an outdated todo
A number of github issues have been added for todos that did not have an issue already existing.
This is to assist with tracking and triaging of things to do. 
Open up in Visual Studio, and check that the todo comments have issue numbers
N/A
> (maint) Link todo comments to issues

- .build/nugetBuild.step
- .build/versionBuilder.step
- .teamcity/settings.kts
- .uppercut
- Determine whether the commit that is being built is a tag, if it
is, alter the version numbers that are asserted by UppercuT
- Remove unnecessary entries in the VCS Branch Filter
- Remove unnecessary entries in the VCS Trigger Branch Filter
- Add additional branch names, tags/.* to the step where packages are
pushed to repository
- Add build feature to control the execution of pull requests made to
repository in GitHub
While the current TeamCity build is "working" for Chocolatey, there are a number
of additional configuration items that need to be addressed in order to get the build to do
everything that is needed.
The configuration changes were added to a build configuration on Artemis, and various branches,
tags, and changes, were made to that build to confirm that things are working …
> (build) Additional TeamCity configuration

- nuget/chocolatey/tools/chocolateysetup.psm1
Windows identifies a UTF8BOM file with just a newline as being signed. This is due to a javascript file somewhere in the OS that is Catalog Signed. As such, during installation, Chocolatey detects an otherwise empty Profile file as signed and doesn't add the profile.
1. Installed Chocolatey on a Windows 11 system
2. Ran the command `"" | Set-Content $profile -Encoding UTF8' in Windows PowerShell (PowerShell 7.2.2 requires encoding of `UTF8BOM`)
3. Verified the size of the file and confirmed it was seen as signed
4. Upgraded to locally built Chocolatey package
5. confirmed that file is no longer considered signed
Fixes #2663
> (#2663) Check file signature on 6 bytes

- TESTING.md
Updates command for running integration tests.
https://github.com/chocolatey/choco/commit/2864c01d72bd2fda1fa6833acdfcea2e51be16f5
N/A
Part of #2759
> (doc) Update command for running NUnit integration tests.

- docs/legal/CREDITS.md
- Update CREDITS.md to include version numbers and standardise its format to the other similar files we're putting together for other products.
This is mostly just updating it to match what was decided on for the more comprehensive document, as we plan to keep that up to date using this file in future.
We want a consistent(ish) format for these files so that they're easier to maintain along with the project so they stay up to date and accurate, and we can look to automatically generate them in future.
Doc change only, no code changes.
N/A
> (maint) Update CREDITS.md to include versions

- docs/legal/CREDITS.md
- Update ShimGen license in CREDITS.md
- Fix TOCs in CREDITS.md, ensure the shortlinks work, etc.
@corbob noticed that the shimgen license copy in the CREDITS document was out of date. We should keep these as up to date as possible.
- License in CREDITS.md should match the current license of [ShimGen](/chocolatey/shimgen).
N/A
> Update ShimGen license in CREDITS.md

- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
Keep ChocolateyConfiguration backups as a Stack rather than a single instance, so that code paths which call `start_backup()` multiple times before calling `reset_config(true)` don't cause errors.
The current behaviour causes errors when upgrading more than one package at a time.
1. Call choco with `upgrade curl wget -y`
2. Monitor the output
3. No errors about configuration backups should occur, and both installs should succeed
Fixes #2884
> (#2884) Store configuration backups as a Stack

- gitreleasemanager.yaml
Adding GitReleaseManager config so we can use GRM on this repo.
NOTE: we will need to cherry-picked into `support/1.x` after merging.
Make releases easier.
Tested "live" by using GitReleaseManager with this yaml file to close off the `1.2.1` milestone.
N/A
N/A
> (maint) Add GitReleaseManager.yaml

- .github/workflows/build.yml
- .github/workflows/test.yml
This updates the various actions used in the workflows used on Github Actions.
There are currently a number of warnings about deprecated items with the current workflow:
https://github.com/chocolatey/choco/actions/runs/3686741207
Updating the version of the actions used will resolve these warnings. 
Pushed commit and waited until the actions run was done. 
Validated that the builds succeeded and that the deprecation warnings have been resolved:
https://github.com/TheCakeIsNaOH/choco/actions/runs/3687030045
N/A
Depends on #2927
> (build) Update GitHub workflow action versions 

- Invoke-Tests.ps1
- docs/legal/CREDITS.md
- src/chocolatey.console/Program.cs
- src/chocolatey.console/chocolatey.console.csproj
- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey/FileSystemExtensions.cs
- src/chocolatey/GetChocolatey.cs
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/configuration/ChocolateyConfiguration.cs
- src/chocolatey/infrastructure/registration/AssemblyResolution.cs
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/packagewithscript.nuspec
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/tools/chocolateyBeforeModify.ps1
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/tools/chocolateyinstall.ps1
- tests/chocolatey-tests/commands/testpackages/packagewithscript/1.0.0/tools/chocolateyuninstall.ps1
- tests/helpers/common/Chocolatey/Invoke-Choco.ps1
Manual resolution of merge conflicts when merging hotfix/1.2.1 into `develop`
More careful merge with review here due to divergence between the hotfix/support and develop branches.
N/A?
N/A
N/A
> Merge changes from hotfix/1.2.1

- src/chocolatey/infrastructure.app/templates/ChocolateyVerificationFileTemplate.cs
Removed the test that indicates checksums are optional for software authors / vendors.
Everybody, including vendors, are required to provide instructions on how to verify checksums for embedded binaries.
N/A
N/A
Fixes #2920
> (#2920) Change VERIFICATION.txt template for vendors

- README.md
This updates the build documentation to reflect the current requirements to build Chocolatey CLI now that it builds with Cake and .Net 4.8
To have better information about building Chocolatey CLI
N/A
N/A
Part of #2738
https://app.clickup.com/t/20540031/PROJ-429
> (#2738) Update build documentation for .Net 4.8 and Cake

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/packages.config
This pull request update the NuGet packages we use in the project to the latest pre-releases we have pushed to nuget.org
To keep up to date
1. Did some very quick testing of the usual Chocolatey commands, rather than a complete run through of manual testing, as the majority of the changes in the NuGet.Client libraries have been tested in isolation when reviewing those PR's
- Windows 10
#508  
https://app.clickup.com/t/20540031/PROJ-415
> (#508) Update NuGet libraries to latest

- src/chocolatey/infrastructure.app/nuget/NugetPush.cs
- tests/chocolatey-tests/commands/choco-push.Tests.ps1
* Update Push command to not ignore duplicate packages reported from repositories
* Update tests to work with the new wording of NuGet push failures
* Add some wording to the NuGet push tests to indicate which version it was attempting to push.
* The initial implementation wasn't throwing when `409` was returning from the server.
* Tests were disabled as they weren't correctly throwing
* Ran tests in Team City against the PR build targeting this branch for the pester tests. This resulted in 11 failed tests (22 total as we test two OSes). The 4 related to NuGet feed pushes are known to fail in Team City, and do not relate to the push failing, more that we couldn't verify the push was successful as Team City run Test Kitchen isn't getting package listings at the moment. The other 7 tests …
> (#508) Fix NuGet pushes to correctly result in errors

- tests/chocolatey-tests/commands/choco-push.Tests.ps1
Corrects use of credentials with find command within the choco-push tests.
The tests were failing in odd ways. On investigation, it seems that it was likely matching credentials on an added source with the right path, and ignoring the (invalid) `--api-key` argument being passed in. Credentials should be used for the list command.
* ~[ ] Feature / Enhancement (non-breaking change).~
* ~[ ] Breaking change (fix or feature that could cause existing functionality to change).~
* ~[ ] Documentation changes.~
Note: The changes in PowerShell were only to Pester test files.
* ~[ ] Requires a change to the documentation.~
* ~[ ] Documentation has been updated.~
* ~[ ] Tests to cover my changes, have been added.~
Note: This seems to only pass more tests - but I am unsure all tests are passing within …
> (#508) Fixes issue with flaky choco-push tests

- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- tests/chocolatey-tests/commands/choco-list.Tests.ps1
This pull requests main purpose is to fix the query that is being used when searching for packages and the user specifies the `--version` query. This is done to be able to get the correct results that should be available on the server (there is a problem with CCR itself that returns the wrong results).
Additionally this pull requests make two additional fixes that came along for the ride by allowing a pre-release version to be used when searching without having to specify `--pre` manually, and to output the correct results when paging is being used.
To keep behavior between v1 and v2 as close as possible, while still retaining expected output.
Assuming access to internal feed is available, and it is the only feed:
- Run `choco search upgradepackage --version 1.0.0`
- Verify 1 result is …
> (#508) Fix no results can be found when searching for specific versions

- src/chocolatey/infrastructure.app/services/NugetService.cs
- Pull duplicated code into a shared method on NugetService
- Refactor duplicate code into a loop to make it simpler to add additional cases if we find any more error message patterns
- Relegate the warning about us developers missing an error case to a debug message; users don't care about that and they can't do anything about that
- Avoid double-logging the same error message in the case of a straightforward "Unable to resolve dependency 'thing'" from NuGet
- Avoid potentially logging the same error message potentially multiple times for no apparent reason
There was still at least one case where the dependency resolution failure message came back without a dependency name, when there was a circular dependency chain.
Added a case for that error type and also refactored this code to …
> (#508) Fix dependency resolution error messages

- src/chocolatey.tests/TinySpec.cs
- src/chocolatey/BannedSymbols.txt
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/nuget/NuGetEndpointResources.cs
- src/chocolatey/infrastructure.app/nuget/NuGetEndpointResourcesExtensions.cs
- src/chocolatey/infrastructure.app/nuget/NugetCommon.cs
- src/chocolatey/infrastructure.app/nuget/NugetList.cs
- src/chocolatey/infrastructure.app/nuget/NugetPush.cs
- src/chocolatey/infrastructure.app/services/NugetService.cs
- src/chocolatey/infrastructure.app/services/TemplateService.cs
- tests/chocolatey-tests/commands/choco-info.Tests.ps1
- tests/chocolatey-tests/commands/choco-install.Tests.ps1
- tests/chocolatey-tests/commands/choco-search.Tests.ps1
- tests/chocolatey-tests/commands/choco-upgrade.Tests.ps1
This pull request fixes an issue where failure on a source when resolving dependencies would stop the entire execution of an installation or upgrade.
Additionally, as it was required when fixing this issue, and to prevent us from blocking ourself in future related issues some refactoring was made to create a new class that holds and lazily loads any resources that we make use of when connecting to different source endpoints and replace all uses of the previously generated tuples to instead look up any cached resources (or create new resource group when the source hasn't been used yet).
To make sure installations succeed, even if there is a problem with a single unrelated source.
1. Enable the Chocolatey source.
2. Add a new source for the licensed repository (to make sure queries still …
> (#508) Fix issues when resolving dependencies and connecting to sources

- src/chocolatey.tests/infrastructure.app/services/ChocolateyConfigSettingsServiceSpecs.cs
- src/chocolatey/infrastructure.app/services/ChocolateyConfigSettingsService.cs
Output the de list of features in alphabetical order
It's easier to search through the feature list when they are in a predictable order.
Added a test that check the order in which features are outputted in de MockLogger. Tested that the order of the features is alphabetical. I used a ShouldContain on the outputted messages because I'm only interested in the order and not the way it's formatted in the console.
Fixes #2814
> (#2814) Alphabetically sort the output from list commands

- README.md
- src/chocolatey.console/choco.exe.manifest
- src/chocolatey/infrastructure.app/templates/ChocolateyReadMeTemplate.cs
- src/chocolatey/infrastructure/platforms/Platform.cs
- Update readme/template
- Update application manifest to put 2008r2 as the minimum supported OS
Consistency with our documentation. Related to open docs PR: https://github.com/chocolatey/docs/pull/699
I'm not that certain if changing the app manifest really does anything tbh? AFAIK it's mainly just metadata. Other than that, all this is just doc changes.
N/A
Fixes #2903
> (#2903) Update minimum supported OS

- .github/workflows/stale.yml
Fixed GH action so it only runs against issues that have the `0 - Waiting on User` label. And the PR label for Pending Closure was incorrect.
Workflow is not running as it should.
N/A
N/A
This is a repository fix.
> (maint) Fix issue and PR labels for GH Action

- .teamcity/settings.kts
This PR adjusts the parameters used by the Docker builds in this project, specifically passing through credentials for pushing to Docker hub and resolving a private repo authentication issue on the Linux build.
The Docker builds were not completing successfully, this PR resolves that issue.
These changes have been tested on TeamCity and the build ran to completion including pushing to Docker Hub.
N/A
Relates to #3020
> (#3020) Adjust parameters on Docker builds

- src/chocolatey.tests.integration/chocolatey.tests.integration.csproj
- src/chocolatey.tests.integration/packages.config
- src/chocolatey.tests/chocolatey.tests.csproj
- src/chocolatey.tests/packages.config
- src/chocolatey/chocolatey.csproj
- src/chocolatey/infrastructure.app/commands/ChocolateyCacheCommand.cs
- src/chocolatey/packages.config
As part of the changes that is coming in our custom flavor
of NuGet.Client, the cache directories will now contain the
a new folder where lock files are located when issuing
HTTP requests.
The cache command needs to ignore these directories as
they may contain locked files that can not be cleaned up,
and is not part of the cached HTTP queries.
As the lock folders do not contain any cached HTTP requests, these folders are not valid for consideration when cleaning up files.
As such we need to ignore these.
1. Pull in latest NuGet.Client sources
2. Build a release build of Chocolatey CLI
3. Run a search in both elevated and non-elevated mode
4. Create at locked file in the ProgramData folder using `$f1 = [System.IO.File]::Open("C:\ProgramData\ChocolateyHttpCache\.locks\$(New-Guid)", …
> (#3264) Ignore lock folders in cache directories

- CONTRIBUTING.md
- TESTING.md
- tests/helpers/common-helpers.psm1
* Update Contributing.md to move testing section into Testing.md.
* Update Testing.md to include some guidelines to help reduce flaky tests.
Consolidate testing information into a single location. Improve communication of test guidelines.
N/A
Fixes #2710
> (#2710) Update repository documentation around testing

- README.md
- Add a note to the readme about our usage of editorconfig.
Make it a little clearer that we want folks to follow the established styles.
N/A
N/A
Fixes #13
> (#13) Add note to README about editorconfig

- .teamcity/settings.kts
- recipe.cake
Going forward, rather than signing PowerShell scripts on every build, which is a bit of a waste of effort, we are only going to sign the scripts when required.  The changes required to to do have been implemented in 0.28.0 of Chocolatey.Cake.Recipe under issue #149.
This commit updates the Chocolatey CLI build to make use of it.  This includes changes the DAG for tasks to depend on the new Verify-PowerShellScripts task, rather than the Sign-PowerShellScripts task.  In addition, a new Func is created to find the scripts that need to be verified, since this can, and is, sometimes different from the list of files that need to be signed.
This PR should be tested in combination with the PR into Chocolatey.Cake.Recipe, along with a new Build Configuration added to the settings.kts file from …
> (build) Update to latest Recipe package

- recipe.cake
- src/chocolatey.console/chocolatey.console.csproj
- src/chocolatey.resources/chocolatey.resources.csproj
- src/chocolatey/chocolatey.csproj
- Copy resource files to output directories during build
- Alter build to copy these files directly instead of using `-unpackself`
- Cleaned up a couple csproj files that had duplicated property-setting blocks for some build configurations that I noticed while fiddling with them.
This command is deprecated and slated to be removed in v3 so we need to not be using it.
1. Run `.\build.ps1 -Configuration ReleaseOfficial`
2. Inspect the generated nupkgs, compare to a previous release to ensure all the files seem to be in their proper places.
3. Copy the generated nupkgs to a fresh VM and then take a snapshot.
4. In a PowerShell admin shell, run the folllowing to install Chocolatey, using the path to the chocolatey nupkg:
```
${function:Install-Chocolatey} = [scriptblock]::Create((iwr …
```
> (#3427) Rework build to remove use of -unpackself

- .templates/contributors/contributor-details.sbn
- .templates/contributors/contributors.sbn
- .templates/contributors/index.sbn
- .templates/contributors/issue-details.sbn
- .templates/contributors/issue-note.sbn
This commit makes changes to the contributor template so that the manual tweaks will not be required going forward.
These tweaks were:
- Move the information about the issue number and who solved the problem in a PR, to it's own line.  The single line approach was getting very "busy" and it was decided that a new line made a lot of sense
- The title for "Contributors" was updated to use `###` rather than surrounding with '__'.  This was just so that things were consistent in the generated file.
- The if statement for including the milestone was corrected to only do the inclusion is the milestone description actually has some content. This change prevented the large gap that was left at the start of the file
- General spacing around each issue section was updated to remove empty lines
- …
> (maint) Update GitReleaseManager template

- nuspec/chocolatey/chocolatey/chocolatey.nuspec
- nuspec/nuget/Chocolatey.PowerShell/Chocolatey.PowerShell.nuspec
- nuspec/nuget/chocolatey.lib/chocolatey.lib.nuspec
- src/chocolatey.tests.integration/scenarios/UpgradeScenarios.cs
- tests/pester-tests/commands/testpackages/chocolatey-dummy-package/1.0.0/chocolatey-dummy-package.nuspec
- tests/pester-tests/commands/testpackages/too-long-description/1.0.0/too-long-description.nuspec
- tests/pester-tests/commands/testpackages/too-long-title/1.0.0/too-long-title.nuspec
Updated image urls to the new images location on the shared img repository.
All images need to be removed from their repositories and placed in the shared image repository to create one centralized img repo.
Open the solution in Visual Studio and make sure the solution builds ok.
n/a
#3792 
Fixes #3792
> (#3792) Update image urls
